### ISSUE TITLE
standalone.js:15 Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by tutq8118** [prettier/prettier#10102]
Hi there,

I used ReactJs (TypeScript), and imported the following codes:
```javascript
import prettier from "prettier/standalone";
import parserHtml from "prettier/parser-html";
import parserBabel from "prettier/parser-babel";
```
and used them for this function:
```javascript
const handleFormat = () => {
        const result = prettier.format(String(formatAreaRef.current?.value), {
            plugins: [parserHtml, parserBabel],
            printWidth: 9999,
            tabWidth: tabWidth,
            parser: "html",
        }); 
};
```
The developing environment worked well but the production did not, it said that:
```
standalone.js:15 Uncaught TypeError: Cannot convert undefined or null to object
    at getPrototypeOf (<anonymous>)
    at r (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:337956)
    at r.value (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:575987)
    at Object.t.parse (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:576454)
    at Xr (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:577197)
    at Kr (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:580504)
    at Object.parse (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:581378)
    at Object.parse (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:964307)
    at Pu (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:978642)
    at Ou (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:981192)
    at http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:1285652
    at Object.format (http://localhost:5000/static/js/2.aedcd80d.chunk.js:2:1285755)
    at http://localhost:5000/static/js/main.451f8ab1.chunk.js:1:7742
```
Please help me!

Thank you,

**Comment by thorn0** [comment]
Please provide a [way to reproduce the error](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff).

**Comment by tfrijsewijk** [comment]
I'm having the same issue as well, but as a dependency of https://github.com/whitespace-se/storybook-addon-html. I narrowed it down to prettier (ie: When I remove the call to prettier everything works). I'm running Node 12. Prettier 2.2.1.
