### ISSUE TITLE
Uncaught TypeError: runLinter is not a function

### ISSUE THREAD

**Issue by ewdave** [prettier/prettier#1063]
So I just updated my Prettier package on Atom, and when I tried formatting a codebase, I get a "runLinter is not a function" error. Code rightly formatted, though, but not sure this is something I should ignore

`Uncaught TypeError: runLinter is not a function`

```bash
TypeError: runLinter is not a function
    at executePrettierOnBufferRange (/Users/wale/.atom/packages/prettier-atom/dist/executePrettier.js:52:3)
    at format (/Users/wale/.atom/packages/prettier-atom/dist/format.js:22:5)
    at atom-workspace.lazyFormat (/Users/wale/.atom/packages/prettier-atom/dist/main.js:23:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by vjeux** [comment]
Sorry about that! Could you please ask the same thing on the `atom-prettier` repository as this one is the one for the core algorithm. Thanks! https://github.com/jlongster/prettier-atom
