### ISSUE TITLE
SyntaxError when using Template Literal Type 

### ISSUE THREAD

**Issue by bes** [prettier/prettier#11533]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKpuAQQCMxsBebAHRAEMbsAfakYh5msGgbitgLwESYAKJRaxADZwAJhWwADACTB8WYQF8xE6TIW8oIADQgIGGAEtoAZ2ShaAJwcQA7gAVHCWylqSXtNFsTYgdaMABrOBgAZQwwiygAc2QYBwBXOBMACxgAW0kAdSyLeGs4sDhorxKLADcStGRwayCQBOs4Bxg3UMTc2mQAM18OkwArawAPACFQiKjo2ly4ABkEuCGRzJAJyeiExOkARTSIeE3JUZA4hw6HJuIJOElja4cEmAKLGRgs5AAOAAMJgwzg6BVCGCaoLgd1qGxMAEdTvAemZvHRrABaKBwWSyV4OODIixEnq0PoDJDDS7bDq5CwpdJ0g7HFEbalbEwwCRfH5-JAAJm5oQskgOAGEILl+k1YQBWV5pDq4CTeGlXWoZACSUBkCBiYHe5kIeui6GkFw6Gg0QA)

```sh
# Options (if any):
{
  "trailingComma": "all",
  "tabWidth": 4,
  "semi": true,
  "singleQuote": false,
  "jsxBracketSameLine": false,
  "arrowParens": "always",
  "printWidth": 120
}
```

**Input:**

```jsx
type TypeAbc = "a" | "b" | "c";
type TypeAbcEnabled = `${TypeAbc}Enabled`;
```

**Output:**

```jsx
SyntaxError: Type expected. (2:23)
  1 | type TypeAbc = "a" | "b" | "c";
> 2 | type TypeAbcEnabled = `${TypeAbc}Enabled`;
    |                       ^
  3 | 
  4 | 
  5 | 
    at t (/Users/unknown/repo/node_modules/prettier/parser-typescript.js:1:287)
    at Object.parse (/Users/unknown/repo/node_modules/prettier/parser-typescript.js:14:2633274)
    at Object.parse (/Users/unknown/repo/node_modules/prettier/index.js:11370:19)
    at coreFormat (/Users/unknown/repo/node_modules/prettier/index.js:14784:25)
    at format (/Users/unknown/repo/node_modules/prettier/index.js:15019:75)
    at formatWithCursor (/Users/unknown/repo/node_modules/prettier/index.js:15035:12)
    at /Users/unknown/repo/node_modules/prettier/index.js:51620:12
    at Object.format (/Users/unknown/repo/node_modules/prettier/index.js:51640:12)
    at performFormat (/Users/unknown/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/212.5080.54/WebStorm.app/Contents/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:66:29)
    at PrettierPlugin.handleReformatCommand (/Users/unknown/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/212.5080.54/WebStorm.app/Contents/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:36:16)
Process finished with exit code -1

```

**Expected behavior:**

Prettier should not throw SyntaxError when trying to parse a Template Literal Type.

**Comment by fisker** [comment]
Are you using an old version of Prettier?

**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKpuAQQCMxsBebAHRAEMbsAfakYh5msGgbitgLwESYAKJRaxADZwAJhWwADACTB8WYQF8xE6TIW8oIADQgIGGAEtoAZ2ShaAJwcQA7gAVHCWylqSXtNFsTYgdaMABrOBgAZVoAWzgAGQsoOGQAM19rOGDQiKjojDCUgHNkGAcAVxyQODjiWRlZRNooEsraErgAMQgHONoYSzbkOkqYCGMQAAsYOMkAdWmLeGsisDhorxWLADcVtFGwayCQFOyHGDdQkoGMrJqAK2sAD2jS6QBFSoh4e8lsiYig4LqN0FhrGAHBZzFMMNDYAsLDIYNNkAAOAAMQOc2QWoQwo3hcAuuzSJgAjj94NczN46NYALSpWSyKYOOBUiwc66dO5ITIAmrZOIWcpVYUfODfX5pAUPEwwCRIlFopAAJkVoQsklKAGEIHF+bVrABWKaVbK4CTeQWAkC7aoASSgTVg0ShMJghFd0XQ0n+9ueLwAQnlIjF4kkUnK7XANBogA)

```sh
--parser typescript
```

**Input:**

```tsx
type TypeAbc = "a" | "b" | "c";
type TypeAbcEnabled = `${TypeAbc}Enabled`;

```

**Output:**

```tsx
type TypeAbc = "a" | "b" | "c";
type TypeAbcEnabled = `${TypeAbc}Enabled`;

```

**Comment by bes** [comment]
Prettier version was correct but WebStorm didn't pick up the change until restart.

**Comment by acnebs** [comment]
Just chiming in to say the same happened to me but with VSCode + Prettier, installed a new version of Prettier but needed to restart VSCode in order for it to be picked up.
