### ISSUE TITLE
TypeScript conditional types: Comment "TEST" was not printed. Please report this error!

### ISSUE THREAD

**Issue by benny-medflyt** [prettier/prettier#11660]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwFUoB3bAQwxIBMAlOAZwFcAbGJiSgHgAqAPjwBePMAA6UPHLwBtAAp4AlrIDWcQhABmeQQF0keABQz5lg8sN508KA1Z4WAR37rdcbHhqiA-GYWViE0wSEAlHgm5rIhVoI2dmgOTngA8hgwHlBePgBGAUFx8fH54aV4UTEVlfIA9PUGAKIAyoK1dXhQcABu3p2Rg1UVEQDcMgC+E1AgADQgEFmq0KzIoDTY2HxKmwhrKDSclDSEawv5tGBaMK0YNGDqAObIMNjscAtwALb5cAwMf4AGRoUCe7BoTzgADEcN8aDAYM9kCAaOwYBB5iAABYwb6cADq2NU8FY9zAcFa+xJql6JMIKLArHOIHUrG8MCUtCe8OQuiO7IWACtWGhWs9OHAAIrsCDwPkCz4ge7YdnYFFEEisMDYVRZLEYXWwAmqBgwbHIACMACYAAwLQ0QdkE2gYFGGtjefpY1yy+BcpYHVGsAC0PX+-yx2DgvtU0a5kN5SH5nEFIHZ31Ur3eStYEulfrgCtTSpgNHyJrNFqQ1oWbxoqk4zwAwhBvknUKwAKxY9jswTlg4ptO9D4ASUcCFuOr1MAAgo5WkRJcX2ZNJkA)

```sh
--parser typescript
--print-width 120
```

**Input:**

```tsx
export type UnwrappedResultRow<T> = {
    [P in keyof T]: (
        T[P] extends Req<infer a> ? (
            a
        ) : (
            T[P] extends Opt<infer b> ? (
                b
            ) : (
                // TEST
                never
            )
        )
    );
};

```

**Output:**

```tsx
Error: Comment "TEST" was not printed. Please report this error!
    at Object.ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:36:106741)
    at xd (https://prettier.io/lib/standalone.js:36:113165)
    at Nd (https://prettier.io/lib/standalone.js:36:115668)
    at Object.formatWithCursor (https://prettier.io/lib/standalone.js:76:39916)
    at formatCode (https://prettier.io/worker.js:141:21)
    at handleMessage (https://prettier.io/worker.js:78:26)
    at self.onmessage (https://prettier.io/worker.js:36:14)
```

**Expected behavior:**

**Comment by sosukesuzuki** [comment]
This is happened for only `babel-ts` parser

**Comment by sosukesuzuki** [comment]
minimal case

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAkigGcYCAzCCJAgCgB0oCCB6VoiAWy4RiZZQ4ANzi4mASgDcTEABoQEAA4wAltBLJQeXBADuABTwJNKbJj3YAnpoUAjXNjABrODADK2XgBlVQ5BTmJHD2ji5u7kpOfgDmyDC4AK4hIHBcdnCo6Kje2FAxidgxcABiELhc2DBq+cgg2IkwEPIgABYwXJgA6q2q8CRRYHDuJn2qwn1WdWAktiB+wbgwBo4xlQFBKQBWJAAe7rGYcACKiRDwG5jBClG4i3V22BmYALQwc0q4fjBdqqgwrWQAEYAEwABhuumCXUcSjqnzgi1ELQAjmd4CtlKZ6iQXkJMpkWvg0ap8CsiuskIErilglxVPEkrTDid0XBLtcQDAnr9-oCkCCFAlsKpMLEAMLcSmpEgAVhaiWCABUnqZqZzhMkAJJQdCwdxgL4qACCuvcMCsRw5cAAvjagA)

```sh
--parser babel-ts
--print-width 120
```

**Input:**

```tsx
declare const foo: (
  // comment
  never
);

```

**Output:**

```tsx
Error: Comment "comment" was not printed. Please report this error!
    at Object.ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:1:218494)
    at qD (https://prettier.io/lib/standalone.js:1:225762)
    at JD (https://prettier.io/lib/standalone.js:1:228265)
    at Object.formatWithCursor (https://prettier.io/lib/standalone.js:40:40390)
    at formatCode (https://prettier.io/worker.js:141:21)
    at handleMessage (https://prettier.io/worker.js:78:26)
    at self.onmessage (https://prettier.io/worker.js:36:14)
```
