### ISSUE TITLE
[js] crash with parent pointers and a custom parser

### ISSUE THREAD

**Issue by bradzacher** [prettier/prettier#11793]
**Environments:**

- Prettier Version: 2.4.1
- Running Prettier via: Node.JS API
- Runtime: Node 12
- Operating System: Linux
- Prettier plugins (if any): none

**Steps to reproduce:**

```js
import {parseForESLint} from 'hermes-eslint';

declare function traverse(node, (node, parent) => void): void;

const code = 'const x = (): () => () => void => {};';
prettier.format(code, (text) => {
  const ast = parseForESLint(text);
  traverse(ast, (node, parent) => { node.parent = parent });
  return ast;
});
```

**Expected behavior:**

Prettier ignores `parent` property during formatting and formats the code.

**Actual behavior:**

```
    RangeError: Maximum call stack size exceeded
        at Function.values (<anonymous>)

      at hasNode$2 (node_modules/prettier/index.js:37813:56)
      at node_modules/prettier/index.js:37813:83
          at Array.some (<anonymous>)
      at hasNode$2 (node_modules/prettier/index.js:37813:69)
      at node_modules/prettier/index.js:37813:83
          at Array.some (<anonymous>)
      at hasNode$2 (node_modules/prettier/index.js:37813:69)
      at node_modules/prettier/index.js:37813:83
          at Array.some (<anonymous>)
```

It looks like this function just naively iterates over all **values** and ignores the keys.
Thus if the `parent` property is set - it gets itself into an infinite loop, and crashes.

https://github.com/prettier/prettier/blob/65e01b7c034d4349b844316d35da537734a226e2/src/language-js/utils.js#L75-L91

**Comment by fisker** [comment]
Yes, `parent` can't be used, instead of ignore `parent`, we delete them...

https://github.com/prettier/prettier/blob/fd69858bc4c4c944258411f67824f05015d8b103/src/language-css/parser-postcss.js#L166
https://github.com/prettier/prettier/blob/fd69858bc4c4c944258411f67824f05015d8b103/src/language-graphql/parser-graphql.js#L27

**Comment by fisker** [comment]
Ideally, we should  ask the parser to provide a `traverse` function. I tried to make change to this part, but didn't finish.

**Comment by fisker** [comment]
#13255 should already fixed this, we can add a test to close.
