### ISSUE TITLE
</template> in VS code breaks prettier

### ISSUE THREAD

**Issue by jmarshall9120** [prettier/prettier#12388]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6I1AfJVIYagG4C0eWWbARngE71GTZuwwIAroQgAzGQGc4MNgE8hIkejjZ88WqgD0mXATjrNBsZPOH2nbn0ENDx3WYYgANCAhYYAS2h5ZFABfggAdwAFAQRglDwcCLwVYO8efjwwAGslAGU8cQAZfyg4ZBlExXTMnPysLNLSZBh+CThvbR44ABMe3qK8Mgk8UjgAMQh+DAIAsmQQPAkYCC8QAAsYDBwAdXX-eHkGsDg8uIP-FgOVBbB5NJBSxX4YKMzSGYqqjpAAK3kAB55Jo4OAARQkEHgXxw1RADX4zwWfG6ODWWH4pRgO38PRg62QAA4AAzeDEQRQ7TJYBYYuDPFjlbwAR0h8Devnii3kbDKvV6a34cFZ-iFb1GnyQlVhP0UGH8LTaspB4LZ5SQrXa3hgeB4OLxBKQACZtZl-DgmgBhCAYSUgekAVjWEkUABVdfFNT8WO0AJJQfqwPJgTF+ACCAbyMBUoJhigAvvGgA)

```sh
--parser babel
--use-tabs
--single-quote
```

**Input:**

```jsx
<template lang="">
  <v-app-bar>
    <v-menu offset-y>
      <template></template>
    </v-menu>
  </v-app-bar>
</template>

```

**Output:**

```jsx
<template lang="">
	<v-app-bar>
		<v-menu offset-y>
			<template></template>
		</v-menu>
	</v-app-bar>
</template>;

```

**Expected behavior:**
The expected behavior in the playground is correct, however in my environment, it seems to recognize the first </template> tag it finds as the end of the vue template and creates this error:

```
SyntaxError: Unexpected closing tag "v-menu". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (5:5)
  3 |     <v-menu offset-y>
  4 |       <template></template>
> 5 |     </v-menu>
    |     ^^^^^^^^^
  6 |   </v-app-bar>
  7 | </template>
  8 | <script>
	at y (m:\source\bandzintranet\node_modules\prettier\parser-html.js:40:2906)
	at Vl (m:\source\bandzintranet\node_modules\prettier\parser-html.js:111:2567)
	at Xl (m:\source\bandzintranet\node_modules\prettier\parser-html.js:111:4116)
	at Object.parse (m:\source\bandzintranet\node_modules\prettier\parser-html.js:111:4885)
	at Object.parse$d [as parse] (m:\source\bandzintranet\node_modules\prettier\index.js:12975:19)
	at coreFormat (m:\source\bandzintranet\node_modules\prettier\index.js:14525:16)
	at formatWithCursor$1 (m:\source\bandzintranet\node_modules\prettier\index.js:14765:14)
	at m:\source\bandzintranet\node_modules\prettier\index.js:60959:12
	at Object.format (m:\source\bandzintranet\node_modules\prettier\index.js:60979:12)
	at t.default.format (c:\Users\jmarshall\.vscode\extensions\esbenp.prettier-vscode-9.3.0\dist\extension.js:1:13219)
	at async t.PrettierEditProvider.provideEdits (c:\Users\jmarshall\.vscode\extensions\esbenp.prettier-vscode-9.3.0\dist\extension.js:1:10196)
	at async g.provideDocumentFormattingEdits (c:\Users\jmarshall\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:98509)
["INFO" - 11:59:23 AM] Formatting completed in 0.007ms.
```

**Comment by fisker** [comment]
Di you mean to use `vue` parser?

**Comment by fisker** [comment]
I guess we should allow empty `lang`.

**Comment by jmarshall9120** [comment]
Wow, that was a quick find.  Once I filled in the `lang` prettier began working again.

**Comment by fisker** [comment]
I think we can fix from here

https://github.com/prettier/prettier/blob/9b599ccaad8201af9e85f5749e53a9315d3fbdf6/src/language-html/parser-html.js#L424

Would like to work on it?

**Comment by HallvardMM** [comment]
Saw the issue and wanted to contribute. Hope it looks good.

**Comment by jmarshall9120** [comment]
I'm happy to contribute. But my bandwidth won't be open for about a week.  If there's any blocks here I'll try to jump in.
