### ISSUE TITLE
Don't remove space between unary minus and calc() in Sass

### ISSUE THREAD

**Issue by nex3** [prettier/prettier#12613]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMARk9BadMVAGzAAoASAZwEsAvOdAenQCYBKAXxABoQIADjBrQqyUKgBOkiAHcAClIRiUJWagCeYvlkmowAazgwAyqgC2cADI0ocZADMSVODr2HjJgftsBzZDCSAK6uIHDmWHAAJlHRVqhQvkGovnAAYhCS5qgwwonIaEEwELwgABYw5sQA6mU08FTeYHAmyvU0AG71GgVgVNogti6SMPJ6vtmOzqEAVlQAHiZ+xHAAikEQ8FPELnzeksMFVH0DApK2MNU0UTBlyAAcAAx7Mi7VegIFZ3DDHfZ8AEcNvAxoIVGgqHg7NFoqVJHAgTR4WMUpMkE4dqEXOYaAFgljlmtgfZ0dM+DBUFgrjc7khWOS9DRiH4AMIQcxosJUACspSCLgAKpSVBjdiAOiEAJJQWKwExgc5CACCMpMMA0K22Lk4nCAA)

```sh
--parser scss
```

**Input:**

```scss
a {b: - calc($size / 2)}
```

**Output:**

```scss
a {
  b: -calc($size / 2);
}

```

**Expected behavior:**

Removing the space between `-` and `calc()` changes the behavior (since `-calc` is a valid CSS identifier, Sass parses it as an unknown function rather than a negation of the value of the `calc()` expression).

**Comment by stuprog** [comment]
Hello, 

I wanted to know Which version of scss did you use ?

**Comment by fisker** [comment]
@stuprog she designed sass.

**Comment by stuprog** [comment]
Okay ,thank you

**Comment by stuprog** [comment]
I tested it  with  postcss-scss 2.1.1 and I found this result .

### SCSS

```a {b: - calc($size / 2)}
}
```

### JavaScript

```
const scssParser = require("postcss-scss");

const result = scssParser.parse(`
a {b: - calc($size / 2)}
}

`);
console.log(result);

```

### Errors 

```
$ node index.js
C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\node_modules\postcss\lib\parser.js:565
    throw this.input.error('Unexpected }', token[2], token[3]);
    ^

CssSyntaxError: <css input>:3:1: Unexpected }
    at Input.error (C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\node_modules\←[4mpostcss←[24m\lib\input.js:128:16)
    at ScssParser.unexpectedClose (C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\node_modules\←[4mpostcss←[24m\lib\parser.js:565:22)
    at ScssParser.end (C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\node_modules\←[4mpostcss←[24m\lib\parser.js:386:12)
    at ScssParser.parse (C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\node_modules\←[4mpostcss←[24m\lib\parser.js:59:16)
    at Object.scssParse [as parse] (C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\node_modules\←[4mpostcss-scss←[24m\lib\scss-parse.js:10:10)
    at Object.<anonymous> (C:\Users\PC\OneDrive - South Mediterranean University\Desktop\test\index.js:3:27)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)←[39m {
  reason: ←[32m'Unexpected }'←[39m,
  source: ←[32m'\na {b: - calc($size / 2)}\n}\n\n'←[39m,
  line: ←[33m3←[39m,
  column: ←[33m1←[39m,
  input: { line: ←[33m3←[39m, column: ←[33m1←[39m, source: ←[32m'\na {b: - calc($size / 2)}\n}\n\n'←[39m }
}
```

**Comment by nex3** [comment]
You're seeing a parsing bug there because you have an extra `}`.

**Comment by sosukesuzuki** [comment]
@nex3  Thanks for this issue! I'm working on this. Do we need to consider other unary operators? Is minus(`-`) enough?

**Comment by nex3** [comment]
> @nex3 Thanks for this issue! I'm working on this. Do we need to consider other unary operators? Is to support only minus(`-` enough?

Only `-` matters, because only `-` is valid as part of a CSS identifier.

**Comment by alexander-akait** [comment]
`-calc` is valid ident too :smile: so I think a valid solution is checking original code and look at space between `-` and `ident`
