### ISSUE TITLE
Fatal error when trying to format file

### ISSUE THREAD

**Issue by oliversalzburg** [prettier/prettier#12753]
**Environments:**

- Prettier Version: 2.6.2
- Running Prettier via: CLI
- Runtime: Node 16.14.0
- Operating System: Windows WSL
- Prettier plugins (if any): prettier-plugin-organize-imports, prettier-plugin-sh

**Steps to reproduce:**

Repro repository: https://github.com/oliversalzburg/prettier-repro

```
node node_modules/.bin/prettier --write subject.json
```

**Expected behavior:**

The file is formatted. Should be a noop, as it's already formatted to comply.

**Actual behavior:**

```shell
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb309a0 node::Abort() [node]
 2: 0xa4219e node::FatalError(char const*, char const*) [node]
 3: 0xd235da v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb352ed node::fs::FileHandle::CloseReq::Resolve() [node]
 5: 0xb35470  [node]
 6: 0x159f86d  [node]
 7: 0x15a4046  [node]
 8: 0x15b6774  [node]
 9: 0x15a4998 uv_run [node]
10: 0xa67dd5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbfcfca node::worker::Worker::Run() [node]
12: 0xbfd478  [node]
13: 0x7f01bfd29609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f01bfc50293 clone [/lib/x86_64-linux-gnu/libc.so.6]
[1]    990 abort      node node_modules/.bin/prettier --write subject.json
```

I have observed this yesterday already with another file and was not able to make sense of it.

**Comment by oliversalzburg** [comment]
After upgrading Node from 16.14.0 to 17.9.0, this issue went away. I feel like I also ran into this issue yesterday after having upgraded Node. I will keep an eye on it.

**Comment by oliversalzburg** [comment]
Seeing this again on 17.9.0 with other files now. I'm not sure if the file contents are even relevant here, so I spare us the noise.

```shell
╰─ yarn prettier --write /home/oliver/projects/monolit/.yarnrc.yml                                
.yarnrc.yml 42ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb309a0 node::Abort() [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
 2: 0xa4219e node::FatalError(char const*, char const*) [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
 3: 0xd235da v8::Utils::ReportApiFailure(char const*, char const*) [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
 4: 0xb352ed node::fs::FileHandle::CloseReq::Resolve() [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
 5: 0xb35470  [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
 6: 0x159f86d  [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
 7: 0x15a4046  [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
 8: 0x15b6774  [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
 9: 0x15a4998 uv_run [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
10: 0xa67dd5 node::SpinEventLoop(node::Environment*) [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
11: 0xbfcfca node::worker::Worker::Run() [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
12: 0xbfd478  [/home/oliver/.nvm/versions/node/v17.9.0/bin/node]
13: 0x7f9908ebd609  [/lib/x86_64-linux-gnu/libpthread.so.0]
```

**Comment by oliversalzburg** [comment]
Just to add a bit more sample data, I was just trying to reproduce this. On the first pass, everything was fine, second and further runs failed with the same stack trace.

```shell
╭─ ~/projects/cbc-kitten-scientists  master ────────────────────────────────────────────────────────── ✔  20:34:54
╰─ yarn prettier --write packages/userscript/package.json
packages/userscript/package.json 25ms

╭─ ~/projects/cbc-kitten-scientists  master ────────────────────────────────────────────────────────── ✔  10:38:12
╰─ node -v
v18.0.0

╭─ ~/projects/cbc-kitten-scientists  master ────────────────────────────────────────────────────────── ✔  10:38:18
╰─ yarn prettier --write packages/userscript/package.json
packages/userscript/package.json 24ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb57b90 node::Abort() [/usr/local/bin/node]
 2: 0xa701b3 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xd4388a v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: 0xb5bfed node::fs::FileHandle::CloseReq::Resolve() [/usr/local/bin/node]
 5: 0xb5c170  [/usr/local/bin/node]
 6: 0x1634dbd  [/usr/local/bin/node]
 7: 0x1639596  [/usr/local/bin/node]
 8: 0x164bcd4  [/usr/local/bin/node]
 9: 0x1639ee8 uv_run [/usr/local/bin/node]
10: 0xa95e45 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
11: 0xc22472 node::worker::Worker::Run() [/usr/local/bin/node]
12: 0xc22a58  [/usr/local/bin/node]
13: 0x7f16e4f8f609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f16e4eb6293 clone [/lib/x86_64-linux-gnu/libc.so.6]

╭─ ~/projects/cbc-kitten-scientists  master ──────────────────────────────────────────────────────── 1 ✘  10:38:21
╰─ yarn prettier --write packages/userscript/package.json
packages/userscript/package.json 24ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb57b90 node::Abort() [/usr/local/bin/node]
 2: 0xa701b3 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xd4388a v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: 0xb5bfed node::fs::FileHandle::CloseReq::Resolve() [/usr/local/bin/node]
 5: 0xb5c170  [/usr/local/bin/node]
 6: 0x1634dbd  [/usr/local/bin/node]
 7: 0x1639596  [/usr/local/bin/node]
 8: 0x164bcd4  [/usr/local/bin/node]
 9: 0x1639ee8 uv_run [/usr/local/bin/node]
10: 0xa95e45 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
11: 0xc22472 node::worker::Worker::Run() [/usr/local/bin/node]
12: 0xc22a58  [/usr/local/bin/node]
13: 0x7ffb2e363609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7ffb2e28a293 clone [/lib/x86_64-linux-gnu/libc.so.6]
```
I don't understand why it worked the first time and I have not been able to recover from this situation manually. At some point it just starts working again.

**Comment by fisker** [comment]
Any  plugin installed?

**Comment by fisker** [comment]
Sorry, missed this https://github.com/oliversalzburg/cbc-kitten-scientists/blob/59244905c6d7ae5280b9e92bcfe4b36e7041ccbe/package.json#L38, maybe caused by https://github.com/keithamus/sort-package-json/issues/258?

**Comment by oliversalzburg** [comment]
[`prettier-package-json`](https://github.com/cameronhunter/prettier-package-json) should actually operate outside of prettier (it just borrows the name). I don't think it uses `sort-package-json` internally.

However, the issue you linked to makes me think. I've been seeing a lot of these ESM warnings myself and am wondering if that is relevant here.

**Comment by oliversalzburg** [comment]
So, here's more info.

First of all, I executed Prettier without going through `yarn`, same issue:
```shell
╰─ node ./node_modules/.bin/prettier --write packages/userscript/package.json
packages/userscript/package.json 24ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb309a0 node::Abort() [node]
 2: 0xa4219e node::FatalError(char const*, char const*) [node]
 3: 0xd235da v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb352ed node::fs::FileHandle::CloseReq::Resolve() [node]
 5: 0xb35470  [node]
 6: 0x159f86d  [node]
 7: 0x15a4046  [node]
 8: 0x15b6774  [node]
 9: 0x15a4998 uv_run [node]
10: 0xa67dd5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbfcfca node::worker::Worker::Run() [node]
12: 0xbfd478  [node]
13: 0x7f770c2f7609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f770c21e293 clone [/lib/x86_64-linux-gnu/libc.so.6]
[1]    3801 abort      node ./node_modules/.bin/prettier --write packages/userscript/package.json
```

Then I removed `prettier-plugin-sh` from my config and ran again:

```shell
╰─ node ./node_modules/.bin/prettier --write packages/userscript/package.json
packages/userscript/package.json 29ms
```

No problem. So run again.

```shell
╰─ node ./node_modules/.bin/prettier --write packages/userscript/package.json
packages/userscript/package.json 25ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb309a0 node::Abort() [node]
 2: 0xa4219e node::FatalError(char const*, char const*) [node]
 3: 0xd235da v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb352ed node::fs::FileHandle::CloseReq::Resolve() [node]
 5: 0xb35470  [node]
 6: 0x159f86d  [node]
 7: 0x15a4046  [node]
 8: 0x15b6774  [node]
 9: 0x15a4998 uv_run [node]
10: 0xa67dd5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbfcfca node::worker::Worker::Run() [node]
12: 0xbfd478  [node]
13: 0x7f4aa9f87609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f4aa9eae293 clone [/lib/x86_64-linux-gnu/libc.so.6]
[1]    4406 abort      node ./node_modules/.bin/prettier --write packages/userscript/package.json
```

I've had this a couple of times that _some change_ would resolve the problem for a single run and then it's back to failure. Sounds like some caching to me, but I don't know what this could be.

**Comment by oliversalzburg** [comment]
I'm also seeing this on another workstation. Admittedly, both workstations are similar.

```shell
╭─ ~/projects/monolit  master ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  14:31:31 
╰─ node node_modules/.bin/prettier tsconfig.json --write
tsconfig.json 29ms

╭─ ~/projects/monolit  master !1 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  14:31:35 
╰─ node node_modules/.bin/prettier tsconfig.json --write
tsconfig.json 67ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb09c10 node::Abort() [node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [node]
 3: 0xcf8afa v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb0da7d node::fs::FileHandle::CloseReq::Resolve() [node]
 5: 0xb0dbd9  [node]
 6: 0x156015d  [node]
 7: 0x1564936  [node]
 8: 0x1577064  [node]
 9: 0x1565288 uv_run [node]
10: 0xa43dd5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbd3792 node::worker::Worker::Run() [node]
12: 0xbd3f28  [node]
13: 0x7fa35a002609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7fa359f27163 clone [/lib/x86_64-linux-gnu/libc.so.6]
[1]    19726 abort      node node_modules/.bin/prettier tsconfig.json --write

╭─ ~/projects/monolit  master !1 ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ABRT ✘  14:31:39 
╰─ node -v                                              
v16.15.0
```

When I try to run `node` with `--inspect-brk`, I can cleanly run through the program without any noticeable issues and there will be no stack trace after the run.

I also wanted to investigate if this could be related to my shell (ZSH). When I run prettier in bash, I see the same pattern:

```shell
oliver@oliver-work:~/projects/monolit$ node node_modules/.bin/prettier tsconfig.json --write
tsconfig.json 29ms
oliver@oliver-work:~/projects/monolit$ node node_modules/.bin/prettier tsconfig.json --write
tsconfig.json 53ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb09c10 node::Abort() [node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [node]
 3: 0xcf8afa v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb0da7d node::fs::FileHandle::CloseReq::Resolve() [node]
 5: 0xb0dbd9  [node]
 6: 0x156015d  [node]
 7: 0x1564936  [node]
 8: 0x1577064  [node]
 9: 0x1565288 uv_run [node]
10: 0xa43dd5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbd3792 node::worker::Worker::Run() [node]
12: 0xbd3f28  [node]
13: 0x7f7f931bf609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f7f930e4163 clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted
```

Not all consecutive runs after the first failure fail. If I run the same command line many times, sometimes it passes without error.

**Comment by oliversalzburg** [comment]
When I run prettier from source (b188c905cfaeb238a122b4a95c230da83f2f3226), I can not reproduce this error:

```shell
╭─ ~/projects/monolit  master !1 ─────────────────────────────────────────────────────────────────────────── ✔  15:22:42 
╰─ node ~/projects/prettier/bin/prettier.js tsconfig.json --write
tsconfig.json 39ms

╭─ ~/projects/monolit  master !1 ─────────────────────────────────────────────────────────────────────────── ✔  15:23:21 
╰─ node ~/projects/prettier/bin/prettier.js tsconfig.json --write
tsconfig.json 56ms

╭─ ~/projects/monolit  master !1 ─────────────────────────────────────────────────────────────────────────── ✔  15:23:23 
╰─ node ~/projects/prettier/bin/prettier.js tsconfig.json --write
tsconfig.json 62ms

╭─ ~/projects/monolit  master !1 ─────────────────────────────────────────────────────────────────────────── ✔  15:23:24 
╰─ node ~/projects/prettier/bin/prettier.js tsconfig.json --write
tsconfig.json 55ms
```

**Comment by oliversalzburg** [comment]
I'm going to assume we're dealing with https://github.com/nodejs/node/issues/42829

**Comment by oliversalzburg** [comment]
I'm not sure what I did when I reported that I can reproduce the issue without plugins. I feel like I must have made a mistake at the time. After further troubleshooting, I am fairly certain that this issue only reproduces when `prettier-plugin-sh` is in use.

**Comment by fisker** [comment]
The only place we use `fs.open` https://github.com/prettier/prettier/blob/b188c905cfaeb238a122b4a95c230da83f2f3226/src/utils/get-interpreter.js#L14, try to comment it out to see if the error still there.

**Comment by oliversalzburg** [comment]
Right now, I feel like it was v0.9.0 of prettier-plugin-sh that introduced this defect. I have run 150 passes with v0.8.0 with no issue and with 0.9.0, it fails after few iterations.

The NodeJS issue linked above seems to relate to some WASM feature and I noticed https://github.com/rx-ts/prettier/pull/154 for v0.9.0 of the plugin. Maybe this is related?

**Comment by oliversalzburg** [comment]
My statements regarding having the plugins loaded are probably misleading. I realized that `prettier-plugin-sh` is loaded regardless of my `plugins` setting in my Prettier config. From what I can tell so far, `load-plugins.js` checks `node_modules` and loaded these plugins. 

As this stack trace (from a manually inserted error) illustrates, `prettier-plugin-sh` is loaded, even though the debug log afterwards shows no plugins are configured. So this gave me some misleading results.

```shell
╰─ node ../monolit/node_modules/.bin/prettier --write ../monolit/tsconfig.json --loglevel debug
Error: you shouldn't be here 1
    at Object.<anonymous> (/home/oliver/projects/monolit/node_modules/prettier-plugin-sh/lib/index.cjs:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/oliver/projects/monolit/node_modules/prettier/index.js:39134:10
    at Array.map (<anonymous>)
    at Object.load (/home/oliver/projects/monolit/node_modules/prettier/index.js:39132:125)
[debug] normalized argv: {"_":["../monolit/tsconfig.json"],"color":true,"editorconfig":true,"write":true,"loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"__raw":{"_":["../monolit/tsconfig.json"],"color":true,"editorconfig":true,"write":true,"loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}
[debug] resolve config from '../monolit/tsconfig.json'
[debug] loaded options `{"useTabs":false,"tabWidth":2,"printWidth":100,"arrowParens":"avoid","plugins":[]}`
[debug] applied config-precedence (cli-override): {"arrowParens":"avoid","plugins":[],"printWidth":100,"tabWidth":2,"useTabs":false}
../monolit/tsconfig.json 44ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb309a0 node::Abort() [node]
 2: 0xa4219e node::FatalError(char const*, char const*) [node]
 3: 0xd235da v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xb352ed node::fs::FileHandle::CloseReq::Resolve() [node]
 5: 0xb35470  [node]
 6: 0x159f86d  [node]
 7: 0x15a4046  [node]
 8: 0x15b6774  [node]
 9: 0x15a4998 uv_run [node]
10: 0xa67dd5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbfcfca node::worker::Worker::Run() [node]
12: 0xbfd478  [node]
13: 0x7f7922e0b609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f7922d32293 clone [/lib/x86_64-linux-gnu/libc.so.6]
[1]    20191 abort      node ../monolit/node_modules/.bin/prettier --write ../monolit/tsconfig.json  
```

**Comment by oliversalzburg** [comment]
In light of the latest discoveries, I have created this new repository to repro the issue: https://github.com/oliversalzburg/prettier-repro.

This fails pretty reliably for me. I am currently assuming the defect is due to a race condition when formatting is so fast that prettier-plugin-sh has issues to bring up or tear down the worker cleanly.

**Comment by fisker** [comment]
@JounQin

**Comment by JounQin** [comment]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/8336744/166972627-bf697c88-44db-42e4-a2bf-01db80055c9d.png">

<img width="795" alt="image" src="https://user-images.githubusercontent.com/8336744/166972682-93f53063-b374-4306-8d0c-b4b5174b73f1.png">

Interesting... I can't get any log correctly, will dig deeper tomorrow.

**Comment by JounQin** [comment]
I think maybe it is a Node bug?... Really no idea what is happening, the `parser` and `printer` of `prettier-plugin-sh` is not even been called at all...

<img width="736" alt="image" src="https://user-images.githubusercontent.com/8336744/167054971-89c349b3-ff9f-4b17-9139-30a790998f83.png">

**Comment by fisker** [comment]
https://github.com/prettier/prettier/issues/12753#issuecomment-1118573594

**Comment by JounQin** [comment]
I don't know if it is related, `worker.mjs` is always used for `.cjs` entry, I tried to use `worker.cjs`, it seems working as expected. (No idea why...)

@oliversalzburg Can you try `prettier-plugin-sh@https://pkg.csb.dev/rx-ts/prettier/commit/c2923bd2/prettier-plugin-sh/_pkg.tgz`?

**Comment by oliversalzburg** [comment]
@JounQin From a very brief check in the repro repo, that seems to work wonders :) I will try in all my other projects. Awesome!

**Comment by oliversalzburg** [comment]
Everything is working perfectly right now. In case I see some regression, I will report again. Thanks again for your quick help :)

**Comment by oliversalzburg** [comment]
After upgrading my prettier dependencies yesterday, this issue is back.

```shell
╰─ yarn prettier --write packages/plant-nursery/package.json
packages/plant-nursery/package.json 26ms
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xb09c10 node::Abort() [/usr/local/bin/node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xcf8afa v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: 0xb0da7d node::fs::FileHandle::CloseReq::Resolve() [/usr/local/bin/node]
 5: 0xb0dbd9  [/usr/local/bin/node]
 6: 0x156015d  [/usr/local/bin/node]
 7: 0x1564936  [/usr/local/bin/node]
 8: 0x1577064  [/usr/local/bin/node]
 9: 0x1565288 uv_run [/usr/local/bin/node]
10: 0xa43dd5 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
11: 0xbd3792 node::worker::Worker::Run() [/usr/local/bin/node]
12: 0xbd3f28  [/usr/local/bin/node]
13: 0x7ff404b0e609  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7ff404a35293 clone [/lib/x86_64-linux-gnu/libc.so.6]
```

Let me know if you feel this belongs in a new issue.

**Comment by oliversalzburg** [comment]
No, I have not yet tried your latest update. Thanks for pointing that out.

> Besides, do not reopen the issue here, post a new one on https://github.com/rx-ts/prettier next time if you know which prettier plugin is related.

Bro, this is literally a question in my latest post. You don't have to play smart with me wtf?

**Comment by agalatan** [comment]
Hats off
