### ISSUE TITLE
Error Formatting in Typescript 4.7.4

### ISSUE THREAD

**Issue by FabrizioCoder** [prettier/prettier#13207]
## Hello, I have a problem when I try to format a typescript file.

```sh
["ERROR" - 1:20:51] Error formatting document.
["ERROR" - 1:20:51] '=' expected. (11:13)
   9 | import { Command } from '../../interfaces/Command';
  10 | import { SpotifyItemType } from '@lavaclient/spotify';
> 11 | import type { Addable } from '@lavaclient/queue';
     |             ^
  12 | 
  13 | import fetch from 'node-fetch';
  14 | import { formatText } from '../../utils/functions';
SyntaxError: '=' expected. (11:13)
   9 | import { Command } from '../../interfaces/Command';
  10 | import { SpotifyItemType } from '@lavaclient/spotify';
> 11 | import type { Addable } from '@lavaclient/queue';
     |             ^
  12 | 
  13 | import fetch from 'node-fetch';
  14 | import { formatText } from '../../utils/functions';
	at t (/home/fabriziocoder/biscuit/node_modules/prettier/parser-typescript.js:1:285)
	at Object.parse (/home/fabriziocoder/biscuit/node_modules/prettier/parser-typescript.js:14:180461)
	at Object.parse (/home/fabriziocoder/biscuit/node_modules/prettier/index.js:9739:19)
	at coreFormat (/home/fabriziocoder/biscuit/node_modules/prettier/index.js:13252:23)
	at format (/home/fabriziocoder/biscuit/node_modules/prettier/index.js:13510:73)
	at formatWithCursor (/home/fabriziocoder/biscuit/node_modules/prettier/index.js:13526:12)
	at /home/fabriziocoder/biscuit/node_modules/prettier/index.js:44207:15
	at Object.format (/home/fabriziocoder/biscuit/node_modules/prettier/index.js:44226:12)
	at t.default.format (/home/fabriziocoder/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:13427)
	at async t.PrettierEditProvider.provideEdits (/home/fabriziocoder/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:10134)
	at async H.provideDocumentFormattingEdits (/home/fabriziocoder/.vscode-server-insiders/bin/12b08be500f8a307f30e92cbc3ee39ba115eab69/out/vs/workbench/api/node/extensionHostProcess.js:87:45865)
["INFO" - 1:20:51] Formatting completed in 0.106ms.
```

- Prettier extension
![Image](https://media.discordapp.net/attachments/986978011490439198/1003912570362667088/unknown.png)

**Comment by sosukesuzuki** [comment]
Maybe your Prettier's version is old. TypeScript 4.7 is supported by since Prettier 2.7.

**Comment by yuchant** [comment]
I am getting this error suddenly as well on type imports as of today. Nothing has changed in prettier or TS but I started upgrading prettier/downgrading TS / playing with it, and the problem was fixed after a VSCode restart. Therefore I can't tell what the issue was. All I can say is try reinstalling TS/prettier and restarting VSCode.

**Comment by FabrizioCoder** [comment]
> I am getting this error suddenly as well on type imports as of today. Nothing has changed in prettier or TS but I started upgrading prettier/downgrading TS / playing with it, and the problem was fixed after a VSCode restart. Therefore I can't tell what the issue was. All I can say is try reinstalling TS/prettier and restarting VSCode.

I found yours useful, thanks a lot :D

**Comment by yuchant** [comment]
> > I am getting this error suddenly as well on type imports as of today. Nothing has changed in prettier or TS but I started upgrading prettier/downgrading TS / playing with it, and the problem was fixed after a VSCode restart. Therefore I can't tell what the issue was. All I can say is try reinstalling TS/prettier and restarting VSCode.
> 
> I found yours useful, thanks a lot :D

I wonder what happened? Why same time. Interesting.
