### ISSUE TITLE
Angular parser with --write does not fix the issue, adds a line break each time it is run

### ISSUE THREAD

**Issue by jsruok** [prettier/prettier#13226]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UAFMMEkgAQCGNtd99AdAEatvsceNg+9--9G6YSNFixFAL6SAlIVQB6LHkIgANCAgAHGJmgBnZKCoAnExADuABVMJDKKgBsLVAJ6GNzE1TABrODAAylQAtnAAMphQcMgAZk76cJ7efgGBWj5RAObIMCYArkkgcCHMcMLl4VRQWflUWXAAYhAmIVQwujXIIFT5MBDqIAAWMCGOAOpDmPD6GWBwgXbTONOu3WD6HiBRiSYwVt5ZbXEJRQBW+gAegdmOcACK+RDwJ46JGhkmu93VtY6mgy0JiiMHGmHQMCGyAAHAAGD7mRLjbxabpAuC7bAxDQARye8AO2nsPX0AFpouVyoMTHA8ZgaQd6sckPE3kVEiFMLkCuzbg98TEWacNDAqMwwRCoUgAEwi7yYRzZADCEBCzOK+gArIN8okACpi+ys94gbCFACSUHQCCCYGBOgAglbAjBXHdXolpEA)

```sh
--parser angular
```

**Input:**

```html
<div>
({{:: aaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccc.dddddddddddddddddddd }})
</div>
```

**Output:**

```html
SyntaxError: Unexpected token :
    at R (https://prettier.io/lib/parser-angular.js:2:44123)
    at b (https://prettier.io/lib/parser-angular.js:2:43742)
    at a (https://prettier.io/lib/parser-angular.js:2:56386)
    at Object.h [as parseInterpolation] (https://prettier.io/lib/parser-angular.js:2:56621)
    at https://prettier.io/lib/parser-angular.js:2:57295
    at Object.parse (https://prettier.io/lib/parser-angular.js:2:56961)
    at Object.m [as parse] (https://prettier.io/lib/standalone.js:40:1354)
    at u (https://prettier.io/lib/standalone.js:41:10255)
    at https://prettier.io/lib/standalone.js:41:10006
    at Object.b [as embed] (https://prettier.io/lib/standalone.js:110:7631)
```

BUT in our development environment `--write` does change the file. The output becomes

```html
<div>
({{:: aaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccc.dddddddddddddddddddd
}})
</div>
```

This, however, does not fix the issue. When prettier is ran again, the output is

```html
<div>
({{:: aaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccc.dddddddddddddddddddd

}})
</div>
```

So, each time prettier finds an issue and adds a line change at the end of the variable.

The problem seems to be related to the double colon notation of [one time binding](https://docs.angularjs.org/guide/expression#one-time-binding). Without it, the output becomes

```html
({{
  aaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccc
    .dddddddddddddddddddd
}})
```
and stays that way.

**Expected behavior:**
Output:

```html
({{::
  aaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccc
    .dddddddddddddddddddd
}})
```

**Comment by thorn0** [comment]
Can be reproduced on the playground with `--embedded-language-formatting off`:

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UAFMMEkgAQCGNtd99AdAEatvsceNg+9--9G6YSNFixFAL6SAlIVQB6LHkIgANCAgAHGJmgBnZKCoAnExADuABVMJDKKgBsLVAJ6GNzE1TABrODAAylQAtnAAMphQcMgAZk76cJ7efgGBWj5RAObIMCYArkkgcCHMcMLl4VRQWflUWXAAYhAmIVQwujXImrGx6iAAFjAhjgDqA5jw+hlgcIF2kziTrt1g+h4gUYkmMFbeWW1xCUUAVvoAHoHZjnAAivkQ8EeOiRoZJtvd1bWOpv1aJiiMFGmHQMAGyAAHAAGN7mRKjbxaboAuDbbAxDQARwe8D22nsICo+gAtNFyuV+iY4DjMNS9vVDkh4i8iokQphcgU2dc7riYszjhoYFRmCCwRCkAAmYXeTCObIAYQgISZxX0AFZ+vlEgAVUX2FmvEDYQoASSg6AQQTAgJ0AEFLYEYK4bs9EtIgA)

```sh
--parser angular
--embedded-language-formatting off
```

**Input:**

```html
<div>
({{:: aaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccc.dddddddddddddddddddd }})
</div>

```

**Output:**

```html
<div>
  ({{:: aaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccc.dddddddddddddddddddd
  }})
</div>

```

**Second Output:**

```html
<div>
  ({{:: aaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbb.cccccccccccccccccccc.dddddddddddddddddddd

  }})
</div>

```
