### ISSUE TITLE
first graphql example throws error

### ISSUE THREAD

**Issue by xenoterracide** [prettier/prettier#13307]
```graphqls
type Query {
  me: User
}

type User {
  id: ID
  name: String
}
```

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - --allow-empty-message
🔍  Finding changed files since git revision 8f74fde.
🎯  Found 5 changed files.
/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/cache/prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip/node_modules/prettier/index.js:7348
          throw error;
          ^

SyntaxError: Syntax Error: Expected Name, found "}". (5:12)
  3 | }
  4 |
> 5 | type User {}
    |            ^
  6 |
    at i (/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/cache/prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip/node_modules/prettier/parser-graphql.js:1:713)
    at Le (/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/cache/prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip/node_modules/prettier/parser-graphql.js:15:20811)
    at Object.xe [as parse] (/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/cache/prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip/node_modules/prettier/parser-graphql.js:15:21020)
    at Object.parse (/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/cache/prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip/node_modules/prettier/index.js:7334:23)
    at coreFormat (/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/cache/prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip/node_modules/prettier/index.js:8645:18)
    at formatWithCursor2 (/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/cache/prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip/node_modules/prettier/index.js:8837:18)
    at /Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/cache/prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip/node_modules/prettier/index.js:37229:12
    at Object.format (/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/cache/prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip/node_modules/prettier/index.js:37243:12)
    at _default (/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/__virtual__/pretty-quick-virtual-32488acfb5/0/cache/pretty-quick-npm-3.1.3-b3fdb9cf9e-28bdc32571.zip/node_modules/pretty-quick/dist/processFiles.js:42:29)
    at _default (/Users/nqy642/IdeaProjects/iw-pm-backend/.yarn/__virtual__/pretty-quick-virtual-32488acfb5/0/cache/pretty-quick-npm-3.1.3-b3fdb9cf9e-28bdc32571.zip/node_modules/pretty-quick/dist/index.js:60:29) {
  loc: { start: { line: 5, column: 12 } },
  codeFrame: '  3 | }\n  4 |\n> 5 | type User {}\n    |            ^\n  6 |'
}
husky - pre-commit hook exited with code 1 (error)
```

**Environments:**

## System:
 - OS: macOS 11.6.8
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
## Binaries:
 - Node: 16.14.2 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-13a67f97/node
 - Yarn: 3.2.2 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-13a67f97/yarn
 - npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm

```
├─ @prettier/plugin-xml@npm:2.2.0
│  ├─ Version: 2.2.0
│  │
│  └─ Dependencies
│     ├─ @xml-tools/parser@npm:^1.0.11 → npm:1.0.11
│     └─ prettier@npm:>=2.4.0 → npm:2.7.1
│
├─ backend@workspace:.
│  ├─ Version: 0.0.0
│  │
│  └─ Dependencies
│     ├─ @prettier/plugin-xml@npm:^2.2.0 → npm:2.2.0
│     ├─ husky@npm:6 → npm:6.0.0
│     ├─ pinst@npm:^2.0.0 → npm:2.1.6
│     ├─ prettier-plugin-java@npm:^1.6.2 → npm:1.6.2
│     ├─ prettier-plugin-properties@npm:^0.2.0 → npm:0.2.0
│     ├─ prettier@npm:^2.7.1 → npm:2.7.1
│     └─ pretty-quick@npm:^3.1.3 → npm:3.1.3 [f5126]
│
├─ husky@npm:6.0.0
│  ├─ Version: 6.0.0
│  │
│  └─ Exported Binaries
│     └─ husky
│
├─ pinst@npm:2.1.6
│  ├─ Version: 2.1.6
│  │
│  ├─ Exported Binaries
│  │  └─ pinst
│  │
│  └─ Dependencies
│     └─ fromentries@npm:^1.3.2 → npm:1.3.2
│
├─ prettier-plugin-java@npm:1.6.2
│  ├─ Version: 1.6.2
│  │
│  └─ Dependencies
│     ├─ java-parser@npm:2.0.2 → npm:2.0.2
│     ├─ lodash@npm:4.17.21 → npm:4.17.21
│     └─ prettier@npm:2.3.1 → npm:2.3.1
│
├─ prettier-plugin-properties@npm:0.2.0
│  ├─ Version: 0.2.0
│  │
│  └─ Dependencies
│     └─ dot-properties@npm:^1.0.0 → npm:1.0.1
│
├─ prettier@npm:2.7.1
│  ├─ Version: 2.7.1
│  │
│  └─ Exported Binaries
│     └─ prettier
│
└─ pretty-quick@npm:3.1.3
   ├─ Instances: 1
   ├─ Version: 3.1.3
   │
   ├─ Exported Binaries
   │  └─ pretty-quick
   │
   └─ Dependencies
      ├─ chalk@npm:^3.0.0 → npm:3.0.0
      ├─ execa@npm:^4.0.0 → npm:4.1.0
      ├─ find-up@npm:^4.1.0 → npm:4.1.0
      ├─ ignore@npm:^5.1.4 → npm:5.1.8
      ├─ mri@npm:^1.1.5 → npm:1.1.6
      └─ multimatch@npm:^4.0.0 → npm:4.0.0
```

**Steps to reproduce:**
I suspect it's just create graphqls, and try to commit with pretty quick

**Comment by xenoterracide** [comment]
actually from the looks of it, it's a problem with pretty-quick, switched to lintstaged and it went away. super strange
