### ISSUE TITLE
Error syntax on importing types and default exports together

### ISSUE THREAD

**Issue by farhad-gh-dev** [prettier/prettier#13360]
Hi

I'm using typescript in my react application and when I try to import types from a module alongside with my default export, prettier throws a syntax error.
when I remove type form import statement prettier works just fine!

I use prettier v9.8.0

**Input:**

```jsx
import AddToCardButton from "./AddToCardButton/AddToCardButton";
import Rating from "../Rating/Rating";
import Heading from "../Heading/Heading";
import Dropdown, { type DropdownItem } from "../Dropdown/Dropdown";
import Text from "../Text/Text";
```

```
["INFO" - 7:18:01 PM] Using ignore file (if present) at c:\Users\User\Desktop\.prettierignore
["INFO" - 7:18:01 PM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 7:18:01 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 7:18:01 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "c:\\Users\\Farhad\\Desktop\\portfolio\\projects\\game-guide-uikit\\src\\Components\\OfferCard\\OfferCard.tsx",
  "parser": "typescript"
}
["ERROR" - 7:18:01 PM] Error formatting document.
["ERROR" - 7:18:01 PM] ',' expected. (14:25)
  12 | import Rating from "../Rating/Rating";
  13 | import Heading from "../Heading/Heading";
> 14 | import Dropdown, { type DropdownItem } from "../Dropdown/Dropdown";
     |                         ^
  15 | import Text from "../Text/Text";
  16 |
  17 | export type offerItem = {
SyntaxError: ',' expected. (14:25)
  12 | import Rating from "../Rating/Rating";
  13 | import Heading from "../Heading/Heading";
> 14 | import Dropdown, { type DropdownItem } from "../Dropdown/Dropdown";
     |                         ^
  15 | import Text from "../Text/Text";
  16 |
  17 | export type offerItem = {
    at e (c:\Users\User\Desktop\projects\store-app\node_modules\prettier\parser-typescript.js:1:384)
    at c:\Users\User\Desktop\projects\store-app\node_modules\prettier\parser-typescript.js:1:3179433
    at Object.parse (c:\Users\User\Desktop\projects\store-app\node_modules\prettier\parser-typescript.js:1:3179466)
    at Object.parse$a [as parse] (c:\Users\User\Desktop\projects\store-app\node_modules\prettier\index.js:14892:19)
    at coreFormat (c:\Users\User\Desktop\projects\store-app\node_modules\prettier\index.js:16425:16)
    at formatWithCursor$1 (c:\Users\User\Desktop\projects\store-app\node_modules\prettier\index.js:16665:14)
    at c:\Users\User\Desktop\projects\store-app\node_modules\prettier\index.js:60922:12
    at Object.Success [as format] (c:\Users\User\Desktop\projects\store-app\node_modules\prettier\index.js:60942:12)
    at t.default.format (c:\Users\User\.vscode\extensions\esbenp.prettier-vscode-9.8.0\src\PrettierEditService.ts:463:45)
    at t.PrettierEditProvider.provideEdits (c:\Users\User\.vscode\extensions\esbenp.prettier-vscode-9.8.0\src\PrettierEditService.ts:324:22)
    at $.provideDocumentFormattingEdits (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:45865)
["INFO" - 7:18:01 PM] Formatting completed in 15ms.
```

**Expected behavior:**

**Comment by fisker** [comment]
Can't reproduce, and we don't have v9.8.0 https://www.npmjs.com/package/prettier

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgEEATYgFQgGEBDHYgIQFcYZp8AzHCdfAHRAB0AehLkqtBs1ZQRpCjTpMW0fgG5eUDNjz4AStRiooAcw5ce-AcP2GTQm0eNqNW3AQAScasUdnufQWFPb0chYJ8TZ00sN3wAES5MYggAdygAGnxgfBgAT0w4eMTktIBJeB4AXz8LQKEEiCTUmQamtKjXHTI4AA8CTn9LYW6+oRGYNRB0kEbDaABnZFBaLhSABVoERZRqABsU6lzF6YAjHGowAGs4GABlanQ4ABkjOGR2Pfm4U-Orm9vMBdHMgYDhGN8QHB0Cc4KRYU9qCZGNRjHAAGK4dAGWzGZAgajMCBTEAACxg6F2AHUSah4PNAWA4LctrTUAA3Wm5PFgebHNBQL54NbnYxY96fCEAK3mPVujl2cAAiowIPBxbsvtNAThBXi8gV5mAcKhMDBiZhjbBKahiDAScgABwABi1XC+lPOmDxFrggrZb2mAEcVfBhY1tvj5gBaKBwWGw4k4ODB1BJ4UosVID4aiFfdCoEFg3PypUht5ZiXTGDUE7W232pAAJir51Qu0clG4mch8wArMTGF8yDXttnNSA2eDSlBiAg7kaTTBCDPbnkFeqvpVKkA)

```sh
--parser typescript
```

**Input:**

```tsx
import AddToCardButton from "./AddToCardButton/AddToCardButton";
import Rating from "../Rating/Rating";
import Heading from "../Heading/Heading";
import Dropdown, { type DropdownItem } from "../Dropdown/Dropdown";
import Text from "../Text/Text";
```

**Output:**

```tsx
import AddToCardButton from "./AddToCardButton/AddToCardButton";
import Rating from "../Rating/Rating";
import Heading from "../Heading/Heading";
import Dropdown, { type DropdownItem } from "../Dropdown/Dropdown";
import Text from "../Text/Text";

```

**Comment by farhad-gh-dev** [comment]
I'm using vs-code extension Prettier - Code formatter v9.8.0

**Comment by fisker** [comment]
Wrong repo, then.

**Comment by farhad-gh-dev** [comment]
oh, ok! thanks.
