### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by mzoterov** [prettier/prettier#13364]
bot.ts[error] bot.ts: Error: Comment "without-right." was not printed. Please report this error!
[error]     at Object.ensureAllCommentsPrinted (/usr/local/lib/node_modules/prettier/index.js:8109:17)
[error]     at coreFormat (/usr/local/lib/node_modules/prettier/index.js:8655:16)
[error]     at formatWithCursor2 (/usr/local/lib/node_modules/prettier/index.js:8837:18)
[error]     at Object.formatWithCursor (/usr/local/lib/node_modules/prettier/index.js:37229:12)
[error]     at format (/usr/local/lib/node_modules/prettier/cli.js:14748:24)
[error]     at formatFiles2 (/usr/local/lib/node_modules/prettier/cli.js:14860:22)
[error]     at async main (/usr/local/lib/node_modules/prettier/cli.js:15077:5)
[error]     at async Object.run (/usr/local/lib/node_modules/prettier/cli.js:15024:5)

**Comment by mzoterov** [comment]
All right :)
Broked by comment after continue

if(condition) continue; // comment
