### ISSUE TITLE
v2.7.1 Error: Comment "..." was not printed

### ISSUE THREAD

**Issue by baidan4855** [prettier/prettier#13820]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnAFAbhwSmAB0oACUgS1SwEZ9TJYKoBXOUgeg9Lgw1IAWvOCXJwANgGd2AEwiSIAWzgwBzAOZZ8JAL4kQAGhAQADjArRJyUAEM+EAO4AFOwisob4hzYCeVowBGGDZgANYqAMo2ygAyzHDIqJ7SgcFhkSYhGsgwGGxGcIoBcDIyJTE2UOosNupwAGKYijYw5lXIIDYsMBCGIAIwiuIA6mrwkplgcBFuFOYAbnM+HWCS-iDM0hgwTsHqzYnJcEYAVpIAHhEa4nAAiiwQ8IdSxyCZGFsdATbF4n0mGGYMGGFBkqmQAA4AAxGAHyODDYImDoAuBbeYJIwARwe8F2pncnUkAFooHASiU+hg4DiKNTdrUDkgki8jNJFBRnikQJJrndcQlmUcjDAfiCwQJkAAmEXBCjiDQAYSUTJAaIArH0WNIACo-dws7nzNgASSgZVgETAgLMAEFzREYD4bly4DodEA)

```sh
--parser babel
--no-semi
```

**Input:**

```jsx
for(;;){
  if(1) continue // err here
  else dosomething()
}

```

**Output:**

```jsx
Error: Comment "err here" was not printed. Please report this error!
    at Object.b [as ensureAllCommentsPrinted] (https://prettier.io/lib/standalone.js:41:7588)
    at S (https://prettier.io/lib/standalone.js:41:15206)
    at D (https://prettier.io/lib/standalone.js:45:576)
    at Object.formatWithCursor (https://prettier.io/lib/standalone.js:116:7304)
    at formatCode (https://prettier.io/worker.js:173:21)
    at handleFormatMessage (https://prettier.io/worker.js:104:24)
    at handleMessage (https://prettier.io/worker.js:77:14)
    at self.onmessage (https://prettier.io/worker.js:53:14)
```

When "continue" is not in the last branch of "if else", the issue above occurs

**Comment by kachkaev** [comment]
Thanks for reporting @baidan4855! Let’s track this bug in https://github.com/prettier/prettier/issues/7126.
