### ISSUE TITLE
`meriyah` throws unexpected error when printing class member `static`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#13921]
**Prettier 2.8.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOmM6MAlmANxkC+IANCBAA53SbKh0AJyEQA7gAVhCfinSox6AJ78OAIyHowAazgwAyugC2cADK0ocZADN5mOOs069+rlosBzZDCEBXByBwRmpwACahYaboUB6+6B5wBEJGNHQxyCDovjAQ7CAAFjBGqADq+bTwmG5gcPoyFbQAbhVKGWDYeRb2QjASmh4pNnYBAFaYAB76nqhwAIq+EPBDqPYcbkLdGSZCtEro+XlcO7AltKEwB0gAHAAMa6L2JZpcGUdw3Y1WHACOC-B93FkmUwAFpLGEwnkhHBfrRoX14oMkLYVgF7EZaN4-GjpnAAIIwHy0NTZOASOBCcyWZarECYXHzRZWZHDDjUNSnc6XABMbM0tFQngAwhAjEjApgAKx5Xz2AAq6DUshRtMa-gAklAIrB9GAdjw8Vr9DAlDMaXBmMwgA)

```sh
--parser meriyah
```

**Input:**

```jsx
class Foo {
  static;
}
```

**Output:**

```jsx
TypeError: Cannot read properties of null (reading 'type')
    at g (https://prettier.io/lib/standalone.js:66:9271)
    at _ (https://prettier.io/lib/standalone.js:66:18773)
    at te (https://prettier.io/lib/standalone.js:68:10664)
    at Object.G [as print] (https://prettier.io/lib/standalone.js:68:2593)
    at y (https://prettier.io/lib/standalone.js:41:11574)
    at A (https://prettier.io/lib/standalone.js:41:11097)
    at F (https://prettier.io/lib/standalone.js:41:10928)
    at https://prettier.io/lib/standalone.js:66:35066
    at r.each (https://prettier.io/lib/standalone.js:41:8924)
    at g (https://prettier.io/lib/standalone.js:66:34990)
```

**Expected behavior:**

No error.

**Comment by fisker** [comment]
https://github.com/meriyah/meriyah/issues/231

**Comment by sosukesuzuki** [comment]
This is already fixed in `next`.
