### ISSUE TITLE
Can not build my vite project which use "prettier/parser-typeScript" in CentOS

### ISSUE THREAD

**Issue by zhangzheng7856** [prettier/prettier#14202]
#### today, i have try to build in CentOS, and get this Error:
````
Error: [vite]: Rollup failed to resolve import "prettier/parser-typeScript" from "src/components/formDesigner/component/Monaco.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/root/.jenkins/workspace/layui-vue-form-designer/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:41772:19)
    at onwarn (/root/.jenkins/workspace/layui-vue-form-designer/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:41588:13)
    at Object.onwarn (/root/.jenkins/workspace/layui-vue-form-designer/node_modules/rollup/dist/shared/rollup.js:23226:13)
    at ModuleLoader.handleResolveId (/root/.jenkins/workspace/layui-vue-form-designer/node_modules/rollup/dist/shared/rollup.js:22510:26)
    at /root/.jenkins/workspace/layui-vue-form-designer/node_modules/rollup/dist/shared/rollup.js:22471:26[39m
Build step 'Execute shell' marked build as failure
SSH: Current build result is [FAILURE], not going to run.
````
#### how can I resolve this problem？ tks, my bro

**Comment by zhangzheng7856** [comment]
i have find the way to resolve this error

Because it is case-sensitive in centos，so it should be like "prettier/parser-typescript" not yet "prettier/parser-typeScript"

**Comment by cbkhwx** [comment]
> i have find the way to resolve this error
> 
> Because it is case-sensitive in centos，so it should be like "prettier/parser-typescript" not yet "prettier/parser-typeScript"

我正在用您的表单设计器，也发现了这个问题，根据您的提示就解决问题了，谢谢，话说，什么时候更新表单设计器！？期待哦
