### ISSUE TITLE
A dynamic import callback was not specified

### ISSUE THREAD

**Issue by jmatsushita** [prettier/prettier#14917]
Getting this error when using prettier from the `prettier-vscode` extension. The error is also reported here https://github.com/prettier/prettier-vscode/issues/3007 but seems to originate from `prettier`:
```
["ERROR" - 13:22:40] Error handling text editor change
["ERROR" - 13:22:40] A dynamic import callback was not specified.
TypeError: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:387:5)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
    at Object.<anonymous> (/path/to/project/root/node_modules/prettier/index.cjs:600:23)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.b._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:29948)
    at Function.h._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:26698)
    at Function.I._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:24489)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at Module.require (/path/home/.vscode/extensions/github.copilot-1.88.132/dist/extension.js:8:366722)
    at t.ModuleResolver.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at t.ModuleResolver.loadNodeModule (/path/home/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:6406)
    at t.ModuleResolver.getPrettierInstance (/path/home/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:4086)
    at t.default.handleActiveTextEditorChanged (/path/home/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:9843)
    at t.default.handleActiveTextEditorChangedSync (/path/home/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:9445)
    at t.default.registerDisposables (/path/home/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:12288)
    at /path/home/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:77862
```

Using `prettier@3.0.0-alpha.12` and prettier-vscode at `9.13.0`

**Comment by jmatsushita** [comment]
Strangely, I did find a bizarre workaround. When I patch the `prettier/index.cjs` file to `await import("./index.mjs");` I get an error on module load
```
/Users/jun/dev/workshop/iios/node_modules/prettier/index.cjs:600
var prettierPromise = await import("./index.mjs");
                      ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
```

But somehow the extension recovers and after that formatting works (though the vscode extension logs show the error each time). Not a recommended workaround, but maybe it will help identify the underlying issue?

**Comment by kachkaev** [comment]
👋 @jmatsushita!

Prettier v3 alpha does not work in VS Code (yet) – see https://github.com/prettier/prettier-vscode/pull/2947#issuecomment-1519060819 and below for details.

Let’s close this issue because this repo is related to Prettier core, not its integration. I am also waiting for VS Code support for the upcoming v3 🤞

**Comment by jmatsushita** [comment]
Great thanks 🙏
