### ISSUE TITLE
Prettier has an error when format with new version 19.15.0

### ISSUE THREAD

**Issue by acn-zhidong-sun** [prettier/prettier#14959]
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```

**Expected behavior:**

**Comment by JPetitpierre** [comment]
`["ERROR" - 3:28:52 PM] parse(n,r,i={}){let s=e.parse(n,r,i),a="__default__",l={},o=Yx.default,d=Kx.createContext,f=Hx.generateRules,h,...<omitted>...s} could not be cloned.
DataCloneError: parse(n,r,i={}){let s=e.parse(n,r,i),a="__default__",l={},o=Yx.default,d=Kx.createContext,f=Hx.generateRules,h,...<omitted>...s} could not be cloned.
    at new DOMException (node:internal/per_context/domexception:72:5)
    at Worker.postMessage (node:internal/worker:342:5)
    at t.PrettierWorkerInstance.callMethod (/home/jpetitpierre/.vscode-server/extensions/esbenp.prettier-vscode-9.15.0/dist/extension.js:1:17398)
    at t.PrettierWorkerInstance.format (/home/jpetitpierre/.vscode-server/extensions/esbenp.prettier-vscode-9.15.0/dist/extension.js:1:17016)
    at t.default.format (/home/jpetitpierre/.vscode-server/extensions/esbenp.prettier-vscode-9.15.0/dist/extension.js:1:14746)
    at t.PrettierEditProvider.provideEdits (/home/jpetitpierre/.vscode-server/extensions/esbenp.prettier-vscode-9.15.0/dist/extension.js:1:11368)
    at U.provideDocumentFormattingEdits (/home/jpetitpierre/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:102:45790)
["INFO" - 3:28:52 PM] Formatting completed in 38ms.`
