### ISSUE TITLE
[error] Cannot read properties of undefined (reading 'parsers')

### ISSUE THREAD

**Issue by cope** [prettier/prettier#15020]
Why is there no Bug type???

**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: pnpm
- Runtime: Node.js v20.0.0
- Operating System: Windows
- Prettier plugins (if any): prettier-plugin-tailwindcss, tslint-config-prettier

**Steps to reproduce:**
prettier --write "src/**/*.js"

**Expected behavior:**
Prettier does not throw an error. 2.8.8 works fine!

**Actual behavior:**
prettier --write "src/**/*.js"

[error] Cannot read properties of undefined (reading 'parsers')
ELIFECYCLE  Command failed with exit code 1.

**Comment by xg4** [comment]
Looks like an error caused by the plugin.

```log
["INFO" - 7:37:57 AM] Extension Name: esbenp.prettier-vscode.
["INFO" - 7:37:57 AM] Extension Version: 9.19.0.
["ERROR" - 7:37:59 AM] Error resolving prettier configuration for /project/github/code
["ERROR" - 7:37:59 AM] Cannot read properties of undefined (reading 'parsers')
TypeError: Cannot read properties of undefined (reading 'parsers')
    at Jz (/project/github/code/node_modules/.pnpm/prettier-plugin-tailwindcss@0.3.0_prettier@3.0.0/node_modules/prettier-plugin-tailwindcss/dist/index.js:2368:52914)
    at Object.<anonymous> (/project/github/code/node_modules/.pnpm/prettier-plugin-tailwindcss@0.3.0_prettier@3.0.0/node_modules/prettier-plugin-tailwindcss/dist/index.js:2368:43390)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/project/github/code/prettier.config.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
```

**Comment by xg4** [comment]
Prettier v3.0 has some API changes.
It is recommended to use v2.8 for now and wait for the update of the plugin.

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/176#issuecomment-1621926950

**Comment by iursevla** [comment]
This still happens to me. 

> <PATH>/node_modules/src/postgres-js/driver.ts:27
                client.options.parsers[type as any] = transparentParser;
                               ^
> TypeError: Cannot read properties of undefined (reading 'parsers')
    at drizzle(<PATH>r/node_modules/src/postgres-js/driver.ts:27:18)
    at testRunMigrations (<PATH>/migrations/run_migrations.ts:22:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by fisker** [comment]
Closing since it's not a bug in core.
