### ISSUE TITLE
Prettier 3 fails in WebStorm

### ISSUE THREAD

**Issue by mgscreativa** [prettier/prettier#15091]
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: WebStorm IDE
- Runtime: 
- Operating System: Linux
- Prettier plugins (if any): 

**Steps to reproduce:**
Install prettier
Run it with ctrl+alt+shift + p

**Expected behavior:**
Code mormalized

**Actual behavior:**

Got error

```
.../node_modules/prettier/index.cjs:481
  const comments = node.comments ?? (node.comments = []);
                                  ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
  at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireInContext (/home/martinb/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/231.9161.29/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:156:12)
    at PrettierPlugin.requirePrettierApi (/home/martinb/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/231.9161.29/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:129:24)
    at PrettierPlugin.<anonymous> (/home/martinb/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/231.9161.29/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:81:44)
Process finished with exit code -1
```

**Comment by dannypk** [comment]
Same for me, when formatting the code / saving, doesn't follow the eslint rules anymore. Moreover, I even got this error
<img width="1272" alt="Screenshot 2023-07-17 at 13 27 36" src="https://github.com/prettier/prettier/assets/4052691/e440c304-1399-4af2-8fca-ba555c35f13b">

**Comment by dannypk** [comment]
reverting for now

**Comment by mgscreativa** [comment]
@vago Confirmed! changing **Language & Frameworks->Node.js->Node interpreter** to node v16 works with prettier 3
