### ISSUE TITLE
Cannot read properties of undefined (reading 'languages') at standalone.mjs:22:1

### ISSUE THREAD

**Issue by makeiteasierapps** [prettier/prettier#15159]
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: React API/Browser via prettier/standalone
- Runtime: Node v18.16.0
- Operating System: macOs
- Prettier plugins (if any): parser-babel

**Steps to reproduce:**

```
import prettier from 'prettier/standalone';
import parserBabel from 'prettier/parser-babel';

const formatCode = async (message) => {
    const regex = /```(\S*)\s([\s\S]*?)```/g;
    let match;
    let formattedStr = message.message_content;

    while ((match = regex.exec(message.message_content)) !== null) {
        const lang = match[1];
        const code = match[2].trim();
        console.log(code);
        const formattedCode = await prettier.format(code, {parser: "babel", plugins: [parserBabel]});
        console.log(formattedCode);
        formattedStr = formattedStr.replace(
            match[0],
            '```' + lang + '\n' + formattedCode + '```'
        );
    }
    message.message_content = formattedStr;
    return message;
};
```
**Expected behavior:**
Expecting formatted text
**Actual behavior:**
I am getting this error: Cannot read properties of undefined (reading 'languages') at standalone.mjs:22:1

**Comment by makeiteasierapps** [comment]
I resolved the error by changing my import statement, adding another import for estree and adding estree to my plugins.
```
import prettier from 'prettier/standalone';
import parserBabel from 'prettier/plugins/babel';
import estreeParser from 'prettier/plugins/estree';
```
```
const formatCode = async (message) => {
    const regex = /```(\S*)\s([\s\S]*?)```/g;
    let match;
    let formattedStr = message.message_content;

    while ((match = regex.exec(message.message_content)) !== null) {
        const lang = match[1];
        const code = match[2].trim();
        const formattedCode = await prettier.format(code, {parser: "babel", plugins: [parserBabel, estreeParser]});
        console.log(formattedCode);
        formattedStr = formattedStr.replace(
            match[0],
            '```' + lang + '\n' + formattedCode + '```'
        );
    }
    message.message_content = formattedStr;
    return message;
};

```

**Comment by kachkaev** [comment]
@makeiteasierapps given that you have found the solution, shall we close this issue?

**Comment by makeiteasierapps** [comment]
Yes, thank you.
