### ISSUE TITLE
Comment in `IfStatement` not printed.

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#15168]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgBQCU+wAOlPvjqvsYeQG6EBO+Y+AvPgIz4A9ACouEALYSEMfADZC+EUIDc1WnAA2AZzj52cGOnY0ATGqgBfEABoQEAA65o25KA7sIAdwAKHBK4ohJpehACernYARuyEYADWhgDKhNIAMjhQcMiowbrRsQnJDnGZAObIMOzocHa6EjiV1bUg2uWacACK6BDwOXktAFbaAB5J7V09fUi5Oi0AjlNwPp4OgSCE2gC0WXAAJvu2IFWEOJrlAMKSEoTIG5qaR21QZR0AgjBVOFHo8D5w7AyWX6czsAAsYBJNAB1ME4eDaEpgOBJALwnAseFhO5gbSREAsGoASSgB1gSTA7BwTjepKSMDCHRB+RADk8umhsQcdzZcF07BY2TsmX5MBWhDKN2ZLRK7H5dyihCiWiObMyMGhOD2MDByAAHAAGOwGRY4AziyW3GYDOwwJWa7W6pCmOzoXQAFSVgVmLLgEmVewOezShBe6AlcAAYhB2DdPuU7oRfhAQJZLEA)

```sh
--parser babel
```

**Input:**

```jsx
function a() {
  if (a) var c = 1 /* comment 6a */;
  else return 2;
}
```

**Output:**

```jsx
Error: Comment "comment 6a" was not printed. Please report this error!
    at pu (https://prettier.io/lib/standalone.js:27:5829)
    at Ze (https://prettier.io/lib/standalone.js:27:7320)
    at async Ou (https://prettier.io/lib/standalone.js:27:11026)
    at async Rr (https://prettier.io/lib/standalone.js:32:581)
    at async formatCode (https://prettier.io/worker.js:170:12)
    at async handleFormatMessage (https://prettier.io/worker.js:82:24)
    at async self.onmessage (https://prettier.io/worker.js:37:14)
```

**Expected behavior:**

See https://github.com/prettier/prettier/pull/15076#discussion_r1259242307

**Comment by markstein-moll** [comment]
Same problem with version 3.0.0 in the following **TypeScript** snippet:
```
for (const division of collidingDivisions) {
	if (!division.properties.canRemove) {
		if (division.canContainSingleParagraph(startParagraph)) continue; // selection starting in r/o div: always OK to delete
		else if (endParagraph !== division.endParagraph && division.canContainSingleParagraph(endParagraph)) continue; // selection ending in r/o div: OK to delete IF it is NOT last paragraph (which would get absorbed)
		else { // selection over whole r/o div OR ending in last paragraph (which would get absorbed) -> FAIL
			console.warn('deleteSelectedTextAndJoinRemainingNodes(): cannot delete because of must-keep division: ' + division.properties.name);
			return { success: false, reason: DeleteAndJoinErrorReason.READONLY_DIVISION };
		}
	}
}
```

**Error:**
```
[error] EditableArticle.ts: Error: Comment "selection starting in r/o div: always OK to delete" was not printed. Please report this error!
[error]     at ensureAllCommentsPrinted
[error]     at printAstToDoc
[error]     at async coreFormat
[error]     at async formatWithCursor
[error]     at async formatFiles
[error]     at async main
[error]     at async Module.run
```

**Comment by sosukesuzuki** [comment]
This is duplicated to #15470

**Comment by sosukesuzuki** [comment]
Sorry I mistook
