### ISSUE TITLE
Prettier: Error while reformatting

### ISSUE THREAD

**Issue by saeed51100** [prettier/prettier#15263]
I have installed and configured prettier in next.js project in phpstorm.
I use the prettier plugin in phpstorm.
When I use the prettier command line there is no problem and the code is formatted correctly like the command below:
prettier --write components/sidebar.jsx
But when I try to format the code using Alt+Shift+Ctrl+P shortcuts, I get the following error:
Prettier: Error while reformatting
Show details

TypeError: prettierApi.resolveConfig.sync is not a function
     at PrettierPlugin.resolveConfig (C:\Users\saeed\AppData\Roaming\JetBrains\PhpStorm2021.3\plugins\prettierJS\prettierLanguageService\prettier-plugin.js:42:48)
     at PrettierPlugin.handleReformatCommand (C:\Users\saeed\AppData\Roaming\JetBrains\PhpStorm2021.3\plugins\prettierJS\prettierLanguageService\prettier-plugin.js:28:27)
     at PrettierPlugin.onMessage (C:\Users\saeed\AppData\Roaming\JetBrains\PhpStorm2021.3\plugins\prettierJS\prettierLanguageService\prettier-plugin.js:13:33)
     at Interface.<anonymous> (C:\Program Files\JetBrains\PhpStorm 2021.3\plugins\JavaScriptLanguage\jsLanguageServicesImpl\js-language-service.js:105:39)
     at Interface.emit (node:events:513:28)
     at [_onLine] [as _onLine] (node:internal/readline/interface:422:12)
     at [_normalWrite] [as _normalWrite] (node:internal/readline/interface:616:22)
     at Socket.ondata (node:internal/readline/interface:249:23)
     at Socket.emit (node:events:513:28)
     at addChunk (node:internal/streams/readable:324:12)
Process finished with exit code -

What should I do to solve the problem?

**Comment by auvred** [comment]
Hi, according to the stack trace, you're using `PhpStorm2021.3`

> TypeError: prettierApi.resolveConfig.sync is not a function

It seems that this version of PhpStorm doesn't support new prettier v3 async api. Try to update you IDE

---

There is a similar issue in JetBrains issue tracker:
https://youtrack.jetbrains.com/issue/IDEA-326133/Prettier-plugin-not-working-prettier.resolveConfig.sync-is-not-a-function#focus=Comments-27-7907818.0-0

_Will be fixed in the future 2023.2.1. You may use an old prettier version (before 3.0) as a workaround._

**Comment by saeed51100** [comment]
Hello, thank you, the problem is solved.
Downgrading prettier to "prettier": "2.4.x" solved the problem.
