### ISSUE TITLE
Error: unknown type: "ChainExpression" (optional chaining)

### ISSUE THREAD

**Issue by aistrike01** [prettier/prettier#15489]
### Envirements:

- Prettier Version: 2.8.4
- Running Prettier via: VS Code
- Runtime: Node.js v20.5.0
- Operating System: macOS
- Prettier plugins: prettier-plugin-organize-imports, prettier-plugin-prisma

### Description:

The error appears when I format the code and it contains optional chaining. Formatting doesn't work

P.S. If you need more information, I will provide it, the error only occurs on a specific project, which I unfortunately cannot show.

```
const obj = { a: "Hello" }

obj?.a
```
### Error:

<img width="1440" alt="Снимок экрана 2023-10-05 в 11 56 00" src="https://github.com/prettier/prettier/assets/69678753/5def7ecb-6198-46f2-9a70-c00314ad3fbc">

```
Error: unknown type: "ChainExpression"
    at printPathNoParens (/Users/user/Desktop/project/node_modules/prettier/index.js:30031:17)
    at Object.genericPrint [as print] (/Users/user/Desktop/project/node_modules/prettier/index.js:29622:23)
    at callPluginPrintFunction (/Users/user/Desktop/project/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/user/Desktop/project/node_modules/prettier/index.js:8550:22)
    at /Users/user/Desktop/project/node_modules/prettier/index.js:8542:32
    at AstPath.call (/Users/user/Desktop/project/node_modules/prettier/index.js:8359:24)
    at mainPrint (/Users/user/Desktop/project/node_modules/prettier/index.js:8542:21)
    at printPathNoParens (/Users/user/Desktop/project/node_modules/prettier/index.js:29711:19)
    at Object.genericPrint [as print] (/Users/user/Desktop/project/node_modules/prettier/index.js:29622:23)
    at callPluginPrintFunction (/Users/user/Desktop/project/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/user/Desktop/project/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/user/Desktop/project/node_modules/prettier/index.js:8537:18)
    at /Users/user/Desktop/project/node_modules/prettier/index.js:28747:25
    at AstPath.each (/Users/user/Desktop/project/node_modules/prettier/index.js:8384:11)
    at printStatementSequence (/Users/user/Desktop/project/node_modules/prettier/index.js:28742:12)
    at printBody (/Users/user/Desktop/project/node_modules/prettier/index.js:28840:14)
    at printBlockBody (/Users/user/Desktop/project/node_modules/prettier/index.js:28972:20)
    at printPathNoParens (/Users/user/Desktop/project/node_modules/prettier/index.js:29698:18)
    at Object.genericPrint [as print] (/Users/user/Desktop/project/node_modules/prettier/index.js:29622:23)
    at callPluginPrintFunction (/Users/user/Desktop/project/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/user/Desktop/project/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/user/Desktop/project/node_modules/prettier/index.js:8537:18)
    at printAstToDoc (/Users/user/Desktop/project/node_modules/prettier/index.js:8529:18)
    at coreFormat (/Users/user/Desktop/project/node_modules/prettier/index.js:8837:20)
    at formatWithCursor2 (/Users/user/Desktop/project/node_modules/prettier/index.js:9021:18)
    at /Users/user/Desktop/project/node_modules/prettier/index.js:38176:12
    at Object.format (/Users/user/Desktop/project/node_modules/prettier/index.js:38190:12)
    at t.PrettierMainThreadInstance.format (/Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:18023)
    at t.default.format (/Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:16114)
    at t.PrettierEditProvider.provideEdits (/Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:12672)
    at O.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:45388)
```

**Expected behavior:**
Format code

**Actual behavior:**
Throws an error

**Comment by kachkaev** [comment]
👋 @aistrike01! Please try upgrading Prettier to v3 or the latest v2 (2.8.8). Your bug report mentions 2.8.4 and the bug fix must be https://github.com/prettier/prettier/pull/13735. If you still have the issue after upgrading, please share reproduction steps that involve Prettier core only (ideally, the [Playground](https://prettier.io/playground/)). VS Code extension is https://github.com/prettier/prettier/labels/scope%3Aexternal to this repo.

----

**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2EwEMlMAdEACTgBsGIbMBfKqT3PAfgDoynEABoQEAA4wAlumSgyAJ0UQA7gAUlCNMhBkGqsgE8dYnIrJgA1nBgBlMgFs4AGWlQ4yAGb60cMxbWtnYSlu4A5sgwigCu-iB+jtJRsfFoEQxwAIoxEPDevvF4aAAedhnZuflIPgx+YgCOVXDqKhI6KGRoALQecAAmA6Ig0WTSDBEAwhCOjmS6+gzD6VDhmQCCMNHSODHw6nCKbh4FdfEAFjCODADq59LwaKFgcHbaD9IAbg9GumBophAnziAEkoINYHYwIppFJ1uC7DAjJlTvUQBIVH4bhYJLoMXA-IpPp4xO5CTBWmRwnNUfFQopCbocGQcIxhhj3DAbtJ+jBzsgABwABjEijgTWkYsp1PmNUKYhgLO5vP5SAATGIYn4ACosjq1NFwRys-qDfouMirGJUuAAMQgijmWwiCz2EBAbDYQA)

```sh
--parser babel
```

**Input:**

```jsx
const obj = { a: "Hello" }

obj?.a

```

**Output:**

```jsx
const obj = { a: "Hello" };

obj?.a;

```
