### ISSUE TITLE
pre-commit installation fails due to version conflict with nodeenv

### ISSUE THREAD

**Issue by TimOrme** [prettier/prettier#15600]
Apologies if this is the wrong place to open this ticket; I tried to open it on the mirrors-prettier repo, but it doesn't allow issues to be opened.

**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: pre-commit hook
- Runtime: nodeenv
- Operating System: macOS
- Prettier plugins (if any): None

**Steps to reproduce:**

1. Install `pre-commit` using the brew package [here](https://formulae.brew.sh/formula/pre-commit).
2. Create a repo with pre-commit installed, and a pre-commit config like:

```
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
```

3. Try and run the pre-commit hooks using:

```
pre-commit run --all-files
```

**Expected behavior:**
The pre-commit hooks should install prettier and then run it.

**Actual behavior:**
The installation fails with:

```
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/Cellar/pre-commit/3.5.0_1/libexec/bin/python3.12', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/ralcarazmercado/.cache/pre-commit/repojajmypca/node_env-default')
return code: 1
stdout: (none)
stderr:
    /usr/local/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
      import pipes
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/usr/local/Cellar/pre-commit/3.5.0_1/libexec/lib/python3.12/site-packages/nodeenv.py", line 48, in <module>
        from pkg_resources import parse_version
    ModuleNotFoundError: No module named 'pkg_resources'
```

I believe this is due to a couple of versioning pieces conflicting.

1. The brew pacakge for pre-commit uses `python 3.12`
2. python 3.12 has removed the `pkg_resources` package from the default install [release notes](https://docs.python.org/3/whatsnew/3.12.html)
3. The prettier pre-commit hook depends on `nodeenv`
4. `nodeenv` is still importing `pkg_resources` and so doesn't work on install.  There is a fix for this merged into master, but unreleased as of now.  [pr](https://github.com/ekalinin/nodeenv/pull/338)

It's a bit unclear to me who needs to address this, but it seems like the brew install for pre-commit has a pretty agressive release of python as its dependency, given that 3.12 is only about a month old.  I'm not sure if there's anything prettier can do about this either, but figured I'd raise it here in case a dependency could be pinned back to address this for prettier.

**Comment by yingxun-lim** [comment]
im running into the same issue when trying to configure the pre-commit hook for eslint as well.

**Comment by CJTurpie** [comment]
A temporary fix seems to be to run `brew install python-setuptools`

**Comment by ssbarnea** [comment]
https://github.com/pre-commit/mirrors-prettier was archived recently as the maintainers said prettier changes made maintenance not possible. That is a big issue as both pre-commit and prettier are very useful tools and I do not fancy using them separately. Did any sorted that issue?
