### ISSUE TITLE
TypeError: join(...).filter is not a function

### ISSUE THREAD

**Issue by LazerJesus** [prettier/prettier#16095]
I am trying to format a svelte component from the cli and am getting this error:
```
$ ⟩  npx prettier --plugin prettier-plugin-svelte --write +page.svelte 
npx prettier --plugin prettier-plugin-svelte --write +page.svelte 
+page.svelte
[error] +page.svelte: TypeError: join(...).filter is not a function
[error]     at splitTextToDocs (/Users/x/code/spanish/app/auth-ui/node_modules/prettier-plugin-svelte/plugin.js:1809:34)
[error]     at Object.print (/Users/x/code/spanish/app/auth-ui/node_modules/prettier-plugin-svelte/plugin.js:981:29)
[error]     at callPluginPrintFunction (file:///Users/x/.nvm/versions/node/v18.12.1/lib/node_modules/prettier/index.mjs:22303:20)
[error]     at mainPrintInternal (file:///Users/x/.nvm/versions/node/v18.12.1/lib/node_modules/prettier/index.mjs:22286:18)
[error]     at mainPrint (file:///Users/x/.nvm/versions/node/v18.12.1/lib/node_modules/prettier/index.mjs:22269:14)
[error]     at AstPath.call (file:///Users/x/.nvm/versions/node/v18.12.1/lib/node_modules/prettier/index.mjs:20753:14)
[error]     at printChild (/Users/x/code/spanish/app/auth-ui/node_modules/prettier-plugin-svelte/plugin.js:1637:21)
[error]     at handleTextChild (/Users/x/code/spanish/app/auth-ui/node_modules/prettier-plugin-svelte/plugin.js:1692:28)
[error]     at printChildren (/Users/x/code/spanish/app/auth-ui/node_modules/prettier-plugin-svelte/plugin.js:1617:13)
[error]     at body (/Users/x/code/spanish/app/auth-ui/node_modules/prettier-plugin-svelte/plugin.js:1082:30)
 
$ ⟩ npx prettier --version
3.2.5
```

**Comment by sosukesuzuki** [comment]
I think this is a bug in the plugin, please follow the comment in the issue on the plugin side
