### ISSUE TITLE
Error when file names 

### ISSUE THREAD

**Issue by Mrgaton** [prettier/prettier#16225]
../../Imágenes/foto perfil Letsoky🌙.webpnode:internal/fs/promises:604
    await binding.openFileHandle(pathModule.toNamespacedPath(path),
                  ^

Error: ENOENT: no such file or directory, open
    at open (node:internal/fs/promises:604:19)
    at Object.readFile (node:internal/fs/promises:1071:20)
    at formatFiles (file:///C:/Users/Mrgaton/AppData/Local/pnpm/global/5/.pnpm/prettier@3.2.4/node_modules/prettier/internal/cli.mjs:6647:25)
    at async main (file:///C:/Users/Mrgaton/AppData/Local/pnpm/global/5/.pnpm/prettier@3.2.4/node_modules/prettier/internal/cli.mjs:7081:5)
    at async Module.run (file:///C:/Users/Mrgaton/AppData/Local/pnpm/global/5/.pnpm/prettier@3.2.4/node_modules/prettier/internal/cli.mjs:7027:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open'
}

**Comment by Mrgaton** [comment]
It should ignore files with emojis not crash the app

**Comment by sosukesuzuki** [comment]
Sorry I was not able to figure out what was going on just from the first information you gave me. Can you update the issue according to the issue template?

**Comment by Mrgaton** [comment]
When I prettify a directory if it has a file with weird characters like a emoji it crashes
