### ISSUE TITLE
Importing plugins in browser with typescript

### ISSUE THREAD

**Issue by jaimiebowen** [prettier/prettier#16838]
I'm having some trouble importing plugins in order to format HTML in the browser as part of an Angular project (using typescript). I have prettier installed via NPM.

**Environments:**
- Prettier Version: 3.3.3
- Running Prettier via: Browser API
- Runtime: Chrome 130.0.6723.117
- Operating System: Windows
- Prettier plugins (if any): @prettier/plugin-html

**Steps to reproduce:**

1. If I try to pass a string file path to plugins:
```
import { format } from 'prettier';

protected async updateHtmlSnippet() {
    ...

    this.htmlSnippet = await format(this.htmlSnippet, {
      tabWidth: 2,
      semi: true,
      singleQuote: true,
      parser: 'html',
      plugins: ['prettier/plugin-html'],
    });

    ...
  }
```

I get this error:

```
ERROR ConfigError: Couldn't resolve parser "html". Plugins must be explicitly added to the standalone bundle.
    at qt (standalone.mjs:3046:77)
    at standalone.mjs:3095:9
    at Generator.next (<anonymous>)
    at chunk-TXDUYLVM.js?v=5268867e:72:61
    at new ZoneAwarePromise (zone.js:2702:25)
    at __async (chunk-TXDUYLVM.js?v=5268867e:56:10)
    at wo (standalone.mjs:3077:30)
    at standalone.mjs:3572:19
    at Generator.next (<anonymous>)
    at chunk-TXDUYLVM.js?v=5268867e:72:61
```

2. If I try to import parserHtml:
```
import { format } from 'prettier';
import { parserHtml } from 'prettier/parser-html';

protected async updateHtmlSnippet() {
    ...

    this.htmlSnippet = await format(this.htmlSnippet, {
      tabWidth: 2,
      semi: true,
      singleQuote: true,
      parser: 'html',
      plugins: [parserHtml],
    });

    ...
  }
```

I get an import error in VS Code:
```
Module '"prettier/plugins/html.js"' has no exported member 'parserHtml'.ts(2305)
```

3. If I try to import prettierPluginHtml from the .mjs file:
```
import { format } from 'prettier';
import { prettierPluginHtml } from 'prettier/plugins/html.mjs';

protected async updateHtmlSnippet() {
    ...

    this.htmlSnippet = await format(this.htmlSnippet, {
      tabWidth: 2,
      semi: true,
      singleQuote: true,
      parser: 'html',
      plugins: [parserHtml],
    });

    ...
  }
```

I get this error about a missing declaration file:
```
Could not find a declaration file for module 'prettier/plugins/html.mjs'. '/workspaces/force-style-guide/node_modules/.pnpm/prettier@3.3.3/node_modules/prettier/plugins/html.mjs' implicitly has an 'any' type.
  If the 'prettier' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'prettier/plugins/html.mjs';`
```

**Comment by jaimiebowen** [comment]
Nevermind, importing parserHtml differently worked:

```
import { format } from 'prettier';
import * as parserHtml from 'prettier/parser-html';

protected async updateHtmlSnippet() {
    ...

    this.htmlSnippet = await format(this.htmlSnippet, {
      tabWidth: 2,
      semi: true,
      singleQuote: true,
      parser: 'html',
      plugins: [parserHtml],
    });

    ...
  }
