### ISSUE TITLE
prettier 1.4.3 failing with css

### ISSUE THREAD

**Issue by jfranty** [prettier/prettier#2042]
```
$ npm install -g prettier@1.4.2
/usr/local/bin/prettier -> /usr/local/lib/node_modules/prettier/bin/prettier.js
+ prettier@1.4.2
updated 1 package in 0.715s

$ prettier foo.css
.bar {
  color: blue;
}

$ npm install -g prettier@1.4.3
/usr/local/bin/prettier -> /usr/local/lib/node_modules/prettier/bin/prettier.js
+ prettier@1.4.3
updated 1 package in 0.734s

$ prettier foo.css

foo.css: TypeError: parseFunction is not a function
    at Object.parse (/usr/local/lib/node_modules/prettier/index.js:12569:12)
    at formatWithCursor (/usr/local/lib/node_modules/prettier/index.js:12767:22)
    at Object.formatWithCursor (/usr/local/lib/node_modules/prettier/index.js:12975:12)
    at format (/usr/local/lib/node_modules/prettier/bin/prettier.js:5475:19)
    at filename (/usr/local/lib/node_modules/prettier/bin/prettier.js:5588:16)
    at patterns.forEach.pattern (/usr/local/lib/node_modules/prettier/bin/prettier.js:5654:7)
    at Array.forEach (native)
    at eachFilename (/usr/local/lib/node_modules/prettier/bin/prettier.js:5649:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier/bin/prettier.js:5549:3)
    at Module._compile (module.js:571:32)
```

The new version still works for JS, though.

**Comment by vjeux** [comment]
Grrr, looking into it. Thanks for the report :)

**Comment by vjeux** [comment]
1.4.4 should fix it

**Comment by jfranty** [comment]
Just confirming that 1.4.4 works for me. Thanks for such a quick fix!
