### ISSUE TITLE
formatWithCursor issue

### ISSUE THREAD

**Issue by pgherveou** [prettier/prettier#2131]
Hey there,
Thanks for this awesome project. 
I think there is a bug in the `formatWithCursor` api. 

When I try to execute the following code

```js
prettier.formatWithCursor(
`
foo('bar', cb => {
  console.log('stuff')
})`, {cursorOffset: 24})
```
I get the following exception
```
TypeError: Cannot convert a Symbol value to a string
    at Array.join (native)
    at printDocToString$1 (xxx/node_modules/prettier/index.js:8495:63)
    at formatWithCursor (xxx/node_modules/prettier/index.js:12787:26)
    at Object.formatWithCursor (xxx/node_modules/prettier/index.js:12975:12)
    at repl:1:10
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
```

**Comment by azz** [comment]
cc. @josephfrazier
