### ISSUE TITLE
Error.loc Inconsistencies

### ISSUE THREAD

**Issue by robwise** [prettier/prettier#2428]
I'm trying to use the `loc` property from the Error object that Prettier returns in case of bad input to show inline error highlighting in prettier-atom. 

However, I've noticed that the schema seems to change a lot and I was wondering if you had some more insight into what was going on here. 

I can only reproduce the first of the following types (PrettierErrorA), but based on the errors that users are reporting, there are also two others:

```js
type PrettierErrorA = {
  loc: { start: { line: number, column: number } },
};

type PrettierErrorB = {
  loc: { line: number, column: number },
};

type PrettierErrorC = {
};
```

**Comment by vjeux** [comment]
This is weird, we should feed everything through createError wrapper which reads from `error.start.line` and `error.start.column`. Do you have examples where the last 2 are thrown?

https://github.com/prettier/prettier/search?utf8=%E2%9C%93&q=createError&type=

**Comment by vjeux** [comment]
In the error you linked, I can't find the prettier stack trace. That would be helpful to see what lines are responsible for the error.

**Comment by robwise** [comment]
@mattapperson Do you remember what the file was when you got that prettier-atom error in https://github.com/prettier/prettier-atom/issues/226#issuecomment-313665570?

I'm at a bit of a disadvantage myself as I did not personally encounter these errorrs. When I was writing the error handler for prettier-atom I was only looking at the createError API and figured every error coming out of Prettier would look like that. However, I'm reading through the various parsers and sometimes there are other types of errors being thrown? I suppose it's also possible that the errors are being thrown by a printer? Should I just not assume all errors thrown by prettier are going to have a `loc`? That's not a problem, I just didn't realize that might happen.

- **Flow Parser:**
It seems like the flow parser throws an `end` prop as well but it's discarded? Also, there's no catch in that code, unlike the others. It looks like the flow parser catches itself and then returns an array of errors so that's probably why? https://github.com/prettier/prettier/blob/master/src/parser-flow.js#L22
- **Parse5 Parser:** I don't know what a Parse5 parser is but that seems to be throwing an error without going through `createError`. https://github.com/prettier/prettier/blob/master/src/parser-parse5.js#L16-L21
- **PostCSS Parser:** there seems to be a non-location error that gets thrown here?
 https://github.com/prettier/prettier/blob/master/src/parser-postcss.js#L194-L196
- **GraphQL Parser:** This also seems to be able to throw a non-loc-based error. https://github.com/prettier/prettier/blob/master/src/parser-graphql.js#L55

**Comment by colshacol** [comment]
Stack trace for my local `prettier-atom` error:

```
TypeError: Cannot read property 'start' of undefined
    at errorLine (/home/colshacol/.atom/packages/prettier-atom/dist/executePrettier/handleError.js:15:19)
    at buildPointArrayFromPrettierErrorAndRange (/home/colshacol/.atom/packages/prettier-atom/dist/executePrettier/handleError.js:24:22)
    at setErrorMessageInLinter (/home/colshacol/.atom/packages/prettier-atom/dist/executePrettier/handleError.js:40:29)
    at /home/colshacol/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:49:114
    at executePrettierOnBufferRange (/home/colshacol/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:45:5)
    at executePrettierOnCurrentBufferRange (/home/colshacol/.atom/packages/prettier-atom/dist/manualFormat/index.js:27:10)
    at r (/home/colshacol/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5:165)
    at /home/colshacol/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:97:162
    at r (/home/colshacol/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5:165)
    at /home/colshacol/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:63:325
    at /home/colshacol/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:49:144
    at atom-workspace.lazyFormat (/home/colshacol/.atom/packages/prettier-atom/dist/main.js:33:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:265:29)
    at /usr/lib/atom/src/command-registry.js:3:59
    at Object.didConfirmSelection (/usr/lib/atom/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:296:20)
    at HTMLDivElement.core:confirm (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:64:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:265:29)
    at /usr/lib/atom/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:606:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:397:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:100:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:59)
```

**Comment by robwise** [comment]
@colshacol Do you think I'd be able to reproduce? Can you put the source code here or is it sensitive code?

**Comment by vjeux** [comment]
I'm going to close that until we have more information. If you manage to find a concrete case where it doesn't properly do what you expect, please let me know and I'll get it fixed.
