### ISSUE TITLE
markdown bug: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by MoOx** [prettier/prettier#3091]
**Prettier from git c0aaa0fa523a0cd4cf112fa5e53efe35a62c454b**

**Input:**
https://raw.githubusercontent.com/putaindecode/putaindecode.io/18142bb8e0f638e661ba6dafaab633cb65b5847a/content/fr/evenements/2014/05/table-ronde-3/index.md

**Expected behavior:**

formating should not throw

```
[error] content/fr/evenements/2014/05/table-ronde-3/index.md: TypeError: Cannot read property 'replace' of undefined
[error]     at Object.getStringWidth (~/node_modules/prettier/src/util.js:746:27)
[error]     at currentWidths.map (~/node_modules/prettier/src/printer-markdown.js:346:30)
[error]     at Array.map (<anonymous>)
[error]     at contents.reduce (~/node_modules/prettier/src/printer-markdown.js:345:21)
[error]     at Array.reduce (<anonymous>)
[error]     at printTable (~/node_modules/prettier/src/printer-markdown.js:343:36)
[error]     at genericPrint (~/node_modules/prettier/src/printer-markdown.js:270:14)
[error]     at genericPrint (~/node_modules/prettier/src/printer.js:148:55)
[error]     at comments.printComments.p (~/node_modules/prettier/src/printer.js:4933:14)
[error]     at Object.printComments (~/node_modules/prettier/src/comments.js:1085:19)```

**Comment by MoOx** [comment]
problem comes from this snippets

```md
Membres | Statut
--------|:------:
[_kud](https://twitter.com/_kud) | 👮
[bloodyowl](https://twitter.com/bloodyowl) | 🏠
[yannickc](https://twitter.com/yannickc) |
[dhoko_](https://twitter.com/dhoko_) | 
[philippebarbosa](https://twitter.com/philippebarbosa) |
[tchak13](https://twitter.com/tchak13) |
[remitbri](https://twitter.com/remitbri) |
[dizwix](https://twitter.com/dizwix) |
```

Some empty cells are REALLY empty. Adding a space allow parsing/formatting to work.

**Comment by azz** [comment]
Thanks for the report! Should be an easy fix.
