### ISSUE TITLE
Problem with JSON

### ISSUE THREAD

**Issue by zimme** [prettier/prettier#3725]
**Prettier 1.10.2**
[Reproduction link](https://github.com/zimme/prettier-issue)

Something has changed in `1.10+` which is causing warnings in some cases
in `prettier-eslint`. I haven't been able to reproduce it with `prettier` so I'm
guessing it's related to using the API.

I'm not sure, but I get a feeling that it's related to BOM or line ending/newline
in package.json.

I don't know if it's in `format` or if it's in `resolveConfig.sync`.

```
> prettier-issue@1.0.0 format /Users/zimme/prettier-issue
> prettier-eslint --write "**/*.{js,json}"

prettier-eslint [ERROR]: prettier formatting failed due to a prettier error
prettier-eslint-cli [ERROR]: There was an error formatting "foo.js":
    JSONError: Unexpected end of JSON input while parsing near '' in package.json
        at module.exports (/Users/zimme/prettier-issue/node_modules/prettier/index.js:3676:19)
        at parse$2 (/Users/zimme/prettier-issue/node_modules/prettier/index.js:3773:31)
        at Function.sync$2 [as sync] (/Users/zimme/prettier-issue/node_modules/prettier/index.js:3776:20)
        at Function.module.exports.sync (/Users/zimme/prettier-issue/node_modules/prettier/index.js:6900:25)
        at Function.module.exports.sync.opts [as sync] (/Users/zimme/prettier-issue/node_modules/prettier/index.js:6933:16)
        at loadPlugins (/Users/zimme/prettier-issue/node_modules/prettier/index.js:18275:19)
        at normalize$2 (/Users/zimme/prettier-issue/node_modules/prettier/index.js:24357:24)
        at Object.format (/Users/zimme/prettier-issue/node_modules/prettier/index.js:33945:25)
        at prettify (/Users/zimme/prettier-issue/node_modules/prettier-eslint/dist/index.js:159:29)
        at format (/Users/zimme/prettier-issue/node_modules/prettier-eslint/dist/index.js:145:20)
        at MapSubscriber.project (/Users/zimme/prettier-issue/node_modules/prettier-eslint-cli/dist/format-files.js:305:55)
        at MapSubscriber._next (/Users/zimme/prettier-issue/node_modules/rxjs/operators/map.js:79:35)
        at MapSubscriber.Subscriber.next (/Users/zimme/prettier-issue/node_modules/rxjs/Subscriber.js:90:18)
        at AsyncSubject.Subject.next (/Users/zimme/prettier-issue/node_modules/rxjs/Subject.js:55:25)
        at AsyncSubject.complete (/Users/zimme/prettier-issue/node_modules/rxjs/AsyncSubject.js:46:35)
        at handlerFn (/Users/zimme/prettier-issue/node_modules/rxjs/observable/BoundNodeCallbackObservable.js:193:33)
success formatting 2 files with prettier-eslint
failure formatting 1 file with prettier-eslint
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prettier-issue@1.0.0 format: `prettier-eslint --write "**/*.{js,json}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prettier-issue@1.0.0 format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zimme/.npm/_logs/2018-01-11T22_26_51_066Z-debug.log
```

**Comment by zimme** [comment]
I do believe this happens when `package.json` is being read while formatting other files.

So maybe this is related to `comsiconfig`?

**Comment by zimme** [comment]
or maybe it's `read-pkg-up` in this commit, https://github.com/prettier/prettier/commit/e5d6a4704f2427cdf3baa0a1c941dd797c513993

**Comment by azz** [comment]
Probably `read-pkg-up`. Could you put `try`/`catch` around it and test?

https://github.com/prettier/prettier/commit/e5d6a4704f2427cdf3baa0a1c941dd797c513993#diff-9e0934c7a0ce8de1ef8abc92bfe3ad6dR22

**Comment by zimme** [comment]
The following issues mention `npm cache clean --force` which solved this for me.
I guess there was some old stuff causing the problem.

https://github.com/vuejs-templates/webpack/issues/990
https://github.com/npm/npm/issues/19072

Closing this as resolved.
