### ISSUE TITLE
Build is failing on Node.js 4 in production mode

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#3875]
Several recent testing runs have failed because the Jest process gets “Killed:”

```
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/home/travis/build/prettier/prettier/node_modules/shelljs/src/common.js:417
      if (config.fatal) throw e;
                        ^
Error: exec: internal error
    at Object.error (/home/travis/build/prettier/prettier/node_modules/shelljs/src/common.js:128:27)
    at Object._exec (/home/travis/build/prettier/prettier/node_modules/shelljs/src/exec.js:292:12)
    at Object.exec (/home/travis/build/prettier/prettier/node_modules/shelljs/src/common.js:350:23)
    at Object.<anonymous> (/home/travis/build/prettier/prettier/scripts/test-dist.js:23:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

[source](https://travis-ci.org/prettier/prettier/jobs/335759276#L1087-L1106)

**Comment by evilebottnawi** [comment]
FYI: manually restart job fix this

**Comment by evilebottnawi** [comment]
Update to `shellj@0.8.1` fixed this problem. See https://github.com/shelljs/shelljs/blob/master/CHANGELOG.md#v081-2018-01-20

> Exec failing with internal error when piping large output #818

**Comment by j-f1** [comment]
Looks like this still isn’t fixed.

**Comment by evilebottnawi** [comment]
@j-f1 yep :disappointed:

**Comment by josephfrazier** [comment]
A couple of possibilities:

* https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error
* https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out

**Comment by evilebottnawi** [comment]
We drop node@4, so we can close this issue
