### ISSUE TITLE
Errors when range does not include curly brackets (via rangeStart and rangeEnd) in json files using node api

### ISSUE THREAD

**Issue by erik-inkapool** [prettier/prettier#4009]
Hello Prettier team and thank you for all the hard work you put into this awesome tool. Truly amazing work! 🥇 

I have an issue to report though. When formatting json files using the node api and providing rangeStart and rangeEnd values not including start `{`-sign or end `}` sign it errors. 

I could not recreate it with the playground (unless I missed the rangeStart/rangeEnd options there in which case I am sorry. If it's possible just tell me and I'll put up the repro there instead).

**Prettier 1.10.2**
Reproduction repro: https://github.com/erik-lundgren/prettier-json-range-bug
```js
{
    filepath: filepath,
    rangeStart: 1, // skip start {
    rangeEnd: fileContents.indexOf("}") // skip end }
}
```

**Input:**
```json
{
    "foo": "bar"
}

```

**Output:**
```jsx
SyntaxError: Unexpected token (1:6)
> 1 | "foo": "bar"
    |      ^
    at createError (C:\Projects\prettier-json-range-bug\node_modules\prettier\
parser-babylon.js:1:110)
    at Object.parse (C:\Projects\prettier-json-range-bug\node_modules\prettier
\parser-babylon.js:1:986)
    at Object.parse$4 [as parse] (C:\Projects\prettier-json-range-bug\node_mod
ules\prettier\index.js:24274:19)
    at formatWithCursor (C:\Projects\prettier-json-range-bug\node_modules\pret
tier\index.js:33650:27)
    at format (C:\Projects\prettier-json-range-bug\node_modules\prettier\index
.js:33695:10)
    at formatRange (C:\Projects\prettier-json-range-bug\node_modules\prettier\
index.js:33922:26)
    at formatWithCursor (C:\Projects\prettier-json-range-bug\node_modules\pret
tier\index.js:33654:30)
    at format (C:\Projects\prettier-json-range-bug\node_modules\prettier\index
.js:33695:10)
    at format (C:\Projects\prettier-json-range-bug\node_modules\prettier\index
.js:33945:12)
    at Object.<anonymous> (C:\Projects\prettier-json-range-bug\index.js:8:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
error Command failed with exit code 1.
```

**Expected behavior:**
Output formatted file, exit code 0.

**Additional debug information**
Operating system: Windows 10
yarn version: 1.3.2
node version: 8.9.4

Let me know if I can provide any more details

**Comment by thorn0** [comment]
Closing in favor of #7116
