### ISSUE TITLE
Tests on master are failing

### ISSUE THREAD

**Issue by ericanderson** [prettier/prettier#4053]
```
Summary of all failing tests
 FAIL  tests/typescript_conditional_types/jsfmt.spec.js
  ● Test suite failed to run

    SyntaxError: ';' expected. (1:33)
    > 1 | export type DeepReadonly<T> = T extends any[] ? DeepReadonlyArray<T[number]> : T extends object ? DeepReadonlyObject<T> : T;
        |                                 ^
      2 |
      3 | type NonFunctionPropertyNames<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T];
      4 |

      at createError (src/common/parser-create-error.js:5:17)
      at Object.parse (src/language-js/parser-typescript.js:23:11)
      at Object.parse (src/main/parser.js:75:19)
      at formatWithCursor (index.js:101:25)
      at format (index.js:146:10)
      at Object.format (index.js:406:12)
      at prettyprint (tests_config/run_spec.js:119:19)
      at fs.readdirSync.forEach.filename (tests_config/run_spec.js:43:22)
          at Array.forEach (<anonymous>)
      at run_spec (tests_config/run_spec.js:17:27)
      at Object.<anonymous> (tests/typescript_conditional_types/jsfmt.spec.js:1:90)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at process.emit (events.js:160:13)
      at emit (internal/child_process.js:790:12)
      at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by ericanderson** [comment]
Touche
