### ISSUE TITLE
Bug with prettier-plugin and comments

### ISSUE THREAD

**Issue by thorbenvh8** [prettier/prettier#4217]
Hi,
in prettier-java everything runs normally if you do it from the original prettier-plugin project.
But if you add it as a dependency to a project and run the command you get an error:

```java
public class Test {

  public void test() {
    // A comment
    return;
  }
}
```
```
test-prettier git:(master) yarn prettier --write "**/*.java"
yarn run v1.3.2
$ /Users/thorbenvh8/workspace/test-prettier/node_modules/.bin/prettier --write '**/*.java'
TestFile.java
[error] TestFile.java: TypeError: options.locEnd is not a function
[error]     at path$$1.each.commentPath (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:9084:44)
[error]     at FastPath.each (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:20088:7)
[error]     at Object.printComments (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:9068:11)
[error]     at printGenerically (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:23398:22)
[error]     at FastPath.map (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:20116:19)
[error]     at printBlock (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier-plugin-java/src/printer.js:683:34)
[error]     at printNode (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier-plugin-java/src/printer.js:2223:14)
[error]     at Object.genericPrint [as print] (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier-plugin-java/src/printer.js:2571:10)
[error]     at genericPrint$6 (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:23462:18)
[error]     at comments.printComments.p (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:23400:14)
[error]     at Object.printComments (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:9058:19)
[error]     at printGenerically (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:23398:22)
[error]     at FastPath.call (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:20062:18)
[error]     at printMethodDeclaration (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier-plugin-java/src/printer.js:603:20)
[error]     at printNode (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier-plugin-java/src/printer.js:2211:14)
[error]     at Object.genericPrint [as print] (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier-plugin-java/src/printer.js:2571:10)
[error]     at genericPrint$6 (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:23462:18)
[error]     at comments.printComments.p (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:23400:14)
[error]     at Object.printComments (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:9058:19)
[error]     at printGenerically (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:23398:22)
[error]     at FastPath.call (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier/bin-prettier.js:20062:18)
[error]     at printClassBodyMemberDeclaration (/Users/thorbenvh8/workspace/test-prettier/node_modules/prettier-plugin-java/src/printer.js:338:18)
error Command failed with exit code 2.
```

```
...
  comments: [
    {
      ast_type: "A Comment",
      leading: true,
      trailing: false,
      value: "// comment"
    }
 ]
...
```

Am I missing something on the comment thats mandatory? I really dont understand the problem.

I have created the repo for easy checkout and reproducing.
https://github.com/thorbenvh8/test-repository

Thanks for your help

**Comment by duailibe** [comment]
You need to export some functionality that's required by Prettier core, read https://prettier.io/docs/en/plugins.html#parsers
