### ISSUE TITLE
Test fails on master with "Cannot read property 'split' of null"

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#4588]
Since v1.13.0 (also observable on master now) whenever I run tests (`yarn test`) I get following errors:

```
$ yarn test
yarn run v1.7.0
$ jest
 FAIL  tests/flow/refinements/jsfmt.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'split' of null
      
      at splitPath (node_modules/find-parent-dir/index.js:10:20)
      at Object.<anonymous>.exports.sync [as findParentDir] (node_modules/find-parent-dir/index.js:44:18)
      at loadPlugins (src/common/load-plugins.js:21:36)
      at Object.formatWithCursor (index.js:21:16)
      at prettyprint (tests_config/run_spec.js:97:27)
      at fs.readdirSync.forEach.filename (tests_config/run_spec.js:48:22)
          at Array.forEach (<anonymous>)
      at run_spec (tests_config/run_spec.js:15:27)
      at Object.<anonymous> (tests/flow/refinements/jsfmt.spec.js:1:90)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:126:13)
      at process.emit (events.js:214:7)
      at emit (internal/child_process.js:772:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

 FAIL  tests/markdown_spec/jsfmt.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'split' of null
      
      at splitPath (node_modules/find-parent-dir/index.js:10:20)
      at Object.<anonymous>.exports.sync [as findParentDir] (node_modules/find-parent-dir/index.js:44:18)
      at loadPlugins (src/common/load-plugins.js:21:36)
      at Object.formatWithCursor (index.js:21:16)
      at prettyprint (tests_config/run_spec.js:97:27)
      at fs.readdirSync.forEach.filename (tests_config/run_spec.js:48:22)
          at Array.forEach (<anonymous>)
      at run_spec (tests_config/run_spec.js:15:27)
      at Object.<anonymous> (tests/markdown_spec/jsfmt.spec.js:1:90)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:126:13)
      at process.emit (events.js:214:7)
      at emit (internal/child_process.js:772:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

 FAIL  tests/flow/union-intersection/jsfmt.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'split' of null
      
      at splitPath (node_modules/find-parent-dir/index.js:10:20)
      at Object.<anonymous>.exports.sync [as findParentDir] (node_modules/find-parent-dir/index.js:44:18)
      at loadPlugins (src/common/load-plugins.js:21:36)
      at Object.formatWithCursor (index.js:21:16)
      at prettyprint (tests_config/run_spec.js:97:27)
      at fs.readdirSync.forEach.filename (tests_config/run_spec.js:48:22)
          at Array.forEach (<anonymous>)
      at run_spec (tests_config/run_spec.js:15:27)
      at Object.<anonymous> (tests/flow/union-intersection/jsfmt.spec.js:1:90)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:126:13)
      at process.emit (events.js:214:7)
      at emit (internal/child_process.js:772:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

I just listed fisth three fails, list is way longer

I tried fresh install with Yarn v1.7, and node v8.11.1 (macOS v10.13.4) and errors are there no matter what.

Tests pass without issues when I revert to v1.12.1

**Comment by azz** [comment]
Did you try delete `node_modules` and re-install?

**Comment by medikoo** [comment]
> Did you try delete node_modules and re-install?

Yes, same story

**Comment by azz** [comment]
Weird. Could you put some `console.log`s in `node_modules/find-parent-dir/index.js`? Are you running off a Samba share or something out of the ordinary?

**Comment by medikoo** [comment]
Ok, I after following stack trace, I think I got it.

It's because I don't have `prettier` in `prettier` directory, but in `prettier-elastic` (maintaining this fork -> https://github.com/medikoo/prettier-elastic )

And there's a hard-coded assumption that parent directory is [named `prettier`](https://github.com/prettier/prettier/blob/master/src/common/load-plugins.js#L22). I'd say it's quite controversial. Technically it'll crash for anyone with similar case.

**Comment by medikoo** [comment]
cc @ikatyang @kachkaev

**Comment by azz** [comment]
Ah ok, looks like you'll need to update that string to get it passing.

**Comment by azz** [comment]
I don't think there's anything we need to do in this repo? I guess we could change it to use `require('./package.json').name` instead.

**Comment by medikoo** [comment]
> I guess we could change it to use require('./package.json').name instead.

It wouldn't work, as I keep master 1:1 with this repo.
Maybe solution is to stop at first parent directory that has `package.json` ?

**Comment by azz** [comment]
Not sure I'm following. Why not just change the string in your fork?

**Comment by medikoo** [comment]
> Not sure I'm following. Why not just change the string in your fork?

When new version of prettier is released, before I merge it to my fork, first I switch to given tag (as you published it) and run tests there. 

It's to confirm there are no issues with published versions, before I'd update to it (occasionally you published versions with breaking tests, and then I know I can either hold back, or ignore those fails in my fork).

So committing this change to my master, won't solve anything to me, as your tags will not have this change, and still running tests on it will fail

**Comment by azz** [comment]
All commits (including tagged ones) run through TravisCI. I guess you could look at those results instead? e.g. https://travis-ci.org/prettier/prettier/jobs/385042003

**Comment by medikoo** [comment]
> All commits (including tagged ones) run through TravisCI. I guess you could look at those results instead

But I want to confirm that in my local setup (it's also to detect issues in that) :)

I think this issue may also hit you in your dev setup. e.g. imagine a case where one dev has some extensive work started on v2, but also needs to look after v1 from time to time. At some point it might be more productive to him to keep two repo copies (e.g. one in `prettier` and other in `prettier-v1`), now imagine his surprise on why tests doesn't pass in the latter ;-)

**Comment by azz** [comment]
If you want to PR to fix it in this repo I think that's fine, so long as it is simple and safe.

Since it isn't really an issue with Prettier itself I'm going to close this issue though.
