### ISSUE TITLE
pre-commit fails to run with prettier with "Cannot read property 'split' of null"

### ISSUE THREAD

**Issue by magicmark** [prettier/prettier#4637]
I think this is essentially the same issue as https://github.com/prettier/prettier/issues/4588

prettier fails to run with run with [pre-commit](https://github.com/pre-commit/pre-commit) on master.

This project [ostensibly supports being run via pre-commit](https://github.com/prettier/prettier/blob/master/.pre-commit-hooks.yaml) - until this is fixed, maybe we should remove support? (I'll try take a stab this weekend)

### Repro:
Run the following for a minimal repro
```bash
cd $(mktemp -d)
git init
virtualenv --python=python3.6 venv -q
venv/bin/pip install pre-commit -q
echo "repos:
-   repo: https://github.com/prettier/prettier
    rev: 1.13.4
    hooks:
    -   id: prettier
        name: prettier
        types: ['markdown']" > .pre-commit-config.yaml
echo "bleep bloop" > README.md
venv/bin/pre-commit install -f --install-hooks
venv/bin/pre-commit run prettier --files README.md
```

This produces the following error:
```
╔═ markl@dev21-uswest1cdevc: /tmp/tmp.FOLsd7AHcz git:(master) ✗
╚═ ♪ venv/bin/pre-commit run prettier --files README.md
prettier.................................................................Failed
hookid: prettier

/nail/home/markl/.cache/pre-commit/repoowychjtg/node_modules/find-parent-dir/index.js:10
  var parts = path.split(/(\/|\\)/);
                   ^

TypeError: Cannot read property 'split' of null
    at splitPath (/nail/home/markl/.cache/pre-commit/repoowychjtg/node_modules/find-parent-dir/index.js:10:20)
    at Object.exports.sync [as findParentDir] (/nail/home/markl/.cache/pre-commit/repoowychjtg/node_modules/find-parent-dir/index.js:44:18)
    at loadPlugins (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/common/load-plugins.js:21:36)
    at Object.getSupportInfo (/nail/home/markl/.cache/pre-commit/repoowychjtg/index.js:21:16)
    at updateContextOptions (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/util.js:883:35)
    at pushContextPlugins (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/util.js:916:3)
    at updateContextArgv (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/util.js:927:3)
    at Object.createContext (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/util.js:863:3)
    at Object.run (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/index.js:8:24)
    at Object.<anonymous> (/nail/home/markl/.cache/pre-commit/repoowychjtg/bin/prettier.js:5:23)
```

cc @asottile

**Comment by asottile** [comment]
Is prettier unhappy that it is cloned into a directory not named `prettier`? that seems like a pretty silly requirement to me 😆 -- perhaps someone from the prettier team can comment on this requirement and/or figure out if it can be lifted.  Seems like a strange pattern

**Comment by asottile** [comment]
Actually, seems pretty easy to fix, I might roll up my javascript sleeves and take a stab at it, unless @magicmark wants to have the first go :D

**Comment by ikatyang** [comment]
The reason why we're looking for the `prettier` directory is that we do bundling, the structure is different in development/production env, it's the easiest way to get where we are. We should figure out another way to achieve this goal.

https://github.com/prettier/prettier/blob/52a2a46b3c909320c738ef587095828dc20e21b0/src/common/load-plugins.js#L21-L24

**Comment by duailibe** [comment]
I think I can figure this out

**Comment by duailibe** [comment]
Unfortunately, our current test suite doesn't really test this :/

**Comment by adambrenecki** [comment]
FWIW, if anyone else has run into this problem and needs a quick workaround, this bug was introduced in 1.13.0, so setting `sha: 1.12.1` in your `.pre-commit-config.yaml` will work for now.

**Comment by asottile** [comment]
#4706 contains my attempt

**Comment by kompot** [comment]
Didn't fix this bug for me. Still getting

```
/Users/kompot/.cache/pre-commit/repo3197xm9a/node_modules/find-parent-dir/index.js:10
  var parts = path.split(/(\/|\\)/);
                   ^

TypeError: Cannot read property 'split' of null
    at splitPath (/Users/kompot/.cache/pre-commit/repo3197xm9a/node_modules/find-parent-dir/index.js:10:20)
    at Object.exports.sync [as findParentDir] (/Users/kompot/.cache/pre-commit/repo3197xm9a/node_modules/find-parent-dir/index.js:44:18)
    at loadPlugins (/Users/kompot/.cache/pre-commit/repo3197xm9a/src/common/load-plugins.js:21:36)
```

**Comment by beaugunderson** [comment]
If anyone needs a workaround you can make prettier a local hook for the time being:

```yaml
- repo: local
  hooks:
    - id: prettier
      name: prettier
      entry: prettier
      language: node
      types: [javascript]
      additional_dependencies: ["prettier@1.13.5"]
      exclude_types:
        - html
        - scss
```

**Comment by sloria** [comment]
I was getting this on 1.13.7 but it works for me when I use `rev: master`.
