### ISSUE TITLE
CLI cursor-offset option for vue file throws TypeError

### ISSUE THREAD

**Issue by jackysee** [prettier/prettier#4881]
**Environments:**
- Prettier Version: 1.13.7
- Running Prettier via: CLI
- Runtime: Node 10.6.0
- Operating System: Windows

**Steps to reproduce:**
https://github.com/jackysee/prettier_vue_cursor_bug
Run `npm run test3`  ( which runs `prettier index.vue --cursor-offset -1`)

**Expected behavior:**
It should print out the result, as in `npm run test2` ( which runs `prettier index.vue`), with the offset print out at last line.
```
<style>
</style>


<template>
<div> Hello </div>
</template>


<script>
export default {
  a() {
    return "1";
  }
};
</script>
0
```

**Actual behavior:**

It throws error:
```
C:\workspace\web\prettier_cursor_bug>npm run test3

> prettier_cursor_bug@1.0.0 test3 C:\workspace\web\prettier_cursor_bug
> prettier index.vue --cursor-offset -1

[error] index.vue: TypeError: options.locStart is not a function
[error]     at Object.findNodeAtOffset (C:\workspace\web\prettier_cursor_bug\node_modules\prettier\bin-prettier.js:10017:23)
[error]     at coreFormat (C:\workspace\web\prettier_cursor_bug\node_modules\prettier\bin-prettier.js:10203:32)
[error]     at format (C:\workspace\web\prettier_cursor_bug\node_modules\prettier\bin-prettier.js:10369:16)
[error]     at formatWithCursor (C:\workspace\web\prettier_cursor_bug\node_modules\prettier\bin-prettier.js:10381:12)
[error]     at Object.formatWithCursor (C:\workspace\web\prettier_cursor_bug\node_modules\prettier\bin-prettier.js:31224:15)
[error]     at format$1 (C:\workspace\web\prettier_cursor_bug\node_modules\prettier\bin-prettier.js:33227:21)
[error]     at C:\workspace\web\prettier_cursor_bug\node_modules\prettier\bin-prettier.js:33413:16
[error]     at C:\workspace\web\prettier_cursor_bug\node_modules\prettier\bin-prettier.js:33359:14
[error]     at Array.forEach (<anonymous>)
[error]     at eachFilename (C:\workspace\web\prettier_cursor_bug\node_modules\prettier\bin-prettier.js:33358:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! prettier_cursor_bug@1.0.0 test3: `prettier index.vue --cursor-offset -1`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the prettier_cursor_bug@1.0.0 test3 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I'm tracing this because sublime's JsPrettier is running this CLI and I found the cursor-offset option would have problem for `.vue` file.

**Comment by jackysee** [comment]
duplicate of #4867

**Comment by j-f1** [comment]
Duplicate of #4867
