### ISSUE TITLE
<span property="url">https://www.lol.com</span> breaks typescript parser

### ISSUE THREAD

**Issue by jsphweid** [prettier/prettier#4966]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpQf77VwzrUo+ADwBnAA4BDIWBKTRogHKSAtnAC8bEAAscdOFvzjqEcXGowAnppDj0AIxI5R284atmIqG9pgxxSAD0gaJgriqSAHQ0AOaBAPLUMdI4AF6SuNBaAHxc3PncYlJCxqbmVjYCJDm+-qJBgQDuzZHkJJGQKsIhxbmcMGwDMN0S0n0cAL4gADQgpplQosigktQmjQAKqwhLKJIAbhB6MyD21JJgANZ8AMpSYDhQMcgw1Ohws4+i5RvnMRHIVCSEjfWYAK1EAA8AELnK63VRwAAyjzggOBoNsq2+1GQIA8cFC1Bw4hgJ2MjxgFD0MG0yAAHAAGWalb4Uc7iPHGQnmfZo2a8ACO6BwvF+kn+knRII+IG+KhwLzestEjxiJDgAEV0BB4NLMTBJPZqXRacgAEyzV6SHBOJ4AYQgKgBKCg0H5IHQ3wAKkbdkCZRMJkA)
```sh
# Options (if any):
--parser typescript
```

**Input:**
```jsx
function HelloWorld() {

  return <span className="hide" property="publisher" typeof="http://schema.org/Organization">
        <span property="url">https://www.lol.com</span>
			</span>

}
```

**Output:**
```
Error: Comment location overlaps with node location
    at decorateComment (https://prettier.io/lib/standalone.js:9827:11)
    at decorateComment (https://prettier.io/lib/standalone.js:9801:7)
    at decorateComment (https://prettier.io/lib/standalone.js:9801:7)
    at decorateComment (https://prettier.io/lib/standalone.js:9801:7)
    at decorateComment (https://prettier.io/lib/standalone.js:9801:7)
    at decorateComment (https://prettier.io/lib/standalone.js:9801:7)
    at https://prettier.io/lib/standalone.js:9868:5
    at Array.forEach (<anonymous>)
    at Object.attach (https://prettier.io/lib/standalone.js:9862:12)
    at attachComments (https://prettier.io/lib/standalone.js:10683:14)
```

**Expected behavior:**
It should not blow up. I has to do with the double `//`

**Comment by jsphweid** [comment]
Actually, my apologies, but this is already known. #3346
