### ISSUE TITLE
[VueJS] [bug] Breaking a v-model string raises error on Webpack

### ISSUE THREAD

**Issue by antonioribeiro** [prettier/prettier#5384]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQVmoAmAlgG4nmUs0Nlj4DOXAvMSABOEAO5kAVgFcuMWgDMAngFpIsBDBXq4ggUxb7Kbeh258BkHEoAcu0gfuG5EQRj0P3FIybw9+Q0bbMHsFUdMacPmbgEJYAjABMZBgARkoAzIEhWYZ4WFhKXHA4cGAwdtkVFFB4GHB+kRBgtARw1AD6XJLJcPTqbbTUAuWV2fjdOH4Ayl096hBkAII8jc3UEENBIyH0ShgQ1EV+nckAor2wXAB0Ti7XtEXUVw1NLe3Hs7D9gyDDW8FIgjgAEdJLRAdQ-DBBJI4Bs-lkkDcMH4kXD4f8inBahc-Ah6GDoNiYJcYHhksUrsc2h8YFw0ej9IRUAB6XL5QrFUpuBkssLcka8hj8kIspHC+yCxi-VjMvm-SVMFmYXAtJggAA0IAgWFk0C4yFAeEEwhEAAUjQh9Sg8PQIAMNSBkoI8GAANZwGCTLAu2hQADmyChMM1AAsYBgcAB1EO0eBcb1gOCTS2xhixhTIcA8B2+wqCGCm51+jB4ZByPA4Qqa8RcAAeACFnW6PZManAADK+uBlitVkA12uTX1+4oARUkEHgPcrcE13sEecz9BhDqwgl9MEjAxgIeQVgADHPhIVI86sJm13A870HYCQWC4IW8MXS4je7OQIUMLRA9CP1xhzHCcpzfGdNVJZIt2oHdkAAFnA51aBwYcAGEIAwEtMygaBu01aQ4AAFTJK1yxnABfMigA)
```sh
# Options (if any):
tabWidth: 4
semi: false
singleQuote: true
```

**Input:**
```jsx
v-model="subEvents.form.fields.associated_subevent_id"
```

**Output:**
```jsx
v-model="
    subEvents.form.fields.associated_subevent_id
"
```

Raises the following error when compiling:

````
ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-5fe8fece","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./resources/js/views/SubEventsForm.vue
Module build failed: SyntaxError: Unterminated string constant (3:126)
    at Parser.pp$4.raise (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:2610:13)
    at Parser.pp$8.readString (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:3436:35)
    at Parser.pp$8.getTokenFromCode (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:3220:17)
    at Parser.pp$8.readToken (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:2975:15)
    at Parser.readToken (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:4398:22)
    at Parser.pp$8.nextToken (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:2966:15)
    at Parser.pp$8.next (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:2923:8)
    at Parser.pp.eat (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:569:10)
    at Parser.pp$3.parsePropertyValue (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:2309:12)
    at Parser.parseObj (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:4472:14)
    at Parser.pp$3.parseExprAtom (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:2077:17)
    at Parser.parseExprAtom (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:4372:24)
    at Parser.pp$3.parseExprSubscripts (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1932:17)
    at Parser.pp$3.parseExprOps (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1832:19)
    at Parser.pp$3.parsePropertyValue (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:2310:87)
    at Parser.parseObj (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:4472:14)
    at Parser.pp$3.parseExprAtom (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:2077:17)
    at Parser.parseExprAtom (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:4372:24)
    at Parser.pp$3.parseExprSubscripts (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1932:17)
    at Parser.pp$3.parseExprOps (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1832:19)
    at Parser.pp$3.parseExprList (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:2528:20)
    at Parser.pp$3.parseSubscripts (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1983:29)
    at Parser.pp$3.parseExprSubscripts (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1958:21)
    at Parser.pp$3.parseMaybeUnary (/Users/antoniocarlos/code/alerj/eventos/node_modules/vue-template-es2015-compiler/buble.js:1932:17)
 @ ./resources/js/views/SubEventsForm.vue 10:23-263
 @ ./resources/js/routes.js
 @ ./resources/js/pages/app.js
 @ ./resources/js/pages/boostrap.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
```

**Comment by ikatyang** [comment]
I tried it on the [Official Vue Template Explorer](https://template-explorer.vuejs.org/#%0A%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22row%20justify-content-center%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22col-8%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cform%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22col-12%20mb-3%22%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Capp-select%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3D%22associated_subevent_id%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20label%3D%22Subevento%20Associado%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20v-model%3D%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20subEvents.form.fields.associated_subevent_id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Arequired%3D%22true%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Aform%3D%22form%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Aelements%3D%22environment.tables.sub_events%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3E%3C%2Fapp-select%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fform%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E) and it did not throw errors. It looks like a bug in your loader.

**Comment by antonioribeiro** [comment]
The problem, probably, is that there's a whole pletora of packages related to Laravel Mix which are not allowing npm to install a newer version of vue-loader, so we are kind of stuck with ^13.7.3. Tried yesterday to upgrade to ^15, but Webpack wasn't able to compile my app no more, got many other errors, entered the rabbit hole to try to find them with newer Babel plugins but aborted after a few hours looking after the correct setup.

Not sure of @JeffreyWay would/could help us on this one.

**Comment by antonioribeiro** [comment]
Upgraded to 

laravel-mix@4.0.5
webpack@4.27.1
vue-loader@15.4.2

But still being haunted by this thing:

https://github.com/vuejs/vue-loader/issues/1453

**Comment by antonioribeiro** [comment]
Fixed by vue@2.5.21
