### ISSUE TITLE
AngularJS: one-time binding syntax

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#5466]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgDpQAR7DB5JIBuAtgHQCuAznAE54C+LuqA9FiADQgR0MAJbQ6yUAENGjCAHcACtITiUkshGEATPiABGjSWADWcGAGV0R4VADmyGIxpx+ACxgUANgHVXw+HRWYHDmKv7CZP4AnsjgdOL8NgyMMAqGthSSyABmkp4M-ABWdAAeAEKGJmbmkhRwADI2cDl5BSDFJeY2tp5wAIo0EPAt+S4gVozJsZJ2NJ7SuuiMNjDe2jCuyAAcAAz8SxAM3obosUtwyWTN-IxwAI40wrdpkhlZSLmj-AwUwg5OYzo3V6AyGzQ+rTGMEkejWWg2yAATPxHJJhJ5ugBhCAUTKxKDQa4gehwAAqMNUnwYbCAA)
```sh
--parser angular
```

**Input:**
```html
<p>
  {{ ::vm.user }}
</p>
```

**Output:**
```html
SyntaxError: Unexpected token :
    at o (https://prettier.io/lib/parser-angular.js:1:43175)
    at t.parseNgInterpolation (https://prettier.io/lib/parser-angular.js:1:44299)
    at n (https://prettier.io/lib/parser-angular.js:1:54796)
    at Object.t.parseInterpolation (https://prettier.io/lib/parser-angular.js:1:55134)
    at https://prettier.io/lib/parser-angular.js:1:55771
    at Object.parse (https://prettier.io/lib/parser-angular.js:1:55427)
    at Object.parse$2 [as parse] (https://prettier.io/lib/standalone.js:12931:19)
    at textToDoc (https://prettier.io/lib/standalone.js:15724:23)
    at https://prettier.io/lib/standalone.js:15712:14
    at Object.embed$2 [as embed] (https://prettier.io/lib/standalone.js:20444:55)
```

**Expected behavior:**

No error.

Notice that AngularJS and Angular aren't the same framework. The one with JS is an older incompatible version. However, their expression syntaxes seem to be mostly compatible except for this one-time binding thing. Docs: https://docs.angularjs.org/guide/expression#one-time-binding

**Comment by ikatyang** [comment]
Note that syntax errors won't be produced in child languages, this is a bug in our playground. Unknown syntax will be preserved if you're using CLI.

Supporting a new syntax isn't that simple enough, we need a parser for it (something like [angular-estree-parser](https://github.com/ikatyang/angular-estree-parser) but for angular.js) since we don't know what's the difference between them, they look the same but we're not sure, especially for edge cases.

And also I'm not sure if we should support angular.js, is it still developing not maintenance-only?

**Comment by icopp** [comment]
AngularJS syntax is basically `{{ variable interpolation }}` plus `<custom-elements></custom-elements>` and also `<div app-custom-attributes></div>`. It doesn't actually share much with Angular 2+, and unlike Angular 2+, it is and must be valid HTML pre-parsing, because the parser actually works by injecting the template contents into the page and *then* parsing it (as gross as that sounds).

Edge cases to watch out for when handling Angular 1

- One-time binding with complicated expressions: `{{ ::(a ? b : c) }}`
- Filters with complicated expressions: `{{ expression | filter:argument1:argument2 }}`

**Comment by thorn0** [comment]
AngularJS is indeed maintenance-only. But it used to be super popular, so there is a lot of code bases that still use it and aren't going to migrate to Angular as the migration is pretty expensive. Prettier can make their maintenance more pleasant.

This `::` syntax is the only thing that exists in the expression syntax of AngularJS, but doesn't exist in Angular. It can be used only at the beginning of an expression, so this syntax can be viewed as external to expressions, not as part of them, which should simplify greatly adding support for it.

Anyways, if you're saying it's just a playground bug that doesn't manifest itself anyhow else, then it's more than okay to leave everything as is. The Angular parser already works great for AngularJS templates.

**Comment by thorn0** [comment]
Ideally, it'd be nice to format expressions in known attributes like `ng-if` and `ng-class`. But unlike Angular, in AngularJS, in the general case, looking at an attribute, we can't tell whether its content is an expression. That's what makes static analysis of AngularJS templates futile.

**Comment by thorn0** [comment]
@icopp The syntax for filters/pipes is the same in AngularJS and Angular. Please prove me wrong if I am.

**Comment by fisker** [comment]
I'm going to close this since there has been no action for many years.

> Note that syntax errors won't be produced in child languages, this is a bug in our playground. Unknown syntax will be preserved if you're using CLI.

Fixed.
