### ISSUE TITLE
Error: 'arguments' is not allowed in class field initializer

### ISSUE THREAD

**Issue by 0xdevalias** [prettier/prettier#5744]
Was trying to bump some eslint/prettier related dependencies in a project, and hit this strange issue:

```
Running: yarn run eslint --format checkstyle --output-file artifacts/eslint.xml
--
  | yarn run v1.12.3
  | $ eslint '{app,spec}/**/*.js' --format checkstyle --output-file artifacts/eslint.xml
  | 'arguments' is not allowed in class field initializer (54:17)
  | 52 \|
  | 53 \|   onChange = ({ value }) => {
  | > 54 \|     console.log(arguments)
  | \|                 ^
  | 55 \|     if (this.state.role === value) {
  | 56 \|       return
  | 57 \|     }
  | SyntaxError: 'arguments' is not allowed in class field initializer (54:17)
  | 52 \|
  | 53 \|   onChange = ({ value }) => {
  | > 54 \|     console.log(arguments)
  | \|                 ^
  | 55 \|     if (this.state.role === value) {
  | 56 \|       return
  | 57 \|     }
  | at t (/usr/src/app/node_modules/prettier/parser-babylon.js:1:326)
  | at Object.parse (/usr/src/app/node_modules/prettier/parser-babylon.js:1:195891)
  | at Object.parse$2 [as parse] (/usr/src/app/node_modules/prettier/index.js:10600:19)
  | at coreFormat (/usr/src/app/node_modules/prettier/index.js:13763:23)
  | at format (/usr/src/app/node_modules/prettier/index.js:13939:16)
  | at formatWithCursor (/usr/src/app/node_modules/prettier/index.js:13951:12)
  | at /usr/src/app/node_modules/prettier/index.js:41967:15
  | at Object.format (/usr/src/app/node_modules/prettier/index.js:41986:12)
  | at Program (/usr/src/app/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:461:45)
  | at listeners.(anonymous function).forEach.listener (/usr/src/app/node_modules/eslint/lib/util/safe-emitter.js:47:58)
  | error Command failed with exit code 1.
```

The error itself seems as though it may come from node itself..?
* https://github.com/nodejs/node/blob/master/deps/v8/src/messages.h#L275-L276

Cutdown `package.json`:
```
    "prettier": "^1.15.0",

    "eslint": "^4.19.1",
    "eslint-config-prettier": "^3.3.0",
    "eslint-config-standard": ">= 11.0.0 < 12.0.0",
    "eslint-config-standard-react": ">= 7.0.0 < 7.0.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^8.0.1",
    "eslint-plugin-prettier": ">= 2.7.0 < 3.0.0",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-react": "^7.12.0",
    "eslint-plugin-standard": ">= 3.1.0 < 4.0.0",

    "babel-cli": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-polyfill": "^6.16.0",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
```

I'm wondering if this is a version mismatch/similar.. we aren't moving to babel v7 yet.. We were previously using the following with no issues:

```
"eslint-config-prettier": "^2.6.0",
"eslint-plugin-prettier": "^2.3.1",
"prettier": "1.7.0"
```

**Comment by 0xdevalias** [comment]
Disregard.. this seems to be in my code and I read the stacktrace poorly.
