### ISSUE TITLE
Unsafe Eval Causing Problems in Prettier-Atom After 1.17

### ISSUE THREAD

**Issue by robwise** [prettier/prettier#6053]
**Environments:**
- Prettier Version: 1.17.0
- Running Prettier via: prettier-atom
- Runtime: Node

**Steps to reproduce:**
Use Prettier version 1.17.0 with prettier-atom inside of Atom.

**Expected behavior:**
No errors.

**Actual behavior:**
```
At /home/vista/.atom/packages/prettier-atom/node_modules/prettier/index.js:40036

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at /packages/prettier-atom/node_modules/prettier/index.js:40036:21
    at createCommonjsModule (/packages/prettier-atom/node_modules/prettier/index.js:192:35)
    at /packages/prettier-atom/node_modules/prettier/index.js:39843:18)
    at /packages/prettier-atom/node_modules/prettier/index.js:41849:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/prettier-atom/dist/helpers/getPrettierInstance.js:4:25)
    at /packages/prettier-atom/dist/helpers/getPrettierInstance.js:20:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/prettier-atom/dist/helpers/index.js:9:29)
    at /packages/prettier-atom/dist/helpers/index.js:20:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/prettier-atom/dist/statusTile/updateStatusTileScope.js:3:56)
```

We are seeing errors getting thrown by Atom because it's detecting an unsafe use of eval (it's a security feature of Atom that it checks for unsafe eval in its plugins and I can't turn it off from prettier-atom).

These all of the sudden started happening around the time 1.17 dropped (April 12). I haven't changed anything on the prettier-atom repo and other Atom plugins using Prettier report the same stack trace all of the sudden appearing.

Here is the issue on prettier-atom we are using to track this:
https://github.com/prettier/prettier-atom/issues/493

I think this could be the problem line, but I'm not sure: https://github.com/prettier/prettier/pull/5963/files#diff-d566515bb6fb446710493e62794f89e8R21

As stated in the prettier-atom issue I linked, this has happened before:

- prettier/prettier#1895
- prettier/prettier#4764

I thought since this was a different occurrence you would prefer I make a new issue, but sorry if I should have appended to one of those.

**Comment by j-f1** [comment]
Looks like it’s an issue with our TOML parser, which runs this:

```js
eval(`require('util').inspect`)
```
