### ISSUE TITLE
TypeError: Cannot read property 'start' of null

### ISSUE THREAD

**Issue by solderjs** [prettier/prettier#6167]
**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgGIQgAlQEN8ALAJzgDMBeAHRFJhnQGckB6DuADyIFt0AGzgA6SPwaYAQkXKoORTHShCIlfvgCWbAK6SoKjJgAmENeXystMfALgwVIADQgI6GFuitkoOeQgAdwAFOQQfFCIANwgtExcQACNyIjAAawcAZXRUrSgAc2QYcl04VyZ+IQB1Uhs4VhywOEzwmy0omwBPZHBWH1c81jhyGGCU-P4iZCoiISHXACtWHmkU9Kz7ABk8uGnZ+ZAlnky8-JEARV0IeD25spAc8iHyHoqhBPRyPJgquJhSZAADgADK5PhAhlUUugep96sMortXABHK7wMbuCIgIisAC0UDgcBMRISlFRWkoYyIEymSBmd1cQ34WiKJXu1gKFzRuzp+3uMCIiV+Jn+yAATK5ikQtEJTgBhCD8SY9KDQJEgXRDAAqgoi9KGAF8DUA)
```sh
--parser html
```

**Input:**
```html
<p>Foo <a href="https://example.com">Bar</a>
lorem ipsum

<p>dolor sit amet

```

**Output:**
```html
hasTrailingLineBreak@https://prettier.io/lib/standalone.js:19373:3
hasSurroundingLineBreak@https://prettier.io/lib/standalone.js:19365:39
preferHardlineAsLeadingSpaces$1@https://prettier.io/lib/standalone.js:19357:111
printBetweenLine@https://prettier.io/lib/standalone.js:20920:153
printChildren/<@https://prettier.io/lib/standalone.js:20843:44
map@https://prettier.io/lib/standalone.js:15752:21
printChildren@https://prettier.io/lib/standalone.js:20819:24
genericPrint$2@https://prettier.io/lib/standalone.js:20738:237
callPluginPrintFunction@https://prettier.io/lib/standalone.js:15898:18
printGenerically/res<@https://prettier.io/lib/standalone.js:15849:16
printComments@https://prettier.io/lib/standalone.js:15572:17
printGenerically@https://prettier.io/lib/standalone.js:15848:22
printChild@https://prettier.io/lib/standalone.js:20891:12
printChildren/<@https://prettier.io/lib/standalone.js:20875:102
map@https://prettier.io/lib/standalone.js:15752:21
printChildren@https://prettier.io/lib/standalone.js:20819:24
genericPrint$2@https://prettier.io/lib/standalone.js:20703:39
callPluginPrintFunction@https://prettier.io/lib/standalone.js:15898:18
printGenerically/res<@https://prettier.io/lib/standalone.js:15849:16
printComments@https://prettier.io/lib/standalone.js:15572:17
printGenerically@https://prettier.io/lib/standalone.js:15848:22
printAstToDoc@https://prettier.io/lib/standalone.js:15860:16
coreFormat@https://prettier.io/lib/standalone.js:16179:16
format@https://prettier.io/lib/standalone.js:16426:73
formatWithCursor@https://prettier.io/lib/standalone.js:16442:12
withPlugins/<@https://prettier.io/lib/standalone.js:30808:15
format@https://prettier.io/lib/standalone.js:30816:12
formatCode@https://prettier.io/worker.js:234:21
handleMessage@https://prettier.io/worker.js:185:18
self.onmessage@https://prettier.io/worker.js:155:14
```

**CLI Output:**
```
dummy.html[error] dummy.html: TypeError: Cannot read property 'start' of null
[error]     at hasTrailingLineBreak (/Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:32793:167)
[error]     at hasSurroundingLineBreak (/Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:32785:39)
[error]     at preferHardlineAsLeadingSpaces$1 (/Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:32777:111)
[error]     at printBetweenLine (/Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:34341:153)
[error]     at /Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:34264:44
[error]     at FastPath.map (/Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:13430:21)
[error]     at printChildren$1 (/Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:34240:28)
[error]     at Object.genericPrint$5 [as print] (/Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:34159:237)
[error]     at callPluginPrintFunction (/Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:13576:18)
[error]     at /Users/aj/.local/opt/node-v10.13.0/lib/node_modules/prettier/bin-prettier.js:13527:16
```

**Expected behavior:**

Not to crash, but to format the code.

If I put it in just ever so slightly differently (no newlines or spaces), I get what I expect:

Input without newlines or spaces after the paragraph block:
```
<p>Foo <a href="https://example.com">Bar</a>
lorem ipsum<p>dolor sit amet
```

Output as expected:
```
<p>Foo <a href="https://example.com">Bar</a> lorem ipsum</p>
<p>dolor sit amet</p>
```

**Comment by adityachugh** [comment]
Were you able to overcome this issue? I still seem to be having it with `1.19.1` when trying to format my TypeScript files

**Comment by k3it** [comment]
same issue here with 1.19.1.  I can't tell the line number prettier stumbles at (don't think it's just the <p> tag).  To get around this I have to remove all line breaks from the html code, then let prettier reformat it.

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/7293
