### ISSUE TITLE
Prettier produces an error when finishes executing

### ISSUE THREAD

**Issue by Aiivaras** [prettier/prettier#6321]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: npm
- Runtime:
  - Node: v12.4.0
  - npm: 6.9.0

- Operating System: Windows 10 (WSL: Ubuntu 18.04 LTS)

**Steps to reproduce:**
 - `npm install prettier`
 - Add the following command to the package.json: `"check": "prettier --config ./.prettierrc --list-different \"src/*.ts\""`
 - `npm run check`

**Expected behavior:**
Executes without errors

**Actual behavior:**
```
user@ADMINRG-RJNI5OC:/mnt/d/Development/test$ npm run check

> test@0.1.0 check /mnt/d/Development/test
> prettier --config ./.prettierrc --list-different "src/*.ts"

src/serviceWorker.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 check: `prettier --config ./.prettierrc --list-different "src/*.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-07-21T11_10_45_926Z-debug.log
user@ADMINRG-RJNI5OC:/mnt/d/Development/test$

```
Log file output:
```
user@ADMINRG-RJNI5OC:/mnt/d/Development/test$ cat /home/user/.npm/_logs/2019-07-21T11_11_43_748Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/user/.nvm/versions/node/v12.4.0/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v12.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'check'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.4.0
4 verbose run-script [ 'precheck', 'check', 'postcheck' ]
5 info lifecycle test@0.1.0~precheck: test@0.1.0
6 info lifecycle test@0.1.0~check: test@0.1.0
7 verbose lifecycle test@0.1.0~check: unsafe-perm in lifecycle true
8 verbose lifecycle test@0.1.0~check: PATH: /home/user/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/d/Development/test/node_modules/.bin:/home/user/.nvm/versions/node/v12.4.0/bin:/usr/local/sbin:/us
r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/d/Development/test/node_modules/.bin:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath_target_835156765:/mnt/c/ProgramData/Oracle/Java/javapath_target_274181078:/mnt/
c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Skype/Phone:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/
mnt/c/Program Files/nodejs:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Windows/System32/dns/bin:/mnt/c/Users/user/AppData/Roaming/npm:/mnt/c/Users/skilli
t/AppData/Local/hyper/app-2.0.0/resources/bin:/snap/bin:/home/user/mvn/apache-maven-3.6.1/bin:/home/user/java/jdk-11.0.4/bin
9 verbose lifecycle test@0.1.0~check: CWD: /mnt/d/Development/test
10 silly lifecycle test@0.1.0~check: Args: [ '-c', 'prettier --config ./.prettierrc --list-different "src/*.ts"' ]
11 silly lifecycle test@0.1.0~check: Returned: code: 1  signal: null
12 info lifecycle test@0.1.0~check: Failed to exec check script
13 verbose stack Error: test@0.1.0 check: `prettier --config ./.prettierrc --list-different "src/*.ts"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid test@0.1.0
15 verbose cwd /mnt/d/Development/test
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/home/user/.nvm/versions/node/v12.4.0/bin/node" "/home/user/.nvm/versions/node/v12.4.0/bin/npm" "run" "check"
18 verbose node v12.4.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error test@0.1.0 check: `prettier --config ./.prettierrc --list-different "src/*.ts"`
22 error Exit status 1
23 error Failed at the test@0.1.0 check script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
user@ADMINRG-RJNI5OC:/mnt/d/Development/test$

```

**Comment by lydell** [comment]
Hi! As far as I can tell, everything works as expected here. `src/serviceWorker.ts` does not seem to be formatted with Prettier, so the check fails.

I recommend running `prettier --check "src/**/*.ts"` instead – it gives more human friendly output.

**Comment by Aiivaras** [comment]
Hi @lydell,
Thank you for the recommendation. Still getting error from npm.

Everything looks fine when I run the command via cmd so I did more digging and found out that the command returns `exit code 1`.

Behavior:
```
user@ADMINRG-RJNI5OC:/mnt/d/Development/test$ prettier --config ./.prettierrc --list-different "src/*.ts"
src/serviceWorker.ts
user@ADMINRG-RJNI5OC:/mnt/d/Development/test$ echo $?
1
``` 

Is this expected behavior?

**Comment by lydell** [comment]
It is! When running via `npm run`, npm adds a lot of noisy extra messages when commands exit with a non-zero code.

**Comment by Aiivaras** [comment]
Ah.. Okay. Thank you for your time.
