### ISSUE TITLE
Question: Checked out tag 1.18.2 is failing several tests

### ISSUE THREAD

**Issue by Xotic750** [prettier/prettier#6407]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: npm run test
- Runtime: node 8, 10 and 12
- Operating System: macOS

**Steps to reproduce:**
clone the repo
checkout tag 1.18.2
npm install
build
test

**Expected behavior:**
All tests would pass
**Actual behavior:**
Several tests fail

```
Summary of all failing tests
 FAIL  tests/handlebars/jsfmt.spec.js
  ● basic-handlebars.hbs

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "basic-handlebars.hbs 1".

    - Snapshot
    + Received

    @@ -16,14 +16,14 @@
      
      =====================================output=====================================
      <script id="entry-template" type="text/x-handlebars-template">
        <div class="entry">
          <h1>
    -       {{title}}
    -     </h1>
    +   {{title}}
    +   </h1>
          <div class="body">
    -       {{body}}
    -     </div>
    +   {{body}}
        </div>
    +   </div>
      </script>
      <div class="{{hello}} {{world}}"></div>
      ================================================================================

      88 |           )
      89 |         )
    > 90 |       ).toMatchSnapshot();
         |         ^
      91 |     });
      92 | 
      93 |     for (const parser of parsers.slice(1)) {

      at Object.test (tests_config/run_spec.js:90:9)

 FAIL  tests_integration/__tests__/loglevel.js
  ● do not show warnings with --loglevel error

    expect(received).toMatch(expected)

    Expected value to match:
      "[error]"
    Received:
      "[error] No matching files. Patterns tried: not-found.js !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
    "

      43 |   if (patterns) {
      44 |     patterns.forEach(pattern => {
    > 45 |       expect(result.stderr).toMatch(pattern);
         |                             ^
      46 |     });
      47 |   } else {
      48 |     expect(result.stderr).toMatch(/^\s*$/);

      at patterns.forEach.pattern (tests_integration/__tests__/loglevel.js:45:29)
          at Array.forEach (<anonymous>)
      at runPrettierWithLogLevel (tests_integration/__tests__/loglevel.js:44:14)
      at Object.<anonymous>.test (tests_integration/__tests__/loglevel.js:10:3)

  ● show errors and warnings with --loglevel warn

    expect(received).toMatch(expected)

    Expected value to match:
      "[error]"
    Received:
      "[warn] Ignored unknown option --unknown-option.
    [error] No matching files. Patterns tried: not-found.js !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
    "

      43 |   if (patterns) {
      44 |     patterns.forEach(pattern => {
    > 45 |       expect(result.stderr).toMatch(pattern);
         |                             ^
      46 |     });
      47 |   } else {
      48 |     expect(result.stderr).toMatch(/^\s*$/);

      at patterns.forEach.pattern (tests_integration/__tests__/loglevel.js:45:29)
          at Array.forEach (<anonymous>)
      at runPrettierWithLogLevel (tests_integration/__tests__/loglevel.js:44:14)
      at Object.<anonymous>.test (tests_integration/__tests__/loglevel.js:14:3)

  ● show all logs with --loglevel debug

    expect(received).toMatch(expected)

    Expected value to match:
      "[error]"
    Received:
      "[warn] Ignored unknown option --unknown-option.
    [debug] normalized argv: {\"_\":[\"not-found.js\"],\"color\":true,\"editorconfig\":true,\"loglevel\":\"debug\",\"parser\":\"unknown-parser\",\"plugin-search-dir\":[],\"plugin\":[],\"ignore-path\":\".prettierignore\",\"debug-repeat\":0,\"config-precedence\":\"cli-override\"}
    [error] No matching files. Patterns tried: not-found.js !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
    "

      43 |   if (patterns) {
      44 |     patterns.forEach(pattern => {
    > 45 |       expect(result.stderr).toMatch(pattern);
         |                             ^
      46 |     });
      47 |   } else {
      48 |     expect(result.stderr).toMatch(/^\s*$/);

      at patterns.forEach.pattern (tests_integration/__tests__/loglevel.js:45:29)
          at Array.forEach (<anonymous>)
      at runPrettierWithLogLevel (tests_integration/__tests__/loglevel.js:44:14)
      at Object.<anonymous>.test (tests_integration/__tests__/loglevel.js:18:3)


Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `npm test -- -u` to update them.

Test Suites: 2 failed, 922 passed, 924 total
Tests:       4 failed, 6007 passed, 6011 total
Snapshots:   1 failed, 4739 passed, 4740 total
Time:        75.418s
Ran all test suites.
```

I want to ask if this is a problem with my environment, or do they actually fail?

**Comment by evilebottnawi** [comment]
Can't reproduce, look problem in env, maybe you use old deps?

**Comment by Xotic750** [comment]
```
GRAHAMS-MBP:.private grahamfairweather$ uname -a
Darwin GRAHAMS-MBP.bahnhof.se 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
GRAHAMS-MBP:p.private grahamfairweather$ git --version
git version 2.18.0
GRAHAMS-MBP:.private grahamfairweather$ node --version
v8.11.4
GRAHAMS-MBP:.private grahamfairweather$ npm --version
6.10.1
GRAHAMS-MBP:.private grahamfairweather$ git clone https://github.com/prettier/prettier.git prettier-fresh
Cloning into 'prettier-fresh'...
remote: Enumerating objects: 54801, done.
remote: Total 54801 (delta 0), reused 0 (delta 0), pack-reused 54801
Receiving objects: 100% (54801/54801), 29.24 MiB | 4.26 MiB/s, done.
Resolving deltas: 100% (26002/26002), done.
Checking out files: 100% (5831/5831), done.
GRAHAMS-MBP:.private grahamfairweather$ cd prettier-fresh/
GRAHAMS-MBP:prettier-fresh grahamfairweather$ git checkout 1.18.2
Note: checking out '1.18.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f7fb04b0 Release 1.18.2
GRAHAMS-MBP:prettier-fresh grahamfairweather$ npm install

> fsevents@1.2.9 install /Users/grahamfairweather/.private/prettier-fresh/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/grahamfairweather/.private/prettier-fresh/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" is installed via remote

> core-js@2.6.9 postinstall /Users/grahamfairweather/.private/prettier-fresh/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/grahamfairweather/.private/prettier-fresh/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
added 1175 packages from 578 contributors and audited 26072 packages in 65.113s
found 65 vulnerabilities (63 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
GRAHAMS-MBP:prettier-fresh grahamfairweather$ npm run build

> prettier@1.18.2 build /Users/grahamfairweather/.private/prettier-fresh
> node --max-old-space-size=2048 ./scripts/build/build.js

 Building packages
index.js................................................................  DONE
doc.js..................................................................  DONE
standalone.js...........................................................  DONE
bin-prettier.js.........................................................  DONE
third-party.js..........................................................  DONE
parser-babylon.js.......................................................  DONE
parser-flow.js..........................................................  DONE
parser-typescript.js....................................................  DONE
parser-angular.js.......................................................  DONE
parser-postcss.js.......................................................  DONE
parser-graphql.js.......................................................  DONE
parser-markdown.js......................................................  DONE
parser-glimmer.js.......................................................  DONE
parser-html.js..........................................................  DONE
parser-yaml.js..........................................................  DONE
GRAHAMS-MBP:prettier-fresh grahamfairweather$ npm run test
...
Summary of all failing tests
 FAIL  tests/handlebars/jsfmt.spec.js
  ● basic-handlebars.hbs

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "basic-handlebars.hbs 1".

    - Snapshot
    + Received

    @@ -16,14 +16,14 @@

      =====================================output=====================================
      <script id="entry-template" type="text/x-handlebars-template">
        <div class="entry">
          <h1>
    -       {{title}}
    -     </h1>
    +   {{title}}
    +   </h1>
          <div class="body">
    -       {{body}}
    -     </div>
    +   {{body}}
        </div>
    +   </div>
      </script>
      <div class="{{hello}} {{world}}"></div>
      ================================================================================

      88 |           )
      89 |         )
    > 90 |       ).toMatchSnapshot();
         |         ^
      91 |     });
      92 |
      93 |     for (const parser of parsers.slice(1)) {

      at Object.test (tests_config/run_spec.js:90:9)


Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `npm test -- -u` to update them.

Test Suites: 1 failed, 923 passed, 924 total
Tests:       1 failed, 6010 passed, 6011 total
Snapshots:   1 failed, 4739 passed, 4740 total
Time:        85.432s
```

So starting completely fresh reduced some of the fails, the error snapshots (perhaps something from building master earlier), but the handlebars test still fails.

**Comment by evilebottnawi** [comment]
Can't reproduce

**Comment by SimenB** [comment]
This repo uses `yarn`, not `npm` - test failures might occur due to some changed dependency when the lockfile is not respected

**Comment by Xotic750** [comment]
`yarn` does indeed make the difference. Well spotted! I also had to update to the latest version of `yarn` v1.17.3 as v1.15.2 that I had installed did not work with the project.

**Comment by evilebottnawi** [comment]
@Xotic750 can we close issue?

**Comment by Xotic750** [comment]
Sure! Thanks for the help.
