### ISSUE TITLE
[TypeScript 3.7] add support for nullish coalescing operator

### ISSUE THREAD

**Issue by RIP21** [prettier/prettier#6609]
**Prettier 1.18.2**

**Input:**
```jsx
const a = null
console.log(a ?? "keque")
```

**Output:**
```
[error] src/index.tsx: SyntaxError: Expression expected. (8:16)
[error]    6 | 
[error]    7 | const a = null
[error] >  8 | console.log(a ?? "keque")
[error]      |                ^
[error]    9 | 
```

**Expected behavior:**
Should understand or at least ignore such expression.

**Comment by RIP21** [comment]
This one comes along with Optional Chaining https://github.com/prettier/prettier/issues/6595. I wanted to be sure that this one is not overlooked.
Sure, TS 3.7 is still in beta, but having this supported before the official release will be awesome.

**Comment by vernondegoede** [comment]
I've updated Prettier to 1.19.0, but I'm still getting errors when formatting files containing nullish coalescing statements.

```
SyntaxError: Expression expected. (32:53)
  30 | 
  31 | const MethodIcon: React.FC<Props> = ({ method, size = "default" }) => {
> 32 |   const methodIcon = PAYMENT_METHOD_IMAGES[method] ?? require("assets/images/payment-methods/unknown.png");
     |                                                     ^
  33 |   const iconStyle =
  34 |     size === "large"
  35 |       ? [styles.methodImage, styles.methodImageLarge]
    at e (/Users/vernon/Sites/expo/mollie/node_modules/prettier/parser-typescript.js:1:267)
    at Object.parse (/Users/vernon/Sites/expo/mollie/node_modules/prettier/parser-typescript.js:1:2261711)
    at Object.parse$2 [as parse] (/Users/vernon/Sites/expo/mollie/node_modules/prettier/index.js:10629:19)
    at coreFormat (/Users/vernon/Sites/expo/mollie/node_modules/prettier/index.js:13888:23)
    at format (/Users/vernon/Sites/expo/mollie/node_modules/prettier/index.js:14146:73)
    at formatWithCursor (/Users/vernon/Sites/expo/mollie/node_modules/prettier/index.js:14162:12)
    at /Users/vernon/Sites/expo/mollie/node_modules/prettier/index.js:42756:15
    at Object.format (/Users/vernon/Sites/expo/mollie/node_modules/prettier/index.js:42775:12)
    at performFormat (/Users/vernon/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/192.7142.35/WebStorm.app/Contents/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:62:29)
    at PrettierPlugin.handleReformatCommand (/Users/vernon/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/192.7142.35/WebStorm.app/Contents/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:36:16)
Process finished with exit code -1
```

**Comment by lydell** [comment]
@vernondegoede Your example seems to work:

**Prettier 1.19.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBZOMAWEAJgJKRRKYBKcAhmDAHQBiAwgDwAKAThAA5oAfJgC8mABTBMAWzyEiAGkxoAlgC84ozAB0QROADNaAVwA2MXZgC+ASlHDg2qJheZyGGXOJloWzgEEATWwAUQA5ABUAfVCIgAkAeQARKJJsfwBxEIBlAG1ZAmIAXUwAflLMbjgAR2MVKvFdWjQ0PDQAehVpWgBzOA6+WgBPWVgAWgL5DuMoAGsoCAB3KEY+KB7dGwBuJytXfYPXEAUQfhgVdGRQWm5eRc4bhDRkEFoANwgVImOQACNueizPDZQZgFTrZAwbjGOAnfAwaSmADq+BU8DQoLg2SeaJUbzRQxeYBaP3BrW4MB4vW6yCMplaJwAVmgAB4AIQBYCBMGytFkABlwXBabR6bCQMyWdlwT1THAAIrGCDwEVik6Dbjkl4wIZ8fpgbgqPgwH58Q2wJFfAjIAAcAAZ1bxWkiAXwXmb+nBuG9hSdasq4Dx+M8UM0xlA4HB9N8TlVavVAwCejSkHSGSBWtIVJDoeLVOs5YqA6r0zBaL9LURrUgAEwnKG0FSmGWsCDSFMgBYRn7GVoRcshtPit4wkhQfSwbIGo0wfzj7I6uUluBWKxAA)
```sh
--parser typescript
```

**Input:**
```tsx
const MethodIcon: React.FC<Props> = ({ method, size = "default" }) => {
    const methodIcon = PAYMENT_METHOD_IMAGES[method] ?? require("assets/images/payment-methods/unknown.png");
}               
```

**Output:**
```tsx
const MethodIcon: React.FC<Props> = ({ method, size = "default" }) => {
  const methodIcon =
    PAYMENT_METHOD_IMAGES[method] ??
    require("assets/images/payment-methods/unknown.png");
};

```

Please open a new issue if you find a bug. First, triple-check that the Prettier that is running actually is the version you think it is.
