### ISSUE TITLE
Direct from github installs don’t work with the default .yarnclean

### ISSUE THREAD

**Issue by EdwardDrapkin** [prettier/prettier#6771]
Hey there, I'm trying to use prettier@next so my team can go ahead and start using the new 3.7 syntactical features.  I noticed the PR landed and the versions page says to run `yarn add prettier/prettier`, which is a direct from GH installation, and I did.  I'm getting this error:

```

    🕘 17:36:54 ⎦📘 ~/projects/payment-plugin-3 🌱 development (3/755) ⎡
 📒3147 💩 yarn lint:ts
yarn run v1.17.3
$ eslint modules --ext ts,tsx
Error: Cannot find module '../doc'
Require stack:
- /Users/edrapkin/projects/payment-plugin-3/node_modules/prettier/src/main/comments.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/prettier/src/main/core.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/prettier/src/index.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/prettier/index.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/eslint/lib/cli-engine/index.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/eslint/lib/cli.js
- /Users/edrapkin/projects/payment-plugin-3/node_modules/eslint/bin/eslint.js
Occurred while linting /Users/edrapkin/projects/payment-plugin-3/modules/common/src/TestUtils.tsx:1
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (/Users/edrapkin/projects/payment-plugin-3/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/edrapkin/projects/payment-plugin-3/node_modules/prettier/src/main/comments.js:12:5)
    at Module._compile (/Users/edrapkin/projects/payment-plugin-3/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brodybits** [comment]
Which Node.js version and which platform are you using?

This is no longer supported on Node.js 6.

**Comment by lydell** [comment]
@EdwardDrapkin Can you run `./node_modules/.bin/prettier some/file/in/your/project.js` and see it you get errors then too?

**Comment by iCrawl** [comment]
Yes it errors nonetheless.

```
E:\Coding\Projects\Naval-Base\yukikaze\src\bot [refactor/ts_37 ≡ +0 ~2 -0 !]> node -v
v12.11.1
E:\Coding\Projects\Naval-Base\yukikaze\src\bot [refactor/ts_37 ≡ +0 ~2 -0 !]> .\node_modules\.bin\prettier .\bot.ts
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module '../doc'
Require stack:
- E:\Coding\Projects\Naval-Base\yukikaze\node_modules\prettier\src\main\comments.js
- E:\Coding\Projects\Naval-Base\yukikaze\node_modules\prettier\src\main\core.js
- E:\Coding\Projects\Naval-Base\yukikaze\node_modules\prettier\src\index.js
- E:\Coding\Projects\Naval-Base\yukikaze\node_modules\prettier\index.js
- E:\Coding\Projects\Naval-Base\yukikaze\node_modules\prettier\src\cli\index.js
- E:\Coding\Projects\Naval-Base\yukikaze\node_modules\prettier\bin\prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\Coding\Projects\Naval-Base\yukikaze\node_modules\prettier\src\main\comments.js:12:5)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\Coding\\Projects\\Naval-Base\\yukikaze\\node_modules\\prettier\\src\\main\\comments.js',
    'E:\\Coding\\Projects\\Naval-Base\\yukikaze\\node_modules\\prettier\\src\\main\\core.js',
    'E:\\Coding\\Projects\\Naval-Base\\yukikaze\\node_modules\\prettier\\src\\index.js',
    'E:\\Coding\\Projects\\Naval-Base\\yukikaze\\node_modules\\prettier\\index.js',
    'E:\\Coding\\Projects\\Naval-Base\\yukikaze\\node_modules\\prettier\\src\\cli\\index.js',
    'E:\\Coding\\Projects\\Naval-Base\\yukikaze\\node_modules\\prettier\\bin\\prettier.js'
  ]
}
```

**Comment by thorn0** [comment]
Indeed, `doc` is among the default entries `yarn autoclean --init` generates. I guess better to rename this folder.

**Comment by fisker** [comment]
funny, how  about `document`

**Comment by EdwardDrapkin** [comment]
I was using Node 13, tried 12 as well, fwiw, but it seems that @iCrawl's analysis is likely the culprit.

**Comment by lydell** [comment]
So … I initially labeled this as “bug” but this has been the case since 2017-12-26 and nobody has noticed anything until now. And the yarn autoclean docs say:

> _Note: This command is considered for advanced use cases only._
>
> […]
>
> Autoclean functionality is **disabled** by default.
>
> It is **highly recommended** that you manually review the default entries in .yarnclean and customize them to fit your needs.

So this does sound more like a user error than an error on our side. On the other hand, if it’s easy to fix this on our side then why not 🤷‍♂

**Comment by EdwardDrapkin** [comment]
> So this does sound more like a user error than an error on our side. 

I don't believe there's any way to disable yarn autocleaning when there's a .yarnclean file present.

> When the .yarnclean file exists in a package, autoclean functionality will be enabled. The clean will be performed:

>    After an install
>    After an add
>    If yarn autoclean --force is run

I don't see anything in the docs to disable autocleaning a package on `yarn add` or `yarn install` from the users' side.
