### ISSUE TITLE
`yarn add` installs bad version

### ISSUE THREAD

**Issue by Skalman** [prettier/prettier#6915]
**Heads up:** I don't believe this is an actual Prettier bug. I've reported the same bug to yarnpkg/yarn#7681. But it affects Prettier so badly, that I thought that I'd report it here for others searching.

**Environments:**
- Prettier Version: 1.9.1, 1.9.0, 1.8.2, 1.8.1, 1.8.0, 1.7.3
- Running Prettier via: CLI 
- Runtime: Node.js 12, Yarn 1.19.1 
- Operating System: Ubuntu 18.04 

**Steps to reproduce:**

```sh
$ yarn add prettier@1.9.1 --dev
yarn add v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ prettier@1.9.1
info All dependencies
└─ prettier@1.9.1
Done in 12.77s.

# It says that it's the right version, but I think it's a very old version
$ node node_modules/.bin/prettier --version
1.9.1

$ ls node_modules/prettier/
bin/  index.js  package.json  parser-babylon.js  parser-flow.js  parser-graphql.js  parser-markdown.js  parser-parse5.js  parser-postcss.js  parser-typescript.js  README.md  third-party.js

$ echo '<!DOCTYPE html>' | node node_modules/.bin/prettier --parser html
[error] stdin: Error: Couldn't resolve parser "html"
[error]     at resolveParseFunction (/fake/path/node_modules/prettier/index.js:5844:13)
[error]     at Object.parse$1 [as parse] (/fake/path/node_modules/prettier/index.js:5852:25)
[error]     at formatWithCursor (/fake/path/node_modules/prettier/index.js:27628:22)
[error]     at Object.formatWithCursor (/fake/path/node_modules/prettier/index.js:27906:12)
[error]     at format (/fake/path/node_modules/prettier/bin/prettier.js:20363:21)
[error]     at /fake/path/node_modules/prettier/bin/prettier.js:20466:19
[error]     at processTicksAndRejections (internal/process/task_queues.js:93:5)

$ echo 'alert(1)' | node node_modules/.bin/prettier --parser babel
[error] stdin: Error: Couldn't resolve parser "babel"
[error]     at resolveParseFunction (/fake/path/node_modules/prettier/index.js:5844:13)
[error]     at Object.parse$1 [as parse] (/fake/path/node_modules/prettier/index.js:5852:25)
[error]     at formatWithCursor (/fake/path/node_modules/prettier/index.js:27628:22)
[error]     at Object.formatWithCursor (/fake/path/node_modules/prettier/index.js:27906:12)
[error]     at format (/fake/path/node_modules/prettier/bin/prettier.js:20363:21)
[error]     at /fake/path/node_modules/prettier/bin/prettier.js:20466:19
[error]     at processTicksAndRejections (internal/process/task_queues.js:93:5)

# This actually works!
$ echo 'alert(1)' | node node_modules/.bin/prettier --parser babylon
alert(1);
```

**Expected behavior:**

The latest version of Prettier should be installed. This seems to work fine with `npm install`

**Actual behavior:**

Lots of errors, as seen above.

**Comment by Skalman** [comment]
Omg, I'm completely confused about the versions. Please ignore this. :-)
