### ISSUE TITLE
ContinueStatement and BreakStatement comments are not printed

### ISSUE THREAD

**Issue by Gobie** [prettier/prettier#7126]
**Prettier 1.19.1**
[Playground link for continue](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgNx4CUWwAOlFlgJaq6RQAmVMV0x9LUArnOZQPT8sAIwxwAhgGsqUAOZZIAW0UIYfLHhwAHCAGddVYQBs4AQQwZxATywAfW1gDaAXUIA6XZhg5C5AL4gADQgEFos0LrIoOIWEADuAAoxCJEo4gBuEFQMQSCi4mCScDAAyloFMrLIMBg8wQAWMIpGAOr1zHC65WBwJSnMVOnMVsjg+rkyunAYMAmWsoriyKjiRlPBAFa6AB4AQpaFxSXiKgAyMnDLq+sgW9sllSYAilwQ8FdrcMHlGFMYo8JxMI4EZcloMDIYC1sjB6sgABwABm+GD0cBali0o3BnWm6UuwQAjq94HNQqkQOJdABaKBwOAMBm5MTEqhiObiBZLJArT7BKaKKgfG4GOTPEmXHnXL4gGBA6EMWHIABMwRq4ioRkqAGEIMpuSAoNACSAuFMACpA1K8m7pHgASUYqhKYAhYVMjBKMCsJmFMoYEDAfr8fiAA)
[Playground link for break](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgNx4CUWwAOlFlgJaq6RQAmVMV0xARhnAIYDW5lAPSCsnHrypQA5lkgBbOQhgCseHAAcIAZy1V2AGzgBBDBm4BPLAB8rWANoBdQgDotmGDkLkAviAA0IBDqLNBayKDcphAA7gAKkQhhKNwAbhBUDP4gnNxgvHAwAMrquZJSyDAYAK5wAQAWMHL6AOp1zHBaJWBwhYnMVCnM5sjgOlmSWnAYMLFmUnLcyKjc+pMBAFZaAB4AQmZ5BYXcigAyknBLK2sgm1uFZYYAilUQ8JertSAlGJMYI+zcdhwfRZdQYSQwZoZGB1ZAADgADAEwdo4M0zOoRmCOlMUhcAgBHF7wWZBJIgbhaAC0UDgcAY9KyXCJVC4s2480WSGWHwCkzkVHe1100iexIu3KunxggKhDBhyAATAFKtwqPoygBhCAKLkgKDQfEgKqTAAqgKSPOuKRqAElGEpCmBwcEjIxCjBzIYhZ8GBAwD7vN4gA)

Default options

**Input:**
```jsx
for (;;) {
  if (condition) continue
  // breaking comment
  ;(possibleArray || []).sort()
}
```

**Output:**
```jsx
Error: Comment "breaking comment" was not printed. Please report this error!
    at https://prettier.io/lib/standalone.js:15543:15
    at Array.forEach (<anonymous>)
    at ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:15541:17)
    at coreFormat (https://prettier.io/lib/standalone.js:15592:5)
    at format (https://prettier.io/lib/standalone.js:15832:75)
    at formatWithCursor (https://prettier.io/lib/standalone.js:15848:14)
    at https://prettier.io/lib/standalone.js:31794:17
    at Object.format (https://prettier.io/lib/standalone.js:31802:14)
    at formatCode (https://prettier.io/worker.js:234:21)
    at handleMessage (https://prettier.io/worker.js:185:18)
```

**Expected behavior:**
It should have the same output as is the input, as
```jsx
for (;;) {
  if (condition) continue
  // breaking comment
  ;(possibleArray || []).sort()
}
```
was the previous prettier output of formatting
```jsx
for (;;) {
  if (condition) continue;
  // breaking comment
  (possibleArray || []).sort()
}
```

**Comment by zhouyu1993** [comment]
--no-semi

Input:

```
[1, 2].forEach((item) => console.log(item))

[1, 2].forEach((item) => console.log(item))
```

Output:

```
;[1, 2]
  .forEach((item) => console.log(item))

  [(1, 2)].forEach((item) => console.log(item))
```

The first line, I can understand.

The second line, I'm shocked.

**Comment by seiyab** [comment]
I think this can be closed.

**Comment by zhouyu1993** [comment]
已收到。谢谢，我会尽快回复你。

**Comment by fisker** [comment]
There are two open PRs linked to it #7160 and #7161, not sure what's the status.

**Comment by zhouyu1993** [comment]
已收到。谢谢，我会尽快回复你。
