### ISSUE TITLE
Error: Mixed descriptor in srcset is not supported

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#7234]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgSzDArgJzgD4AdKAAkvNQGcICw5yb8wa4YBeEkAegFs4AE0wBDXnAAeo-ugA2cGrxoEAZnHwBaAEwAWAAw79+gHQArdAHMeZKnfuCRo7iAAU-TFE0B3TEJgAFkjkABzG6JIAlDykFFSomPyWzKwuAsJiEtKyCkroop7wQpoBolDF2gCcIZoAzLXa5lY85LyxqLxYOATEZCAANCAQ6DCY0DTIoKL4+BDeAArTCBMoogBuEH4DIABG+KJgANYcAMr5YJ6WyDD4uHCDATD8cgDqAZjwNOdwJ8sfmGsPgBPZDgGgTQaedj4GDzfaWfiiZCqURydiDMw0SQAIX2R1OMjgABlPHBkaj0SBMZITpcFABFXAQeDktH3ED5fDQ0GPZ7bdD4QovPyBZBhQYCiDsF77dCggWKDRrMmDACOTPgcOGKxAohomigcGEwm2hHVmEIcNECKRSBRbMG7A811u7JodLgjOZZLtFPZMFEO2F-gCyG0gxuBTklwAwhB+IjQVBoCqQLh2AAVQMre2UtZ3ACS5QQMBOYEFIwAguUTjAgQpWewAL5NoA)
```sh
--parser html
```

**Input:**
```html
<picture>
    <source srcset="/media/examples/surfer-240-200.jpg"
            media="(min-width: 800px)">
    <img src="/media/examples/painted-hand-298-332.jpg" />
</picture>

```

**Output:**
```html
Error: Mixed descriptor in srcset is not supported
    at printImgSrcset (https://prettier.io/lib/standalone.js:20867:13)
    at printEmbeddedAttributeValue (https://prettier.io/lib/standalone.js:21538:26)
    at Object.embed$2 [as embed] (https://prettier.io/lib/standalone.js:21009:43)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15170:30)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15288:31)
    at https://prettier.io/lib/standalone.js:15253:18
    at Object.printComments (https://prettier.io/lib/standalone.js:14974:19)
    at printGenerically (https://prettier.io/lib/standalone.js:15252:24)
    at https://prettier.io/lib/standalone.js:21285:175
    at FastPath.map (https://prettier.io/lib/standalone.js:15155:23)
```

**Comment by thorn0** [comment]
Turns out it's a playground-only error. I keep falling into this trap. Something should be done about it.
