### ISSUE TITLE
Prettier failed without any reason when build project.

### ISSUE THREAD

**Issue by kongchujun** [prettier/prettier#7382]
C:/sofeware/grafana/grafana-6.5.2/data/plugins/simple-react-panel-master/src/SimplePanel.tsx

  Run toolkit:dev to fix errors
  Trace: Error: Prettier failed
      at C:\sofeware\grafana\grafana-6.5.2\data\plugins\simple-react-panel-master\node_modules\@grafana\toolkit\src\cli\tasks\plugin.build.js:129:31
      at step (C:\sofeware\grafana\grafana-6.5.2\data\plugins\simple-react-panel-master\node_modules\tslib\tslib.js:136:27)
      at Object.next (C:\sofeware\grafana\grafana-6.5.2\data\plugins\simple-react-panel-master\node_modules\tslib\tslib.js:117:57)
      at fulfilled (C:\sofeware\grafana\grafana-6.5.2\data\plugins\simple-react-panel-master\node_modules\tslib\tslib.js:107:62)
      at C:\sofeware\grafana\grafana-6.5.2\data\plugins\simple-react-panel-master\node_modules\@grafana\toolkit\src\cli\utils\useSpinner.js:24:29
      at step (C:\sofeware\grafana\grafana-6.5.2\data\plugins\simple-react-panel-master\node_modules\tslib\tslib.js:136:27)
      at Object.throw (C:\sofeware\grafana\grafana-6.5.2\data\plugins\simple-react-panel-master\node_modules\tslib\tslib.js:117:57)
      at rejected (C:\sofeware\grafana\grafana-6.5.2\data\plugins\simple-react-panel-master\node_modules\tslib\tslib.js:108:69)
× Prettier failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kongchujun** [comment]
Anyone met the same problem, I can build my project because Prettier and it dosen't show any problem.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo
