### ISSUE TITLE
Flow: support `SymbolTypeAnnotation`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#7471]
**Prettier pr-6773**
[Playground link](https://deploy-preview-6773--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEB6VACAAgMwDYQDuAOlKZFAM4wYCeSGltAtgEYR4YC8GAFAJoA6AIIMmbDgEoA3KRAAaEBAAOMAJbRKyUAEMATnqIAFfQi0odeQjtpbFrPTrABrODADKyp2qgBzZDB6AK5wigAWMMx4AOphavCUXmBw7mbxagBu8bTI4JR2ID6UcHowRo6+zDrIOJbFigBWlAAeAEKOLm7uOsxwADI+cDV1oSBNze4+vnhwAIpBEPDDePUgXnrFern4RAprej4w0WoAJjBhyAAcAAyKyobF0Y7KufdwmxlDigCOC-DlKnMIB0lAAtFA4HATlC9no4L81HDyjpKtUkLUVqNisw1AFglipjN5oshuiRooYDpWMczhckAAmCmONR4KYAYQgzCquXeAFY9kFigAVKnmDGrDIhACSUGhsHcYAOqmEsvcMFoM2WxQAvtqgA)

Playground link is `next` branch, test case from [flow codebase](https://github.com/facebook/flow/blob/90fcd8f83df4c791266f985689ad959a775f8667/tests/enums/cast.js#L32) , found in #7470

```sh
--parser flow
```

**Input:**
```jsx
// @flow

const y: symbol = (Y.A: symbol);

```

**Output:**
```jsx
Error: unknown type: "SymbolTypeAnnotation"
    at printPathNoParens (https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:27662:15)
    at Object.genericPrint$3 [as print] (https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:25317:32)
    at callPluginPrintFunction (https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:16206:20)
    at https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:16158:49
    at Object.printComments (https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:15852:21)
    at printGenerically (https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:16158:24)
    at FastPath.call (https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:15965:20)
    at printPathNoParens (https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:26810:23)
    at Object.genericPrint$3 [as print] (https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:25317:32)
    at callPluginPrintFunction (https://deploy-preview-6773--prettier.netlify.com/lib/standalone.js:16206:20)
```

**Expected behavior:**

**Comment by thorn0** [comment]
Closed by #7472. Automatic closing seems to be broken.
