### ISSUE TITLE
[2.0] Invalid configuration file `...`: parent.eval is not a function

### ISSUE THREAD

**Issue by milesj** [prettier/prettier#7818]
**Environments:**

- Prettier Version: 2.0.0
- Running Prettier via: CLI
- Runtime: Node 10.10 AND 12.16
- Operating System: mac osx

**Steps to reproduce:**

Once updating to 2.0, all my prettier commands are failing, across all my projects. It's always the same error:

```
[error] Invalid configuration file `packages/config/src/configs/babel.ts`: parent.eval is not a function
```

I tried the following command on Node 10 AND 12, and it's the same error.

```
npx prettier packages/config/src/configs/babel.ts --write
```

Also fails with or without `--write`.

My `prettier.config.js`:

```js
module.exports = {
  arrowParens: 'always',
  bracketSpacing: true,
  endOfLine: 'lf',
  jsxBracketSameLine: false,
  printWidth: 100,
  proseWrap: 'always',
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
};
```

**Expected behavior:**

It works.

**Actual behavior:**

It doesn't.

**Comment by astorije** [comment]
I'm getting the same output regardless of which file Prettier is trying to prettify. Some additional stacktrace I could get, not from running `prettier` directly but through `husky` and `pretty-quick`:

```
[...]/node_modules/prettier/third-party.js:94
  return parent === undefined ? eval('require')(filePath) : parent.eval('require')(filePath); // In case cache doesn't have parent, fall back to normal require
                                                                   ^

TypeError: parent.eval is not a function
    at importFresh ([...]/node_modules/prettier/third-party.js:94:68)
    at loadJs ([...]/node_modules/prettier/third-party.js:10997:20)
    at ExplorerSync.loadFileContentSync ([...]/node_modules/prettier/third-party.js:11652:28)
    at ExplorerSync.createCosmiconfigResultSync ([...]/node_modules/prettier/third-party.js:11657:32)
    at ExplorerSync.loadSearchPlaceSync ([...]/node_modules/prettier/third-party.js:11638:27)
    at ExplorerSync.searchDirectorySync ([...]/node_modules/prettier/third-party.js:11623:34)
    at run ([...]/node_modules/prettier/third-party.js:11603:29)
    at cacheWrapperSync ([...]/node_modules/prettier/third-party.js:11312:20)
    at ExplorerSync.searchFromDirectorySync ([...]/node_modules/prettier/third-party.js:11615:52)
    at ExplorerSync.searchSync ([...]/node_modules/prettier/third-party.js:11595:27)
```

**Comment by wKovacs64** [comment]
Same. Seems to be an issue with the JavaScript (`prettier.config.js`) method of configuration. Changing my config to JSON in `.prettierrc` works.

**Comment by milesj** [comment]
Confirmed this works with `.prettierrc` but not `prettier.config.js`.

**Comment by lipis** [comment]
We are looking into it.. expect a patch to be released very soon.

**Comment by thorn0** [comment]
I'll close this after 2.0.1 is released.

**Comment by thorn0** [comment]
2.0.1 is on npm 🎉

**Comment by milesj** [comment]
Thank you! Confirmed it worked.
