### ISSUE TITLE
Warning for a breakign change for 2.0.1 missing - text.trimEnd is not a function

### ISSUE THREAD

**Issue by thebravoman** [prettier/prettier#7830]
**Environments:**

- Prettier Version: 2.0.1
- Running Prettier via: CLI
- Runtime: Node
- Operating System: macOS

**Steps to reproduce:**
Try to format a file that we have and was successfully format for months

**Expected behavior:**
File is formated

**Actual behavior:**
```
Checking formatting...
app/assets/javascripts/ext/project/abstract_tree_viewer.js
[error] app/assets/javascripts/ext/project/abstract_tree_viewer.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/fancytree/dependencies.js
[error] app/assets/javascripts/ext/project/fancytree/dependencies.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/fancytree/fancytree_editor.js
[error] app/assets/javascripts/ext/project/fancytree/fancytree_editor.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/fancytree/fancytree_filtered_steps_styler.js
[error] app/assets/javascripts/ext/project/fancytree/fancytree_filtered_steps_styler.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/fancytree/fancytree_viewer.js
[error] app/assets/javascripts/ext/project/fancytree/fancytree_viewer.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/fancytree/i_fancytree_extension.js
[error] app/assets/javascripts/ext/project/fancytree/i_fancytree_extension.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/fancytree/i_fancytree_steps_styler.js
[error] app/assets/javascripts/ext/project/fancytree/i_fancytree_steps_styler.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/register_fancytree_filtered_steps_styler.js
[error] app/assets/javascripts/ext/project/register_fancytree_filtered_steps_styler.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/register_tree_editor.js
[error] app/assets/javascripts/ext/project/register_tree_editor.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/register_tree_viewer.js
[error] app/assets/javascripts/ext/project/register_tree_viewer.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
app/assets/javascripts/ext/project/tree_explorer.js
[error] app/assets/javascripts/ext/project/tree_explorer.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
test/dummy/spec/javascripts/ext/project/abstract_tree_viewer_spec.js
[error] test/dummy/spec/javascripts/ext/project/abstract_tree_viewer_spec.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
test/dummy/spec/javascripts/ext/project/fancytree/fancytree_editor_spec.js
[error] test/dummy/spec/javascripts/ext/project/fancytree/fancytree_editor_spec.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
test/dummy/spec/javascripts/ext/project/fancytree/fancytree_filtered_steps_styler_spec.js
[error] test/dummy/spec/javascripts/ext/project/fancytree/fancytree_filtered_steps_styler_spec.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
test/dummy/spec/javascripts/ext/project/fancytree/fancytree_viewer_spec.js
[error] test/dummy/spec/javascripts/ext/project/fancytree/fancytree_viewer_spec.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
vendor/assets/javascripts/gcc/externs/fancytree.externs.js
[error] vendor/assets/javascripts/gcc/externs/fancytree.externs.js: TypeError: text.trimEnd is not a function
[error]     at attachComments (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14775:60)
[error]     at coreFormat (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:15040:12)
[error]     at Object.args [as formatWithCursor] (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:50647:12)
[error]     at format$1 (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52692:19)
[error]     at Object.formatFiles (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:52865:16)
[error]     at Object.run (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53319:14)
[error]     at Object.<anonymous> (/home/shadydealer/.nvm/versions/node/v8.17.0/lib/node_modules/prettier/bin-prettier.js:53334:5)
[error]     at Module._compile (module.js:653:30)
Colla
```

**Comment by thebravoman** [comment]
I have change the title. I think you have done good to describe the breaking changes. 

But on an upgrade or on a run there should be some "deprecation message" to prepare you.

**Comment by thorn0** [comment]
see https://prettier.io/blog/2020/03/21/2.0.0.html#drop-support-for-node-versions-older-than-10-6908httpsgithubcomprettierprettierpull6908-by-fiskerhttpsgithubcomfisker

**Comment by j-f1** [comment]
Would it be worth it to integrate something like [`please-upgrade-node`](https://github.com/typicode/please-upgrade-node) that checks if the current Node version is unsupported early in Prettier’s startup process and kills the process after providing a more helpful message?

**Comment by thebravoman** [comment]
@thorn0 I saw that it is documented. But I think it should be in the build itself. When you run it to upgrade all clients to 1.99 that will give errors that in 2.0 things will change an your current environment will stop working. Then in 2.0 do the changes

@j-f1 this will be reactive - after the fact. A proactive approach will be to tell people on execute on prettier - "hey, you are using something that we have deprecated. Please do X". So stopping the execute will again break everything on a Sunday.

It should have a step in between the current state and the broken state were proper deprecations are communicated. And the most appropriate place is when you start prettier.

**Comment by thorn0** [comment]
@thebravoman I really don't understand your attitude. It's a major version bump. By definition, you can't just blindly update to it expecting that nothing will break.

**Comment by thebravoman** [comment]
@thorn0 I am sorry. I don't mean to offend you. I have great respect to your work. Guess I go used to getting notifications for deprecations and this got me by surprise. I also did not expected it to come from prettier. Was not prepared for this. Github says it is used by 1.5M, it is the last and final step in our build procedure and I was pretty happy of how we used it. I was expecting other projects in the pipeline to fail, but I had the feeling that prettier was pretty solid. 

1. I have not blindly updated. 
All I am doing is 
npx prettier.

Now why has this done an upgrade I can not answer. I don't know. 

2. I have no problem with upgrading and with braking changes. Please do them. People learn. People become better. It takes practice and it takes experience to keep an API and I am ok with that. I have personally broken changes on API that I have developed and I understand many of the considerations.

3. All I am asking is for a "note". A note that says "hey, this will be deprecated." And to have this note on the build. In a nontrivial stack with many dependencies one can not be expected to constantly monitor all the changes in all the projects. So a good practice I could suggest is to act proactively. Just release a version 1.99 that will mark all the deprecations and give people a chance to migrate with proper messages. 

4. Also document all the features that are no longer supported. A breaking change in my previous bug is actually not mentioned in the breaking changes.

**Comment by thorn0** [comment]
> I have not blindly updated.
> All I am doing is
> npx prettier.

How is this not blindly updating?

> Now why has this done an upgrade I can not answer. I don't know.

That's how npx works. You should have pinned the version: `npx prettier@1.19.1...`

**Comment by thorn0** [comment]
> So a good practice I could suggest is to act proactively. Just release a version 1.99 that will mark all the deprecations and give people a chance to migrate with proper messages.

Thanks you for your suggestions, but this is not going to happen. When one updates something to a major version, things break. One should not update if they have no time for the necessary adjustments and making sure everything works after the update.

> Also document all the features that are no longer supported. A breaking change in my previous bug is actually not mentioned in the breaking changes.

That's true. We could document that change better.

**Comment by thebravoman** [comment]
| How is this not blindly updating?

I still don't know. Seems that npx has upgraded only one machine. It happen on only one machine. Even the other servers were not affected. No developers were no affected by this eighter. But only one machine, that was packaging. On my machine doing 'npx prettier' is still using 1.19.1. Guess we would have to do more reading of npx. 

| That's how npx works. You should have pinned the version: npx prettier@1.19.1 ..

I should probably have pinned to the correct version of prettier and every other package. If, I knew the correct version of course. But that is not healthy. That's why we have package managers, apart from all else to update your packages to new versions with appropriate bug fixes and security fixes. This is something good that many software communities have established in recent decades. 

Just warn people. Interoperability and Ergonomics.

**Comment by thorn0** [comment]
> Guess we would have to do more reading of npx.

Exactly.

**Comment by j-f1** [comment]
I’d recommend using Prettier by installing it locally to each project, either individually or as a peer dependency of a common helper package. This way you have choice about when you upgrade packages and you can wait until it’s convenient to do so. You would then be able to create npm scripts to run Prettier for you.

**Comment by ycjcl868** [comment]
I tried to use `yarn` was working, but the `npm` didn't work.

**Comment by thebravoman** [comment]
Thanks for the suggestion @j-f1. It might work for one or two small projects and if there is no CLI infrastructure involved, but it would be a maintenance hell for a real life scenario with more than a few projects.

**Comment by thebravoman** [comment]
@ycjcl868 yes the small differences (like not breaking downstream clients) really could save or lose a few days or each team.

**Comment by eXamadeus** [comment]
@thebravoman It's not prettier's fault you are using `npx` wrong and have a really weird pipeline.  Let me learn you something, `npx` does one of two things in this order:

- runs whatever command you specify from some locally installed version, whether that's in your installed `node_modules`, located on your `$PATH`, or a few other places
- OR if you don't have the command installed anywhere locally, it downloads it in a cache and runs it one-off style

> I should probably have pinned to the correct version of prettier and every other package. If, I knew the correct version of course. But that is not healthy. That's why we have package managers, apart from all else to update your packages to new versions with appropriate bug fixes and security fixes.

What crazy world do you live in?  Of course you should ALWAYS pin the version of tools you are using.  If you know how to use `package.json` correctly you'd realized you can specify a range of versions.

Honestly, I don't know why I'm wasting my time explaining this all to you.  I suppose you struck a nerve with your arrogant assumptions that your poor configuration is somehow the fault of the `prettier` maintainers.

**Comment by thebravoman** [comment]
Thanks for the lesson @eXamadeus. Much appreciated. 

Looking back at it it was a combination of things.
1. npx prettier was finding that there is a prettier version already install and was still installing a new one. No problem there. Kind of odd, but it is npx not prettier.  
2. 
> Of course you should ALWAYS pin the version of tools you are using. 

I have never in my life done
```
$ mv --version 1.2 file1 file2
```

or for that matter 
```
$ grep text * --version=1.4.3
$ gzip --version=5.4 file
```

In fact I don't even know the versions of grep, gzip, mv that I am using and these are tools I am using very often. 

But this is not a fair comparison, I admin. 

I get than about the versions. I get that they should be pinned. I understand the locks. I accept them. I use them. Not only in yarn/npm but in many places. I kind of grew to like them. We are best friends for years now.

3. Software changes and there are breaking changes. Prettier team has done a tremendous job. If they've decided that something should be changed I am sure it was on more than 2 votes on a github issue and many things were taken into considerations.

These are all actually not my real issues.

My issue (understood as 'github issue' not 'personal issue') is:

> But on an upgrade or on a run there should be some "deprecation message" to prepare you.

Prettier is releasing a breaking change with 2.X.X. Just release a 1.9.99 version to prepare you for this change and when starting prettier just print something on the lines of:

'Hey guys, you are using prettier in a way that will no longer work with next prettier version. There are some breaking changes. Nothing to worry about. It is all for the better. Here is a link to a documentation were you could see what will change. We are writing this message as of version 1.9.99 to give you enough time to prepare to upgrade to 2.X.X". 

The tool sees and knows what configurations and setup I am using. It could easily understand what will no longer work as before and will not be supported in next versions.  Should you release 2.X.X a day after 1.9.99 - no, probably that's too fast. Should you wait an year - no, that's too slow. How much time should there be between 1.9.99 and 2.X.X - it is specific for each project and community. 

The api breaking changes are not that much. If nothing will change for me then don't print anything. A pseudo implementation could look like this:

```
def methodDoingSomething
    print "This method will no longer exist in 2.X.X. Please see this: href"
    ....
```

You can't of course mark all the methods that will not exist or be changed. But you could mark the few major once or you could come up with a different approach.

**Comment by yuzhiyao** [comment]
update node version.

**Comment by slashwhatever** [comment]
I'm running node v12.16.3 and still see this error when using prettier v2.0.5
