### ISSUE TITLE
npm  run  format Always fail

### ISSUE THREAD

**Issue by longletian** [prettier/prettier#8005]
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\software\\nodejs\\node.exe',
1 verbose cli   'D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prettier'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'prettier' ]
5 info lifecycle tsprogram@0.0.0~prettier: tsprogram@0.0.0
6 verbose lifecycle tsprogram@0.0.0~prettier: unsafe-perm in lifecycle true
7 verbose lifecycle tsprogram@0.0.0~prettier: PATH: D:\software\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\workProgram\Angular\TypeClass\tsprogram\node_modules\.bin;D:\software\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\workProgram\Angular\TypeClass\tsprogram\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;D:\software\Redis\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;D:\software\nodejs\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\MongoDB\Server\4.2\bin;C:\Program Files (x86)\dotnet\;D:\software\Microsoft VS Code x64\bin;C:\Go\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\software\Seq\;D:\software\Seq\Client\;C:\Users\longl\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\longl\AppData\Local\Programs\Python\Python38-32\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\longl\AppData\Local\Microsoft\WindowsApps;C:\Users\longl\.dotnet\tools;C:\Users\longl\AppData\Local\GitHubDesktop\bin;C:\Users\longl\AppData\Roaming\npm;D:\software\JetBrains Rider 2019.3.1\bin;D:\software\GoLand 2019.2.2\bin;D:\software\mysql-8.0.19-winx64\bin;D:\software\Neovim\bin;D:\software\WebStorm 2019.3.2\bin;D:\workProgram\aspnetcore\.dotnet;D:\workProgram\aspnetcore\.dotnet\x86\;D:\software\IntelliJ IDEA 2019.3.2\bin;D:\softwarePackage\Java\jdk-11.0.6\bin;D:\dailySoftware\Bandizip\;D:\dailySoftware\Nmap;D:\software\RabbitMQ Server\rabbitmq_server-3.8.2\sbin;D:\workProgram\GO\bin
8 verbose lifecycle tsprogram@0.0.0~prettier: CWD: D:\workProgram\Angular\TypeClass\tsprogram
9 silly lifecycle tsprogram@0.0.0~prettier: Args: [
9 silly lifecycle   '/d /s /c',
9 silly lifecycle   "prettier --config .prettierrc --write 'src/app/**/!(testing)/!(polyfills).{ts,scss}'"
9 silly lifecycle ]
10 silly lifecycle tsprogram@0.0.0~prettier: Returned: code: 2  signal: null
11 info lifecycle tsprogram@0.0.0~prettier: Failed to exec prettier script
12 verbose stack Error: tsprogram@0.0.0 prettier: `prettier --config .prettierrc --write 'src/app/**/!(testing)/!(polyfills).{ts,scss}'`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (D:\software\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:210:5)
12 verbose stack     at ChildProcess.<anonymous> (D:\software\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:210:5)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid tsprogram@0.0.0
14 verbose cwd D:\workProgram\Angular\TypeClass\tsprogram
15 verbose Windows_NT 10.0.18363
16 verbose argv "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prettier"
17 verbose node v12.14.0
18 verbose npm  v6.13.4
19 error code ELIFECYCLE
20 error errno 2
21 error tsprogram@0.0.0 prettier: `prettier --config .prettierrc --write 'src/app/**/!(testing)/!(polyfills).{ts,scss}'`
21 error Exit status 2
22 error Failed at the tsprogram@0.0.0 prettier script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 2, true ]
```
.prettierrc

![image](https://user-images.githubusercontent.com/28197668/78967564-69660c00-7b35-11ea-8aba-a4b65d0b72b5.png)
![image](https://user-images.githubusercontent.com/28197668/78967579-7551ce00-7b35-11ea-889f-ec3d01fb3bdb.png)

**Comment by evilebottnawi** [comment]
Please format the problem properly. I can’t understand anything, it’s best to create a minimally reproducible repository

**Comment by j-f1** [comment]
What do you get if you run `npx prettier --config .prettierrc --write 'src/app/**/!(testing)/!(polyfills).{ts,scss}'`?
