### ISSUE TITLE
Uncaught TypeError: createRequire is not a function

### ISSUE THREAD

**Issue by TJProgrammer** [prettier/prettier#8047]
**Environments:**

- Prettier Version: 2.0.4
- Running Prettier via: atom-prettier
- Runtime: ?
- Operating System: Linux, macOS, windows

**Steps to reproduce:**

Please see https://github.com/prettier/prettier-atom/issues/725

Thanks!

**Comment by thorn0** [comment]
Sounds like a Node version problem. Prettier requires Node 10.13.0+.

**Comment by BarryThePenguin** [comment]
I'm seeing a similar issue..

**Environments:**

- Prettier Version: 2.0.4
- Running Prettier via: https://github.com/xojs/atom-linter-xo
- Runtime: Node v12.16.0, Atom 1.45.0
- Operating System: macOS

**Steps to reproduce:**

1. clone https://github.com/BarryThePenguin/simple-desktop-images`
1. run `npm install && npx npm-check --update-all`
1. Open the project in atom with `atom-linter-xo` installed
1. Run "XO: fix" from the Atom command palette

Result

> [Linter] Error running XO TypeError: createRequire is not a function

Expected

> Should see lint errors

I can also create a new issue if need be..
I thought I'd ask here first before creating one in `atom-linter-xo` or `xo`

**Comment by NazarkinRoman** [comment]
Also seen this when tried to run prettier through [Jetbrains IDEA plugin](https://plugins.jetbrains.com/plugin/10456-prettier).

Environments:

- Prettier Version: 2.0.4
- Running Prettier via: [Jetbrains IDEA plugin](https://plugins.jetbrains.com/plugin/10456-prettier)
- Runtime: Node v10.13.0, JetBrains WebStorm 2020.1
- Operating System: macOS

Here is the output:
```
TypeError: createRequire is not a function
    at Object.<anonymous> (/Users/roman/.nvm/versions/node/v10.13.0/lib/node_modules/prettier/index.js:23267:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at requireInContext (/Applications/WebStorm.app/Contents/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:70:12)
    at PrettierPlugin.requirePrettierApi (/Applications/WebStorm.app/Contents/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:44:24)
Process finished with exit code -1
```

**Comment by thorn0** [comment]
@NazarkinRoman You shouldn't need the plugin to use Prettier in WebStorm 2020.1. See https://prettier.io/docs/en/webstorm.html

**Comment by matepek** [comment]
My tests are failing too with this error: https://travis-ci.org/github/matepek/vscode-catch2-test-adapter/jobs/675884929

**Comment by thorn0** [comment]
@matepek Your tests use `vscode-loader` that [patches](https://github.com/microsoft/vscode-loader/blob/c5aeb935d58fa9fd1139c3f574e0a541b6768d36/src/core/scriptLoader.ts#L256) Node's `require` in such a way that the 2nd parameter `options` of `require.resolve` is ignored. But I can't understand why `require('module').createRequire` (AKA `createRequireFromPath`) isn't available. At least it seems like the native `require` (should be available)[https://github.com/microsoft/vscode-loader/blob/4c699048f0ce736cc0c3b8d26b14838b24b18896/src/core/main.ts#L96] as `require.nodeRequire`.

**Comment by thorn0** [comment]
@fisker Seems like it's easier to a add a fallback to https://www.npmjs.com/package/require than to fight all these hacks. Thoughts?

**Comment by matepek** [comment]
I downgraded to:
```
"prettier": "2.0.2",
"eslint-plugin-prettier": "3.1.2"
```
It seems working.

**Comment by fisker** [comment]
> @fisker Seems like it's easier to a add a fallback to [npmjs.com/package/resolve](https://www.npmjs.com/package/resolve) than to fight all these hacks. Thoughts?

Let's do it, we don't want waste more time on this.

**Comment by NazarkinRoman** [comment]
> @NazarkinRoman You shouldn't need the plugin to use Prettier in WebStorm 2020.1. See https://prettier.io/docs/en/webstorm.html

This plugin was installed for long time ago so I just didn't realized that WebStorm now has native support for it. But it seems that they simply replaced old plugin with their own bundled when I updated to the latest version so the bug is still actual.

**Comment by thorn0** [comment]
I'm going to release 2.0.5 this weekend. It will include a fix for these problems (#8072).

**Comment by thorn0** [comment]
@NazarkinRoman 2.0.5 is out. Please update and check if the issue is gone.

**Comment by BarryThePenguin** [comment]
Thanks all, looks like that solved the issue 🎉

**Comment by NazarkinRoman** [comment]
@thorn0 it looks like the previous error has gone, but another one appeared while using Prettier with WebStorm:

```
TypeError: text.trimEnd is not a function
    at attachComments (/Users/nazarkin-roma/.nvm/versions/node/v14.0.0/lib/node_modules/prettier/index.js:14771:60)
    at coreFormat (/Users/nazarkin-roma/.nvm/versions/node/v14.0.0/lib/node_modules/prettier/index.js:14798:23)
    at format (/Users/nazarkin-roma/.nvm/versions/node/v14.0.0/lib/node_modules/prettier/index.js:15019:75)
    at formatWithCursor (/Users/nazarkin-roma/.nvm/versions/node/v14.0.0/lib/node_modules/prettier/index.js:15035:12)
    at args (/Users/nazarkin-roma/.nvm/versions/node/v14.0.0/lib/node_modules/prettier/index.js:51620:12)
    at Object.format (/Users/nazarkin-roma/.nvm/versions/node/v14.0.0/lib/node_modules/prettier/index.js:51640:12)
    at performFormat (/Applications/WebStorm.app/Contents/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:66:29)
    at PrettierPlugin.handleReformatCommand (/Applications/WebStorm.app/Contents/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:36:16)
    at PrettierPlugin.onMessage (/Applications/WebStorm.app/Contents/plugins/prettierJS/prettierLanguageService/prettier-plugin.js:11:33)
    at Interface.<anonymous> (/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js:105:39)
Process finished with exit code -1
```

**Comment by thorn0** [comment]
@NazarkinRoman Does this happen always or only when formatting some specific piece of code? Does downgrading to 2.0.2 fix this?

**Comment by NazarkinRoman** [comment]
@thorn0 Hmm. Right now tried to run it again and it worked (for both cases: whole document and range). I'll get back to you if this error will appear again.

**Comment by yuzhiyao** [comment]
update node version

**Comment by acroyear** [comment]
2.0.5 (with eslint-prettier 3.1.4) did not solve the problem for me (Atom 1.44)

**Comment by meycon1** [comment]
I decided to do an update to borales/actions-yarn/@v2.3.0
