### ISSUE TITLE
Inconsistent parsing of injected expressions in styled-components' css

### ISSUE THREAD

**Issue by helios1138** [prettier/prettier#8095]
note the presence/absence of `;` after injected expression
```ts
const Header = styled.div`
  ${something()};
margin:4px;
`
```
is parsed and formatted as
```ts
const Header = styled.div`
  ${something()};
  margin: 4px;
`;
```
---
```ts
const Header = styled.div`
  ${something()}
margin:4px;
`
```
is parsed and formatted as
```ts
const Header = styled.div`
  ${something()}
  margin:4px;
`;
```
---
```ts
const Header = styled.div`
  ${something()};
  & > ${Child}:not(:first-child) {
margin-left:5px;
}
`
```
is parsed and formatted as
```ts
const Header = styled.div`
  ${something()};
  & > ${Child}:not(:first-child) {
    margin-left: 5px;
  }
`;
```
---
```ts
const Header = styled.div`
  ${something()}
  & > ${Child}:not(:first-child) {
margin-left:5px;
}
`
```
is not parsed
```
Error: Couldn't insert all the expressions
    at transformCssDoc (https://prettier.io/lib/standalone.js:22171:11)
    at Object.embed$4 [as embed] (https://prettier.io/lib/standalone.js:22011:18)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15781:31)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15898:29)
    at https://prettier.io/lib/standalone.js:15863:16
    at Object.printComments (https://prettier.io/lib/standalone.js:15586:17)
    at printGenerically (https://prettier.io/lib/standalone.js:15862:22)
    at FastPath.call (https://prettier.io/lib/standalone.js:15700:16)
    at printPathNoParens (https://prettier.io/lib/standalone.js:25178:91)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:23541:28)
```

**Comment by thorn0** [comment]
Note that this error is shown only on the playground for debugging purposes. In production, Prettier just skips formatting this template literal. And I'd say this is the right thing to do because how can we know what `something()` can be? It can be a part of the selector or a separate rule set, so it's not clear how to format it. Leaving it as is the safest option.

**Comment by thecodrr** [comment]
The error occurs when you have multiple string concatenations. If you remove `${Child}` or `${something()}`, there's no error. As such, this works without an issue:

```js
const Header = styled.div`
  ${something()}
  & > $Child:not(:first-child) {
margin-left:5px;
}
`
```

**Comment by thecodrr** [comment]
@thorn0 Can I claim this?

**Comment by thorn0** [comment]
@thecodrr I'm already looking into it.

**Comment by thecodrr** [comment]
Oops. Okay good luck.
