### ISSUE TITLE
breaks while working with ES7 do expression

### ISSUE THREAD

**Issue by sakivks** [prettier/prettier#810]
Code to be formatted
``` javascript
const env = 'production';
const envSpecific = {
  domain:
    do {
      if(env === 'production') 'https://abc.mno.com/';
      else if(env === 'development') 'http://localhost:4000';
    }
};

console.log(envSpecific.domain);
```

logs in sublime text console

------------
 JsPrettier 
------------

## Prettier CLI Error Output:

TypeError: statements.indent is not a function
        at genericPrintNoParens (/usr/local/lib/node_modules/prettier/src/printer.js:910:44)
        at genericPrint (/usr/local/lib/node_modules/prettier/src/printer.js:42:28)
        at comments.printComments.p (/usr/local/lib/node_modules/prettier/src/printer.js:2367:12)
        at Object.printComments (/usr/local/lib/node_modules/prettier/src/comments.js:288:17)
        at printGenerically (/usr/local/lib/node_modules/prettier/src/printer.js:2365:21)
        at FastPath.call (/usr/local/lib/node_modules/prettier/src/fast-path.js:99:16)
        at genericPrintNoParens (/usr/local/lib/node_modules/prettier/src/printer.js:597:31)
        at genericPrint (/usr/local/lib/node_modules/prettier/src/printer.js:42:28)
        at comments.printComments.p (/usr/local/lib/node_modules/prettier/src/printer.js:2367:12)
        at Object.printComments (/usr/local/lib/node_modules/prettier/src/comments.js:288:17)
    
## Prettier CLI Return Code:

    2

**Comment by vjeux** [comment]
Thanks, good catch. I just sent #811 to fix it :)
