### ISSUE TITLE
HTML can't format my html with awesome vbscripts

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8147]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wAEANgIZQDmAvADogBuARprgXQHw1QBiArlGBg5ohABZxixCAAoAlFwCiUACaE+AodC6oA9C3wx2IADQgIBYVHTJQpLFggB3AAp2E1lKWKPSAT2umjFikYADWcDAAynghOJTIMFi8cKaiMAC2xADqojjw6DFgcJHueTj0eb7I4OgBIHHocFgwzsEU6aTIAGZejaYAVugAHgBCwWERkaTpcAAycXDdvSkgg0ORcRTEcACKvBDwS8R9IDFYjVjVaZkmp7iwWTjKMKLIABwADKZ4Do1ZwXhqj84Bd6ItTABHfbwVrmDwgUjoAC0UDgcGU6NuWDgUJw2NapHanSQPWOK0a6RwCSS5M22z2B0WJOWphgpEYj2eryQACZWcEcMRNgBhCDpDrVEEAVluvEaABV2R5SSd6MkAJIqBBRbAGACCKkiMF82yOjQAvuagA)
```sh
--parser html
```

**Input:**
```html
<script lang="vbscript">
Function hello()
End Function
</script>
```

**Output:**
```html
TypeError: Cannot read property 'endsWith' of undefined
    at inferScriptParser (https://prettier.io/lib/standalone.js:21514:29)
    at Object.embed$2 [as embed] (https://prettier.io/lib/standalone.js:22418:28)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:16786:30)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:16907:33)
    at https://prettier.io/lib/standalone.js:16871:49
    at Object.printComments (https://prettier.io/lib/standalone.js:16544:21)
    at printGenerically (https://prettier.io/lib/standalone.js:16871:24)
    at printChild (https://prettier.io/lib/standalone.js:22672:14)
    at https://prettier.io/lib/standalone.js:22616:16
    at FastPath.map (https://prettier.io/lib/standalone.js:16730:23)
```

**Expected behavior:**

Just kidding, scripts with unknown `lang` and no `type` throws. Will fix it.

Miss vbscript?

**Comment by fisker** [comment]
Seems already fixed by #8023.

**Comment by thorn0** [comment]
It's another playground-only error. Prettier 2.0.5:
```console
$ prettier test.html
<script lang="vbscript">
  Function hello()
  End Function
</script>
However, I'm not sure adding that indentation is the right thing to do.
```

**Comment by fisker** [comment]
I think this is how `script` and `style` works now.

**Comment by fisker** [comment]
playground-only error can only caught if we don't `try/catch` #7296 .

But currently we have many `css-in-js` errors.
