### ISSUE TITLE
Found warnings when formatting markdown files

### ISSUE THREAD

**Issue by ZhiruiLi** [prettier/prettier#8271]
Hi, when I use prettier to format markdown documents, it always print out some warnings like:

```
/usr/local/bin/prettier --loglevel=debug --parser markdown hello.md > /dev/null
[debug] normalized argv: {"_":["hello.md"],"color":true,"editorconfig":true,"loglevel":"debug","parser":"markdown","plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
[debug] resolve config from 'hello.md'
[debug] loaded options `null`
[debug] applied config-precedence (cli-override): {"parser":"markdown"}
(node:59555) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59555) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
```

So what's going wrong here?

Environment info:

```
prettier --version
2.0.4
node --version
v14.2.0
system
macOS 10.15.4
```

**Comment by fisker** [comment]
Can't reproduce, can you share your `hello.md`?

```console
npx prettier --loglevel=debug --parser markdown README.md  > 1.log
[debug] normalized argv: {"_":["README.md"],"color":true,"editorconfig":true,"loglevel":"debug","parser":"markdown","plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
[debug] resolve config from 'README.md'
[debug] loaded options `null`
[debug] applied config-precedence (cli-override): {"parser":"markdown"}
```

**Comment by ZhiruiLi** [comment]
> Can't reproduce, can you share your `hello.md`?
> 
> ```
> npx prettier --loglevel=debug --parser markdown README.md  > 1.log
> [debug] normalized argv: {"_":["README.md"],"color":true,"editorconfig":true,"loglevel":"debug","parser":"markdown","plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
> [debug] resolve config from 'README.md'
> [debug] loaded options `null`
> [debug] applied config-precedence (cli-override): {"parser":"markdown"}
> ```

It's just an empty file created by touch command.

**Comment by fisker** [comment]
I also tested empty file, still no warnings, can you run this?

```bash
node --trace-warnings /usr/local/bin/prettier --loglevel=debug --parser markdown hello.md > /dev/null
```

**Comment by thorn0** [comment]
@ZhiruiLi Do you have any Prettier plugins installed?

**Comment by ZhiruiLi** [comment]
> I also tested empty file, still no warnings, can you run this?
> 
> ```shell
> node --trace-warnings /usr/local/bin/prettier --loglevel=debug --parser markdown hello.md > /dev/null
> ```

```
[debug] normalized argv: {"_":["hello.md"],"color":true,"editorconfig":true,"loglevel":"debug","parser":"markdown","plugin-search-dir":[],"plugin":[],"ignore-path":".prettierignore","debug-repeat":0,"config-precedence":"cli-override"}
[debug] resolve config from 'hello.md'
[debug] loaded options `null`
[debug] applied config-precedence (cli-override): {"parser":"markdown"}
(node:73657) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/RuleContext.js:32:46)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/PredictionContext.js:10:19)
(node:73657) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/tree/Trees.js:15:49)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/RuleContext.js:126:13)
```

**Comment by ZhiruiLi** [comment]
> @ZhiruiLi Do you have any Prettier plugins installed?

I've use `npm install` to install `prettier`. Are there anything need to be installed?

**Comment by fisker** [comment]
>(node:73657) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/tree/Trees.js:15:49)
`

It's from `@solidity-parser`, You may want open an issue there.

**Comment by ZhiruiLi** [comment]
> > (node:73657) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
> > at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
> > at Object.get (internal/modules/cjs/loader.js:831:5)
> > at Object. (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/tree/Trees.js:15:49)
> 
> It's from `@solidity-parser`, You may want open an issue there.

OK, thanks.

**Comment by fisker** [comment]
Sorry, `@solidity-parser/parser`. Don't know it's fixed or not, if fixed, it's `prettier-plugin-solidity` issue.

**Comment by ZhiruiLi** [comment]
> solidity-parser/parser

Should I open issue in [prettier-plugin-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity)?

**Comment by ZhiruiLi** [comment]
> Sorry, it's `@solidity-parser/parser`. Don't know it's fixed or not, if fixed, it's `prettier-plugin-solidity` issue.

Should I open issue in [prettier-plugin-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity)?

**Comment by thorn0** [comment]
@ZhiruiLi Yes, this is an issue with that plugin, not with Prettier core.
