### ISSUE TITLE
Vue: can't parse parenthesized  expression

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8681]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlKgM5Z5SHDAAUeAPkwATsecBGAlAL59UAekrUSZIZlwE4hEABoQELDACW0cslB4ATjogB3AAq6EmlHhwG8AT02KuOvGADWcGAGUqYVVADmyDA6AK5wigAWMBg4AOrhqvCiYHAeZgmqAG4JNsjg5PYgvuRwOjBGTn4YeMgAZpbFigBW5AAeAEJOru4eeBhwADK+cLX1YSDNLR6+fjhwAIrBEPAjOA0gVDrFOrkZoQrrOr4wMaoAJjDhyAAcAAyKWPrFMU5YuQ9wWxnDigCOi-DlZTmEB4cgAWigcDgp2h+x0cD+qnh5TwlWqSDqqzGxQwqkCIWx01mCyWwwxo0UMDwXBO50uSAATJSnKocNMAMIQDBVXIfACs+2CxQAKtTzJi1rs4ABJKAw2AeMCHFQAQTlHhgNlmK2KAiAA)
```sh
--parser vue
```

**Input:**
```vue
<template>
<span>{{(a||          b)}}</span>
</template>
```

**Output:**
```vue
TypeError: Cannot set property 'undefined' of undefined
    at zt (https://prettier.io/lib/parser-babel.js:1:30215)
    at Wt (https://prettier.io/lib/parser-babel.js:1:30493)
    at Object.parse (https://prettier.io/lib/parser-babel.js:1:262557)
    at Object.parse (https://prettier.io/lib/standalone.js:13712:21)
    at textToDoc (https://prettier.io/lib/standalone.js:16798:27)
    at https://prettier.io/lib/standalone.js:16786:79
    at Object.embed$2 [as embed] (https://prettier.io/lib/standalone.js:22427:57)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:16786:30)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:16907:33)
    at https://prettier.io/lib/standalone.js:16871:49
```

**Expected behavior:**

```vue
<template>
  <span>{{ a || b }}</span>
</template>
```

**Comment by fisker** [comment]
@thorn0 This is broken by #7791, [this line](https://github.com/prettier/prettier/blob/cd2b8a32b5ef77eb0047e7517b1ea22d605a094a/src/language-js/postprocess.js#L39) returns a new node, [here](https://github.com/prettier/prettier/blob/cd2b8a32b5ef77eb0047e7517b1ea22d605a094a/src/language-js/postprocess.js#L153) try to assign to `parent[property], and it's root, there is no parent.

I can easily fix this one by add `parent` check here, but I saw potential bug, the node is still the old one, the ast not changed.

Should we use return value in `visitNode`?

**Comment by thorn0** [comment]
We just should disable Babel's `createParenthesizedExpressions` option when parsing Vue expressions.

**Comment by thorn0** [comment]
That won't fix this case though...

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlKgM5Z5SHDABeAZIwBR7MBGAlAL4+oB6StRJkBmXATiEQAGhAQsMAJbRyyUHgBOWiAHcACtoTqUeHHrwBPdfI5a8YANZwYAZSphlUAObIYWgCucPIAFjAYOADqocrwwmBwbiZxygBucVbI4OS2IN7kcFowBg4+GHjIAGbmhfIAVuQAHgBCDs6ubngYcAAy3nDVtSEgjU1u3j44cACKgRDwQzh1IFRahVrZacFyq1reMFHKACYwocgAHAAM8li6hVEOWNl3cBtpg-IAjvPwpYqmEB4cgAWigcDgx0huy0cB+ylhpTw5UqSBqyxGhQwyn8QUxk2mcwWgzRw3kMDwHCOp3OSAATOSHMocJMAMIQDAVbJvACsu0ChQAKpTTOiVts4ABJKBQ2BuMD7JQAQRlbhgVmmS0KfCAA)
```sh
--parser vue
```

**Input:**
```vue
<template>
<span>{{z&&(a&&b)}}</span>
</template>
```

**Output:**
```vue
TypeError: Cannot set property 'undefined' of undefined
    at zt (https://prettier.io/lib/parser-babel.js:1:30215)
    at Wt (https://prettier.io/lib/parser-babel.js:1:30673)
    at Object.parse (https://prettier.io/lib/parser-babel.js:1:262557)
    at Object.parse (https://prettier.io/lib/standalone.js:13712:21)
    at textToDoc (https://prettier.io/lib/standalone.js:16798:27)
    at https://prettier.io/lib/standalone.js:16786:79
    at Object.embed$2 [as embed] (https://prettier.io/lib/standalone.js:22427:57)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:16786:30)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:16907:33)
    at https://prettier.io/lib/standalone.js:16871:49
```

**Comment by InsightAdimn** [comment]
Hi there. I have been having nothing but problems with Prettier, Vue and Vetur. I found this [article](https://blog.jongallant.com/2019/02/vuejs-vetur-vscode-format-eslint-issues/) by Jon Gallant that totally takes care of prettier issues. Try it out!
