### ISSUE TITLE
style is not a function 

### ISSUE THREAD

**Issue by fadytshawky** [prettier/prettier#8986]
while i'm using prettier after the update i got prettier crash when formatting a document and gives the following output.

["INFO" - 2:27:27 PM] Formatting /Users/fadyshawky/Dev/via-mobile/js/components/pages/FAQScreen.js
["INFO" - 2:27:27 PM] Using ignore file (if present) at /Users/fadyshawky/Dev/via-mobile/.prettierignore
["INFO" - 2:27:27 PM] Loaded module 'prettier@2.0.5' from '/Users/fadyshawky/Dev/via-mobile/node_modules/prettier/index.js'
["INFO" - 2:27:27 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 2:27:27 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 2:27:27 PM] Prettier Options:
{
  "filepath": "/Users/fadyshawky/Dev/via-mobile/js/components/pages/FAQScreen.js",
  "parser": "babel",
  "bracketSpacing": false,
  "jsxBracketSameLine": true,
  "singleQuote": true,
  "trailingComma": "all"
}
["ERROR" - 2:27:27 PM] Error formatting document.
TypeError: style is not a function
	at /Users/fadyshawky/Dev/via-mobile/node_modules/import-sort/lib/index.js:220:16
	at sortImports (/Users/fadyshawky/Dev/via-mobile/node_modules/import-sort/lib/index.js:24:58)
	at importSort (/Users/fadyshawky/Dev/via-mobile/node_modules/import-sort/lib/index.js:19:12)
	at organizeImports (/Users/fadyshawky/Dev/via-mobile/node_modules/prettier-plugin-import-sort/src/index.js:51:22)
	at Object.preprocess (/Users/fadyshawky/Dev/via-mobile/node_modules/prettier-plugin-import-sort/src/index.js:71:14)
	at Object.parse (/Users/fadyshawky/Dev/via-mobile/node_modules/prettier/index.js:11365:21)
	at coreFormat (/Users/fadyshawky/Dev/via-mobile/node_modules/prettier/index.js:14784:25)
	at format (/Users/fadyshawky/Dev/via-mobile/node_modules/prettier/index.js:15019:75)
	at formatWithCursor (/Users/fadyshawky/Dev/via-mobile/node_modules/prettier/index.js:15035:12)
	at /Users/fadyshawky/Dev/via-mobile/node_modules/prettier/index.js:51620:12
	at Object.format (/Users/fadyshawky/Dev/via-mobile/node_modules/prettier/index.js:51640:12)
	at t.default.<anonymous> (/Users/fadyshawky/.vscode/extensions/esbenp.prettier-vscode-5.1.3/dist/extension.js:1:58387)
	at Generator.next (<anonymous>)
	at s (/Users/fadyshawky/.vscode/extensions/esbenp.prettier-vscode-5.1.3/dist/extension.js:1:53305)
["INFO" - 2:27:27 PM] Formatting completed in 16.953236ms.

**Comment by evilebottnawi** [comment]
Please open an issue in `prettier-plugin-import-sort` repo
