### ISSUE TITLE
Cannot read property 'end' of undefined in html with front matter

### ISSUE THREAD

**Issue by domoritz** [prettier/prettier#9042]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKAbAhgTwgFcYkACAMwgi3VSywBU4BnGMgHlzIAsAnOBQC8GEDxgwADiyQB6WZIESAlnD4A6ZTRAA+XACMwHWbh3qsIADQgIkmFqgtkoXHz4QA7gAVXCJylxsDwIna30+XDAAazgYAGVJSOUoAHNkGD4iOGtxAFtsAHUeZXgWRLA4OL8S5QA3EvxkcBZQkGSWNRgvCJTc3GQKQI7rACsWAA8AIQjo2LjcXLgAGWS4AaHskDHxuOSU7DgARSIIeHXsYZBEvg6+JrzsKyu+ZJgC5QATGB5kAA4ABmsiggHQKEUkTUUrDUtTW1gAjid4N1bP4QLgWKgoHA4B9cU8BIjlAJurhev0kIMLpsOrllOlMjS9gdjqc1pSNtYYAZ3l8fkgAExciLKbB7ADCEFyfSarAArE8iB1GAZ-FTLrUsgBJKB42BxMAvOwAQV1cRg+AO5w6AF8bUA)
```sh
--parser html
```

**Input:**
```html
---
layout: foo
---

Test <a href="https://prettier.io">abc</a>.

```

**Output:**
```html
TypeError: Cannot read property 'end' of undefined
    at hasLeadingLineBreak (https://prettier.io/lib/standalone.js:21471:71)
    at hasSurroundingLineBreak (https://prettier.io/lib/standalone.js:21467:12)
    at preferHardlineAsTrailingSpaces (https://prettier.io/lib/standalone.js:21463:108)
    at preferHardlineAsLeadingSpaces (https://prettier.io/lib/standalone.js:21459:68)
    at printBetweenLine (https://prettier.io/lib/standalone.js:22701:155)
    at https://prettier.io/lib/standalone.js:22623:48
    at FastPath.map (https://prettier.io/lib/standalone.js:16730:23)
    at printChildren$1 (https://prettier.io/lib/standalone.js:22600:26)
    at Object.genericPrint$2 [as print] (https://prettier.io/lib/standalone.js:22491:41)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:16921:20)
```

**Expected behavior:**
I would expect prettier to format the html file with yaml front matter.

**Comment by fisker** [comment]
WIP
