### ISSUE TITLE
Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

### ISSUE THREAD

**Issue by iwahbe** [prettier/prettier#9151]
**Environments:**

- Prettier Version: 2.1.1
- Running Prettier via: CLI
- Runtime: Node.js (14.4.0)
- Operating System: macOS 10.15.6

**Steps to reproduce:**

```sh
❯ echo "this is a file" > test.md (any file works, I have tested markdown and javascript)
❯ node --trace-warnings /usr/local/bin/prettier test.md
```

**Expected behavior:**

A formated file is printed is printed to stdout.

**Actual behavior:**

A formate file is printed to to stdout, and some errors, and a backtrace. 
```sh
❯ node --trace-warnings /usr/local/bin/prettier test.md  
this is a file
(node:51554) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/RuleContext.js:32:46)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/PredictionContext.js:10:19)
(node:51554) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/tree/Trees.js:15:49)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/antlr4/RuleContext.js:126:13)
```

**Comment by evilebottnawi** [comment]
Please open an issue in `prettier-plugin-solidity` repo
