### ISSUE TITLE
Add support for Nullish coalescing operator (??)

### ISSUE THREAD

**Issue by CerealKiller97** [prettier/prettier#9247]
# Add support for Nullish coalescing operator (??)

**Prettier 1.18.2**

**Input:**

```jsx
this.application$ = this.store.select(
      (state: IAppState) =>
        state.application.applications.data.find(app => app.id === this.applicationId) ?? null
    );
```

**Output:**

```jsx
It output's an error. When I switch It to  || instead of ?? it works.
```

**Expected behavior:**

**Comment by sosukesuzuki** [comment]
We've already supported `??`. Please confirm Prettier version and other libraries you use.

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOgIYAOBANhmHjBtACQAEAvLetjljBAE5ytzFxgwAFAB0otcRMFsKcJLQCSAQSIBlGDICUDAHyiJ+2tPj4ipcpWgmSZClSi4AJhTw4AZhigPBhAjto+cDAcGekZmXB8zW2h5By0AfnjaKABXYmI9CQ0AbhAAGhAIAgt7ZFA8Dg4IAHcABQqELGQQPGJqvABPJoKAIw48MABrOBgVAgGPAHNkGA4UuAK4AFseuAcHNYAZPChJlLxJuAAxTiWKSl3mvBT2fJA0GCXiAHVMeCxxsDgVRoxKADc-h1mmAsN0QB4sHAODBav1JmdkK5WlCCgArLAADwAQv0hiMVHglnBNh44EiUQsQBjMSopnwAIopCDwCnEVEgcYcKEcZo9PCrYh3AgcDwwZ5BdDIAAcAAYCiKIFDnv0CM0RXAef9yQUAI7M+BwopNFB4LAAWigcDWazuXH1GC4cIOiKQyPZVKhSwwMzmnvpcCZLPJbspBXUPQlDilSAATOH+hhSLsAMIQJaukCagCsdxSUIAKgKTe6Of95vJPAhRmBRcVFJ41B0+GyoQBfNtAA)
```sh
--parser babel
```

**Input:**
```jsx
this.application$ = this.store.select(
      (state: IAppState) =>
        state.application.applications.data.find(app => app.id === this.applicationId) ?? null
    );
```

**Output:**
```jsx
this.application$ = this.store.select(
  (state: IAppState) =>
    state.application.applications.data.find(
      (app) => app.id === this.applicationId
    ) ?? null
);

```

**Comment by CerealKiller97** [comment]
My version is 1.18.2. I will download the latest one then. Thank you!

**Comment by CerealKiller97** [comment]
I've downloaded 2.1.2 version, and I still get an error.

```js
SyntaxError: Expression expected. (102:89)
  100 |     this.application$ = this.store.select( 
  101 |       (state: IAppState) =>
> 102 |         state.application.applications.data.find(app => app.id === this.applicationId) ?? null
      |                                                                                         ^
  103 |     );
  104 | 
  105 |     this.subscription.push(
    at e (C:\Users\CerealKiller\AppData\Roaming\npm\node_modules\prettier\parser-typescript.js:1:267)
    at Object.parse (C:\Users\CerealKiller\AppData\Roaming\npm\node_modules\prettier\parser-typescript.js:1:2261711)
    at Object.parse$2 [as parse] (C:\Users\CerealKiller\AppData\Roaming\npm\node_modules\prettier\index.js:10629:19)
    at coreFormat (C:\Users\CerealKiller\AppData\Roaming\npm\node_modules\prettier\index.js:13888:23)
    at format (C:\Users\CerealKiller\AppData\Roaming\npm\node_modules\prettier\index.js:14146:73)
    at formatWithCursor (C:\Users\CerealKiller\AppData\Roaming\npm\node_modules\prettier\index.js:14162:12)
    at C:\Users\CerealKiller\AppData\Roaming\npm\node_modules\prettier\index.js:42756:15
    at Object.format (C:\Users\CerealKiller\AppData\Roaming\npm\node_modules\prettier\index.js:42775:12)
    at performFormat (C:\Users\CerealKiller\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\202.7319.49\plugins\prettierJS\prettierLanguageService\prettier-plugin.js:66:29)
    at PrettierPlugin.handleReformatCommand (C:\Users\CerealKiller\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\202.7319.49\plugins\prettierJS\prettierLanguageService\prettier-plugin.js:36:16)
Process finished with exit code -1

```

**Comment by fisker** [comment]
It seems you are using a global installed Prettier, `C:\Users\CerealKiller\AppData\Roaming\npm\node_modules\prettier`, if you wan use global one, please install use `npm install --global prettier`

If you mean to use the one in your project, you can use `npx prettier .` to run Prettier

**Comment by CerealKiller97** [comment]
I have already installed prettier globally. I have configured it to work with WebStorm and everything works perfectly except null coalescing, maybe there is a bug with Webstorm and prettier. Who knows.

**Comment by evilebottnawi** [comment]
@CerealKiller97 Something wrong with out setup, try to delete global installd prettier and use local version

**Comment by asotog** [comment]
same here added prettier to project and configured workspace to use but still getting issues
