### ISSUE TITLE
Got "Comment was not printed" error

### ISSUE THREAD

**Issue by danieldunderfelt** [prettier/prettier#9255]
I updated Prettier to 2.1.2 and when I tried to reformat my `config-overrides.js` file of `customize-cra`, I got this error from a comment I had in there. The error asked me to report it, so here we are.

The error:

```
Error: Comment "Add some babel plugins" was not printed. Please report this error!
    at /path/to/project/node_modules/prettier/index.js:14755:13
    at Array.forEach (<anonymous>)
    at ensureAllCommentsPrinted (/path/to/project/node_modules/prettier/index.js:14753:15)
    at coreFormat (/path/to/project/node_modules/prettier/index.js:14801:3)
    at format (/path/to/project/node_modules/prettier/index.js:15019:75)
    at formatWithCursor (/path/to/project/node_modules/prettier/index.js:15035:12)
    at /path/to/project/node_modules/prettier/index.js:51620:12
    at Object.format (/path/to/project/node_modules/prettier/index.js:51640:12)
    at performFormat (/path/to/home/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/202.6948.87.plugins/prettierJS/prettierLanguageService/prettier-plugin.js:66:29)
    at PrettierPlugin.handleReformatCommand (/path/to/home/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/202.6948.87.plugins/prettierJS/prettierLanguageService/prettier-plugin.js:36:16)
```

The file I tried to format:

```
const { override, addBabelPlugins } = require('customize-cra')
const { addReactRefresh } = require('customize-cra-react-refresh')

module.exports = override(
  // Add some babel plugins
  ...addBabelPlugins("polished", "styled-components"),
  addReactRefresh()
)
```

Removing the comment fixes the Prettier error. I'm using Prettier through the Jetbrains integration, but rest assured, it uses the version of Prettier I have installed in my project.

**Comment by evilebottnawi** [comment]
@danieldunderfelt please use the issue template and link on playground, I can't reproduce

**Comment by thorn0** [comment]
> rest assured, it uses the version of Prettier I have installed in my project

It doesn't. The stack trace matches 2.0.5. I can't reproduce this too.
