### ISSUE TITLE
When loading two plugins of same ID, prettier should resolve to latest one

### ISSUE THREAD

**Issue by octref** [prettier/prettier#9342]
**Environments:**

- Prettier Version: 2.1.2
- Running Prettier via: API
- Runtime: Node.js v14
- Operating System: macOS

**Steps to reproduce:**

- Clone https://github.com/octref/prettier-double-plugin-load
- Run `yarn` in `/`, `/a`, `/b`
  - `/` contains `"prettier": "^2.1.2"`
  - `/a` contains `"@prettier/plugin-pug": "^1.8.1"`
  - `/b` contains `"@prettier/plugin-pug": "1.4.4"`
- `node index.js`

**Expected behavior:**

Prettier formats pug content fine

**Actual behavior:**

Prettier throws below error:

```
/Users/pine/Code/fiddle/prettier-double-plugin-load/a/node_modules/@prettier/plugin-pug/dist/printer.js:56
        if (((_a = this.tokens[0]) === null || _a === void 0 ? void 0 : _a.type) === 'text') {
                              ^

TypeError: Cannot read property '0' of undefined
    at PugPrinter.build (/Users/pine/Code/fiddle/prettier-double-plugin-load/a/node_modules/@prettier/plugin-pug/dist/printer.js:56:31)
    at Object.print (/Users/pine/Code/fiddle/prettier-double-plugin-load/a/node_modules/@prettier/plugin-pug/dist/index.js:60:40)
    at callPluginPrintFunction (/Users/pine/Code/fiddle/prettier-double-plugin-load/node_modules/prettier/index.js:14675:18)
    at /Users/pine/Code/fiddle/prettier-double-plugin-load/node_modules/prettier/index.js:14606:47
    at Object.printComments (/Users/pine/Code/fiddle/prettier-double-plugin-load/node_modules/prettier/index.js:14238:19)
    at printGenerically (/Users/pine/Code/fiddle/prettier-double-plugin-load/node_modules/prettier/index.js:14606:22)
    at printAstToDoc (/Users/pine/Code/fiddle/prettier-double-plugin-load/node_modules/prettier/index.js:14616:13)
    at coreFormat (/Users/pine/Code/fiddle/prettier-double-plugin-load/node_modules/prettier/index.js:14866:15)
    at format (/Users/pine/Code/fiddle/prettier-double-plugin-load/node_modules/prettier/index.js:15073:14)
    at formatWithCursor (/Users/pine/Code/fiddle/prettier-double-plugin-load/node_modules/prettier/index.js:15090:12)
```

When you remove either line in `pluginSearchDirs` to load only one pug plugin, it formats fine:

```
  pluginSearchDirs: [
    path.resolve(__dirname, './a'),
    path.resolve(__dirname, './b')
  ]
```

**Suggested fix:**

When loading plugins, dedupe by unique id. Pick the plugin with latest version.

**Comment by fisker** [comment]
I think better use `--plugin=path/to/your/plugin` in this case.

**Comment by octref** [comment]
But I think if you are exposing `pluginSearchDirs` as an option to load plugins from, it's highly likely you'll end up having duplicate plugins. They shouldn't cause error for prettier.

**Comment by yoyo930021** [comment]
In this case, we also can't close search plugin feature.
I need to add a exist folder, but no have any plugins to close it.
