### ISSUE TITLE
A comment on after parameter list moves before parameter list

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#9367]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCpyYw7AA6UOOAZhBDgBQD0AVDgEw7OMCUOLOAZk6MA3OQC+5EABoQEAA4wAltEzJQ6AE6aIAdwAKWhGpTpUu9AE81sgEab0YANZwYAZXmOlUAObIYmgCucLJwALa2cAAmUdEAMui+geg+cABiEJph6DDKvsgg6IEwEDIgABYwYagA6uVK8JieYHBuxg1KAG4NlgVg2GXemHCaMPoOPtnIVGbDsgBWmAAeAEIOzq5u6GFwcd5w07MhIItLbt4+qHAAioEQ8IeocyCemsOaBbbokagAtDA2F6abwwGpKKIwcrIAAcAAZZPIdMMag55AVEYQRp0DrIAI53eDjBQmQqYX5QODRaJlTRwfFKWnjFJTJAzJ7HYZhJT+IIci5XW73A6so6yGDfMEQqFINhihxKVAXADCEDCLJAhAArGVAsM8N8TGznp1ggBJKCxWBuMDAxQAQQtbhgliuj2G4nEQA)
```sh
--parser babel-ts
```

**Input:**
```tsx
class Test {
  foo (/* 2 */) /* 3 */;
}

```

**Output:**
```tsx
class Test {
  foo /* 3 */(/* 2 */);
}

```

**Expected behavior:**
```tsx
class Test {
  foo (/* 2 */) /* 3 */;
}

```

**Additional info:**

With `typescript` parser, #9324 happens.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCpyYw7AA6UOOAZhBDgBQD0AVDgEw7OMCUOLOAZk6MA3OQC+5EABoQEAA4wAltEzJQ6AE6aIAdwAKWhGpTpUu9AE81sgEab0YANZwYAZXmOlUAObIYmgCucLJwALa2cAAmUdEAMui+geg+cABiEJph6DDKvsgg6IEwEDIgABYwYagA6uVK8JieYHBuxg1KAG4NlgVg2GXemHCaMPoOPtnIVGbDsgBWmAAeAEIOzq5u6GFwcd5w07MhIItLbt4+qHAAioEQ8IeocyCemsOaBTCW8oRgmkqKMryf6wGpKKIwcrIAAcAAZZMCIMMag55AVgYQRp0DrIAI53eDjBQmQqYAC0UDg0WiZU0cHxSjp4xSUyQMyex2GYSU-iCnIuV1u9wObKOshg6FsYIhUKQbHFDiUqAuAGEIGFWSBCABWMqBYZ4SUmdnPTrBACSUFisDcfwBMAAgla3F8ro9huJxEA)
```sh
--parser typescript
```
```tsx
// Input
class Test {
  foo (/* 2 */) /* 3 */;
}

// Output
Error: Comment "3" was not printed. Please report this error!
    at https://prettier.io/lib/standalone.js:15:106002
    at Array.forEach (<anonymous>)
    at Object.ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:15:105970)
    at Xi (https://prettier.io/lib/standalone.js:15:111682)
    at Yi (https://prettier.io/lib/standalone.js:15:113795)
    at formatWithCursor (https://prettier.io/lib/standalone.js:15:113915)
    at https://prettier.io/lib/standalone.js:15:386874
    at Object.format (https://prettier.io/lib/standalone.js:15:386957)
    at formatCode (https://prettier.io/worker.js:115:21)
    at handleMessage (https://prettier.io/worker.js:66:18)
```

**Comment by fisker** [comment]
The `typescript` bug will be fixed in #9872, I'll look into the comment misplace issue later.
