### ISSUE TITLE
Crash in forceNextEmptyLine

### ISSUE THREAD

**Issue by xPaw** [prettier/prettier#9368]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjATtA5gPgENUB6THKAgWgDJcYBuDbPfAI1PNdvoZABoQEAA4wAltHTJQhLDgDuABVkIpKQgBt5hAJ5TBbLITABrODADKw42MrJsAVziC4AWzZwAJp68AZQpQOhLhwAGIQWK6EMOJ26g4wEAIgABYwrhoA6ili8OjWYHAWqrliAG65Osjg6PogtuhwWDCKRrhRyABmmo2CAFboAB4AQkam5haErnC+tnBdPc4gA4MWtrgacACKDhDwCxq9INZYjVjVaRnJwli2MJlinjApyAAcAAyCNxCNmUbC1RucDOZXmggAjrt4K0RGoQIR0FQoHAvF5klg4JCxBjWsEOkhuoclo1XGJ7FgnIJ0OtNjs9vMCYtBDBCGwHk8XkgAEzMoxiDTrADCEFc+JAwIArMkHI0ACqstSEo5lJwASSgPlgFjAt1EAEENRYYDpNgdGgBfc1AA)
```sh
--parser html
```

**Input:**
```html
<strong>a</strong>-&gt;<strong>b</strong>-&gt;
```

And even simpler:
```html
<strong>a</strong>-<strong>b</strong>-
```

**Output:**
```html
TypeError: Cannot read property 'line' of undefined
    at forceNextEmptyLine (https://prettier.io/lib/standalone.js:15:348165)
    at https://prettier.io/lib/standalone.js:15:361385
    at Ci.map (https://prettier.io/lib/standalone.js:15:107094)
    at Mv (https://prettier.io/lib/standalone.js:15:361045)
    at Object.print (https://prettier.io/lib/standalone.js:15:365539)
    at Ni (https://prettier.io/lib/standalone.js:15:109060)
    at https://prettier.io/lib/standalone.js:15:108522
    at Object.printComments (https://prettier.io/lib/standalone.js:15:104815)
    at e (https://prettier.io/lib/standalone.js:15:108503)
    at ki (https://prettier.io/lib/standalone.js:15:108568)
```

**Expected behavior:**

**Comment by xPaw** [comment]
Similarly it's also possible to trigger in `hasLeadingLineBreak` function:

**Input:**
```html
a track<strong>pad</strong>, or a <strong>gyro</strong>scope.
```

**Output:**
```html
TypeError: Cannot read property 'line' of undefined
    at dA (https://prettier.io/lib/standalone.js:15:345198)
    at pA (https://prettier.io/lib/standalone.js:15:345113)
    at preferHardlineAsLeadingSpaces (https://prettier.io/lib/standalone.js:15:350877)
    at a (https://prettier.io/lib/standalone.js:15:362022)
    at https://prettier.io/lib/standalone.js:15:361231
    at Ci.map (https://prettier.io/lib/standalone.js:15:107094)
    at Mv (https://prettier.io/lib/standalone.js:15:361045)
    at Object.print (https://prettier.io/lib/standalone.js:15:365539)
    at Ni (https://prettier.io/lib/standalone.js:15:109060)
    at https://prettier.io/lib/standalone.js:15:108522
```

**Comment by andreygolik** [comment]
I dug a little in this. But unfortunately couldn't fix.
Nevertheless I can add some additional information.

The call stack
```
    TypeError: Cannot read property 'line' of undefined

      273 |     (node.next &&
      274 |       node.sourceSpan.end &&
    > 275 |       node.sourceSpan.end.line + 1 < node.next.sourceSpan.start.line)
          |                                                                 ^
      276 |   );
      277 | }
      278 |

      at forceNextEmptyLine (src/language-html/utils.js:275:65)
      at callback (src/language-html/printer-html.js:529:13)
      at FastPath.map (src/common/fast-path.js:124:21)
      at printChildren (src/language-html/printer-html.js:479:10)
      at Object.print (src/language-html/printer-html.js:239:15)
      at callPluginPrintFunction (src/main/ast-to-doc.js:144:18)
      at print (src/main/ast-to-doc.js:64:16)
      at Object.printComments (src/main/comments.js:491:19)
      at printGenerically (src/main/ast-to-doc.js:62:22)
      at printAstToDoc (src/main/ast-to-doc.js:77:13)
```

and the content of node.next
```
    Node {
      type: 'text',
      value: '-<strong>b</strong>-',
      sourceSpan: ParseLocation {
        file: ParseSourceFile {
          content: '<strong>a</strong>-<strong>b</strong>-\n',
          url: 'angular-html-parser'
        },
        offset: 18,
        line: 0,
        col: 18
      },
      hasLeadingSpaces: false,
      hasTrailingSpaces: true,
      cssDisplay: 'inline',
      isSelfClosing: true,
      isLeadingSpaceSensitive: true,
      isTrailingSpaceSensitive: false
    }
```
