### ISSUE TITLE
Prettier should not convert `export {a as a}` to `export {a}`

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#9434]
**Prettier pr-9408**
[Playground link](https://deploy-preview-9408--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACYAQz0IGcSBfPAM2wgFs8ByQpkAGhAgxgEtpSyUIWx0A7gAURCQSkIAbMYQCegzgCNshMAGs4MAMoZtvKAHNkMbAFc4nOPXVwAJs5cAZQueuEzcAGI49IQwfObIIITWMBAcIAAWMPTyAOrxvPCkxmBwBjIZvABuGcoRYKRqIKakcLgSWmbByNQKNZwAVqRoAEJauvoGhPRw7qZwza12IJ1oBqZm8nAAitYQ8BPybSDG2DXYEeqETvJxGNimMCm8zjDxyAAcAAycZxA1KVoYEWdwe4XjnAAjqt4PVuLJIqQALRQOAuFxxbBwYG8JH1XxNJAtTZTGr0XiWGy4+aLFZrcZYyacGBHK43O5IABM1K0vHk8wAwgxMahSABWOLWGoAFSOsmxW0KtgAklA3LADGBzjwAIJygwwZSLDY1CgUIA)
```sh
--parser babel
```

**Input:**
```jsx
export {a as a} from 'a'
```

**Output:**
```jsx
export { a } from "a";

```

**Expected behavior:**
```jsx
export { a } from "a";

```

And comment will lost

**Prettier pr-9408**
[Playground link](https://deploy-preview-9408--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACYAQz0IGc8B6AKj0gFs6F8qKSBfPAM2wjrwHJC-EABoQEDDACW0UslCFsPAO4AFRQjkpCAG2WEAnnLEAjbITABrODADKGC1KgBzZDGwBXOGLh0TcABMAwIAZQhcPQmc4ADEcOkIYaRdkEEIPGAhREAALGDodAHUcqXhSBzA4W01SqQA3UoNUsFJjECdSOFxVc2cE5E5dTrEAK1I0ACFzKxtbQkYQpzgBoe8QMbRbJ2cdOABFDwh4FZ1hkAdsTuxUk0J-HWyMbCcYQqkAmBzkAA4ABjEnhBOoVzBhUk84Fc6ssxABHQ7wHoSLRpUgAWigcECgWy2Dg8KkeJ6UX6SEGpzWnToUjcnkp212ByOyzJqzEMDubw+XyQACZ2eYpDptgBhXik1CkACs2Q8nQAKnctOSznUvABJKDBWC2MDPSQAQS1thgBl2J06bDYQA)
```sh
--parser babel
```

**Input:**
```jsx
export {a as /* comment */ a} from 'a'
```

**Output:**
```jsx
Error: Comment "comment" was not printed. Please report this error!
    at https://deploy-preview-9408--prettier.netlify.app/lib/standalone.js:15:111760
    at Array.forEach (<anonymous>)
    at Object.ensureAllCommentsPrinted (https://deploy-preview-9408--prettier.netlify.app/lib/standalone.js:15:111727)
    at Xi (https://deploy-preview-9408--prettier.netlify.app/lib/standalone.js:15:117453)
    at Yi (https://deploy-preview-9408--prettier.netlify.app/lib/standalone.js:15:119639)
    at formatWithCursor (https://deploy-preview-9408--prettier.netlify.app/lib/standalone.js:15:119759)
    at https://deploy-preview-9408--prettier.netlify.app/lib/standalone.js:55:37207
    at Object.format (https://deploy-preview-9408--prettier.netlify.app/lib/standalone.js:55:37290)
    at formatCode (https://deploy-preview-9408--prettier.netlify.app/worker.js:115:21)
    at handleMessage (https://deploy-preview-9408--prettier.netlify.app/worker.js:66:18)
```

**Comment by FlorianWendelborn** [comment]
@fisker I agree that the comment shouldn’t be omitted entirely. However, why would anyone want to `export { a as a }`? Isn’t `export { a }` more desirable?

**Comment by fisker** [comment]
See discussion in  #9435
