### ISSUE TITLE
Unable to load plugins with PnP

### ISSUE THREAD

**Issue by xenoterracide** [prettier/prettier#9664]
should be able to install prettier and any prettier plugin with yarn2 (PnP enabled), and run it against the filetype, and have it fail to find the parser.
```
> yarn prettier --write api/app/src/main/java/com/xenoterracide/ppm/app/Application.java
[error] No parser could be inferred for file: api/app/src/main/java/com/xenoterracide/ppm/app/Application.java
> yarn prettier --write api/config/checkstyle/checkstyle.xml
[error] No parser could be inferred for file: api/config/checkstyle/checkstyle.xml
```
```
> yarn info prettier-plugin-java           # ppm -> 1-setup ! + ? RC=2
└─ prettier-plugin-java@npm:0.8.3
   ├─ Version: 0.8.3
   │
   └─ Dependencies
      ├─ java-parser@npm:0.8.2 → npm:0.8.2
      ├─ lodash@npm:4.17.20 → npm:4.17.20
      └─ prettier@npm:2.1.x → npm:2.1.2

> yarn info @prettier/plugin-xml           # ppm -> 1-setup ! + ? RC=2
└─ @prettier/plugin-xml@npm:0.12.0
   ├─ Version: 0.12.0
   │
   └─ Dependencies
      ├─ @xml-tools/parser@npm:^1.0.2 → npm:1.0.7
      └─ prettier@npm:>=1.10 → npm:2.1.2
```
```
> yarn --version                                # ppm -> 1-setup ! + ?
2.3.3
> node --version                                # ppm -> 1-setup ! + ?
v14.15.0
Darwin Calebs-MBP 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

one possible fix, is that you could add a plugin array to the rc file, and then do the require magic (`require.resolve` (is that it) PnP needs for dynamic dependencies.

**Comment by fisker** [comment]
Try add this to your `.prettierrc`

```js
{
	"plugins": [
		"prettier-plugin-java"
	]
}
```

**Comment by xenoterracide** [comment]
yeah, doesn't work if you don't fix the requires (using either method)

```
> yarn prettier . --plugin=prettier-plugin-java                                                  # ppm -> 1-setup ! ? RC=127
/Users/calebcushing/IdeaProjects/ppm/.pnp.js:13885
    throw firstError;
    ^

Error: Your application tried to access prettier-plugin-java, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: prettier-plugin-java (via "prettier-plugin-java")
Required by: /Users/calebcushing/IdeaProjects/ppm/

Require stack:
- /Users/calebcushing/IdeaProjects/ppm/.yarn/cache/prettier-npm-2.1.2-9d456ef3cd-bedc24c568.zip/node_modules/prettier/index.js
- /Users/calebcushing/IdeaProjects/ppm/.yarn/cache/prettier-npm-2.1.2-9d456ef3cd-bedc24c568.zip/node_modules/prettier/bin-prettier.js
    at internalTools_makeError (/Users/calebcushing/IdeaProjects/ppm/.pnp.js:13629:34)
    at resolveToUnqualified (/Users/calebcushing/IdeaProjects/ppm/.pnp.js:14582:23)
    at resolveRequest (/Users/calebcushing/IdeaProjects/ppm/.pnp.js:14680:29)
    at Object.resolveRequest (/Users/calebcushing/IdeaProjects/ppm/.pnp.js:14758:26)
    at Function.external_module_.Module._resolveFilename (/Users/calebcushing/IdeaProjects/ppm/.pnp.js:13862:34)
    at resolve (internal/modules/cjs/helpers.js:94:19)
    at /Users/calebcushing/IdeaProjects/ppm/.yarn/cache/prettier-npm-2.1.2-9d456ef3cd-bedc24c568.zip/node_modules/prettier/index.js:54623:21
    at Array.map (<anonymous>)
    at Object.load (/Users/calebcushing/IdeaProjects/ppm/.yarn/cache/prettier-npm-2.1.2-9d456ef3cd-bedc24c568.zip/node_modules/prettier/index.js:54615:61)
    at Object.load [as loadPlugins] (/Users/calebcushing/IdeaProjects/ppm/.yarn/cache/prettier-npm-2.1.2-9d456ef3cd-bedc24c568.zip/node_modules/prettier/index.js:16528:26)
```

also I suppose I could have read the api docs section, but this doesn't seem to be well documented

**Comment by xenoterracide** [comment]
oh, that would be a big derp on that one, I guess I forgot to readd it... hmm... docs should still be improved though.

**Comment by thorn0** [comment]
Closing then. There is a closely related discussion in #9385. If you have a specific idea on what needs to be improved in the docs, PRs are much appreciated.
